### PR TITLE
Add R

### PR DESCRIPTION
**Pull request by Stefan-Stojanovic**

### CODE REVIEW

**Comment by enki-hq** [comment]
Failed parsing files: 
  - r/r-core/data-type-conversion-in-r/data-type-conversion.md: 
 > No valid answer list in question node
  - r/r-core/programs-in-r/area-of-a-rectangle-r.md: 
 > No valid answer list in question node
  - r/r-core/programs-in-r/fibonacci-sequence-r.md: 
 > No valid answer list in question node
  - r/r-core/unordered-data-types-r/dictionary-methods-in-r.md: 
 > Cannot parse invalid footnotes

**Comment by enki-hq** [comment]
Failed parsing files: 
  - r/r-core/data-type-conversion-in-r/data-type-conversion.md: 
 > No valid answer list in question node
  - r/r-core/programs-in-r/area-of-a-rectangle-r.md: 
 > No valid answer list in question node
  - r/r-core/programs-in-r/fibonacci-sequence-r.md: 
 > No valid answer list in question node
  - r/r-core/unordered-data-types-r/dictionary-methods-in-r.md: 
 > Cannot parse invalid footnotes

**Comment by enki-hq** [comment]
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| math-functions-for-vectorization-in-r | No footnote matches found in content. |
| what-are-conditional-statements-r | Insight doesn't have a practice question but it has formats and context for it. |
| why-learn-r | Insight doesn't have a practice question but it has formats and context for it. |
| creating-and-storing-variables-in-r | Insight doesn't have a revision question but it has formats and context for it. |
### Workout

| Workout Name | Error Message |
|:-:|:-:|
| unordered-data-types-r | One of the mentioned insights couldn't be found in this pull request or the database. |
| data-type-conversion-in-r | One of the mentioned insights couldn't be found in this pull request or the database. |
| programs-in-r | One of the mentioned insights couldn't be found in this pull request or the database. |
| functions-in-r-ii | One of the mentioned insights couldn't be found in this pull request or the database. |
### Course

| Course Name | Error Message |
|:-:|:-:|
| r-core | We couldn't find these workouts: `data-type-conversions`. |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact content-team@enki.com.

**Comment by Stefan-Stojanovic** [comment]
I see I have some other errors, will fix them shortly

**Comment by enki-hq** [comment]
### Course

| Course Name | Error Message |
|:-:|:-:|
| r-core | We couldn't find these workouts: `data-type-conversions-in-r`. |

> If you notice anything wrong with these rules contact content-team@enki.com.

**Comment by enki-hq** [comment]
### Insight previews:
- [ ] [enkidevs/curriculum/r/r-core/conditional-statements-in-r/if-else-in-r.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/r/r-core/conditional-statements-in-r/if-else-in-r.md?ref=a9dd3d1ba466213caf46d1b4c5efb65db272244e)
- [ ] [enkidevs/curriculum/r/r-core/conditional-statements-in-r/if-statements-in-r.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/r/r-core/conditional-statements-in-r/if-statements-in-r.md?ref=a9dd3d1ba466213caf46d1b4c5efb65db272244e)
- [ ] [enkidevs/curriculum/r/r-core/conditional-statements-in-r/nesting-if-else-in-r.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/r/r-core/conditional-statements-in-r/nesting-if-else-in-r.md?ref=a9dd3d1ba466213caf46d1b4c5efb65db272244e)
- [ ] [enkidevs/curriculum/r/r-core/conditional-statements-in-r/switch-statements-in-r.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/r/r-core/conditional-statements-in-r/switch-statements-in-r.md?ref=a9dd3d1ba466213caf46d1b4c5efb65db272244e)
- [ ] [enkidevs/curriculum/r/r-core/conditional-statements-in-r/what-are-conditional-statements-r.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/r/r-core/conditional-statements-in-r/what-are-conditional-statements-r.md?ref=a9dd3d1ba466213caf46d1b4c5efb65db272244e)
- [ ] [enkidevs/curriculum/r/r-core/data-type-conversions-in-r/as-double-and-character-r.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/r/r-core/data-type-conversions-in-r/as-double-and-character-r.md?ref=a9dd3d1ba466213caf46d1b4c5efb65db272244e)
- [ ] [enkidevs/curriculum/r/r-core/data-type-conversions-in-r/as-logical-and-vector-r.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/r/r-core/data-type-conversions-in-r/as-logical-and-vector-r.md?ref=a9dd3d1ba466213caf46d1b4c5efb65db272244e)
- [ ] [enkidevs/curriculum/r/r-core/data-type-conversions-in-r/as-matrix-r.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/r/r-core/data-type-conversions-in-r/as-matrix-r.md?ref=a9dd3d1ba466213caf46d1b4c5efb65db272244e)
- [ ] [enkidevs/curriculum/r/r-core/data-type-conversions-in-r/as-numeric-and-integer-r.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/r/r-core/data-type-conversions-in-r/as-numeric-and-integer-r.md?ref=a9dd3d1ba466213caf46d1b4c5efb65db272244e)
- [ ] [enkidevs/curriculum/r/r-core/data-type-conversions-in-r/data-type-conversion-r.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/r/r-core/data-type-conversions-in-r/data-type-conversion-r.md?ref=a9dd3d1ba466213caf46d1b4c5efb65db272244e)
- [ ] [enkidevs/curriculum/r/r-core/environment-variables-in-r/global-environment-variables-in-r.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/r/r-core/environment-variables-in-r/global-environment-variables-in-r.md?ref=a9dd3d1ba466213caf46d1b4c5efb65db272244e)
- [ ] [enkidevs/curriculum/r/r-core/environment-variables-in-r/local-variables-in-r.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/r/r-core/environment-variables-in-r/local-variables-in-r.md?ref=a9dd3d1ba466213caf46d1b4c5efb65db272244e)
- [ ] [enkidevs/curriculum/r/r-core/environment-variables-in-r/local-vs-global-variables-in-r.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/r/r-core/environment-variables-in-r/local-vs-global-variables-in-r.md?ref=a9dd3d1ba466213caf46d1b4c5efb65db272244e)
- [ ] [enkidevs/curriculum/r/r-core/functions-in-r-ii/the-matrix-function-r.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/r/r-core/functions-in-r-ii/the-matrix-function-r.md?ref=a9dd3d1ba466213caf46d1b4c5efb65db272244e)
- [ ] [enkidevs/curriculum/r/r-core/functions-in-r-ii/the-reduce-function-r.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/r/r-core/functions-in-r-ii/the-reduce-function-r.md?ref=a9dd3d1ba466213caf46d1b4c5efb65db272244e)
- [ ] [enkidevs/curriculum/r/r-core/functions-in-r-ii/the-sum-function-r.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/r/r-core/functions-in-r-ii/the-sum-function-r.md?ref=a9dd3d1ba466213caf46d1b4c5efb65db272244e)
- [ ] [enkidevs/curriculum/r/r-core/functions-in-r/function-methods-in-r-ii.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/r/r-core/functions-in-r/function-methods-in-r-ii.md?ref=a9dd3d1ba466213caf46d1b4c5efb65db272244e)
- [ ] [enkidevs/curriculum/r/r-core/functions-in-r/function-methods-in-r.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/r/r-core/functions-in-r/function-methods-in-r.md?ref=a9dd3d1ba466213caf46d1b4c5efb65db272244e)
- [ ] [enkidevs/curriculum/r/r-core/functions-in-r/functions-in-r.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/r/r-core/functions-in-r/functions-in-r.md?ref=a9dd3d1ba466213caf46d1b4c5efb65db272244e)
- [ ] [enkidevs/curriculum/r/r-core/functions-in-r/the-paste-function-in-r-ii.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/r/r-core/functions-in-r/the-paste-function-in-r-ii.md?ref=a9dd3d1ba466213caf46d1b4c5efb65db272244e)
- [ ] [enkidevs/curriculum/r/r-core/functions-in-r/the-paste-function-in-r.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/r/r-core/functions-in-r/the-paste-function-in-r.md?ref=a9dd3d1ba466213caf46d1b4c5efb65db272244e)
- [ ] [enkidevs/curriculum/r/r-core/intro-to-r/first-program-hello-world-r.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/r/r-core/intro-to-r/first-program-hello-world-r.md?ref=a9dd3d1ba466213caf46d1b4c5efb65db272244e)
- [ ] [enkidevs/curriculum/r/r-core/intro-to-r/installing-r-locally.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/r/r-core/intro-to-r/installing-r-locally.md?ref=a9dd3d1ba466213caf46d1b4c5efb65db272244e)
- [ ] [enkidevs/curriculum/r/r-core/intro-to-r/what-is-r.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/r/r-core/intro-to-r/what-is-r.md?ref=a9dd3d1ba466213caf46d1b4c5efb65db272244e)
- [ ] [enkidevs/curriculum/r/r-core/intro-to-r/why-learn-r.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/r/r-core/intro-to-r/why-learn-r.md?ref=a9dd3d1ba466213caf46d1b4c5efb65db272244e)
- [ ] [enkidevs/curriculum/r/r-core/looping-techniques-in-r/apply-function.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/r/r-core/looping-techniques-in-r/apply-function.md?ref=a9dd3d1ba466213caf46d1b4c5efb65db272244e)
- [ ] [enkidevs/curriculum/r/r-core/looping-techniques-in-r/looping-techniques-in-r.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/r/r-core/looping-techniques-in-r/looping-techniques-in-r.md?ref=a9dd3d1ba466213caf46d1b4c5efb65db272244e)
- [ ] [enkidevs/curriculum/r/r-core/looping-techniques-in-r/math-functions-for-vectorization-in-r.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/r/r-core/looping-techniques-in-r/math-functions-for-vectorization-in-r.md?ref=a9dd3d1ba466213caf46d1b4c5efb65db272244e)
- [ ] [enkidevs/curriculum/r/r-core/looping-techniques-in-r/statistical-functions-for-vectorization-in-r.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/r/r-core/looping-techniques-in-r/statistical-functions-for-vectorization-in-r.md?ref=a9dd3d1ba466213caf46d1b4c5efb65db272244e)
- [ ] [enkidevs/curriculum/r/r-core/looping-techniques-in-r/the-lapply-and-sapply-functions-in-r.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/r/r-core/looping-techniques-in-r/the-lapply-and-sapply-functions-in-r.md?ref=a9dd3d1ba466213caf46d1b4c5efb65db272244e)
- [ ] [enkidevs/curriculum/r/r-core/looping-techniques-in-r/what-is-vectorization.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/r/r-core/looping-techniques-in-r/what-is-vectorization.md?ref=a9dd3d1ba466213caf46d1b4c5efb65db272244e)
- [ ] [enkidevs/curriculum/r/r-core/loops-in-r/break-and-next-in-r.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/r/r-core/loops-in-r/break-and-next-in-r.md?ref=a9dd3d1ba466213caf46d1b4c5efb65db272244e)
- [ ] [enkidevs/curriculum/r/r-core/loops-in-r/for-loops-in-r.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/r/r-core/loops-in-r/for-loops-in-r.md?ref=a9dd3d1ba466213caf46d1b4c5efb65db272244e)
- [ ] [enkidevs/curriculum/r/r-core/loops-in-r/intro-to-loops-in-r.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/r/r-core/loops-in-r/intro-to-loops-in-r.md?ref=a9dd3d1ba466213caf46d1b4c5efb65db272244e)
- [ ] [enkidevs/curriculum/r/r-core/loops-in-r/nesting-loops-in-r.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/r/r-core/loops-in-r/nesting-loops-in-r.md?ref=a9dd3d1ba466213caf46d1b4c5efb65db272244e)
- [ ] [enkidevs/curriculum/r/r-core/loops-in-r/repeat-loops-in-r.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/r/r-core/loops-in-r/repeat-loops-in-r.md?ref=a9dd3d1ba466213caf46d1b4c5efb65db272244e)
- [ ] [enkidevs/curriculum/r/r-core/loops-in-r/while-loops-in-r.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/r/r-core/loops-in-r/while-loops-in-r.md?ref=a9dd3d1ba466213caf46d1b4c5efb65db272244e)
- [ ] [enkidevs/curriculum/r/r-core/programs-in-r/area-of-a-rectangle-r.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/r/r-core/programs-in-r/area-of-a-rectangle-r.md?ref=a9dd3d1ba466213caf46d1b4c5efb65db272244e)
- [ ] [enkidevs/curriculum/r/r-core/programs-in-r/calculator-r.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/r/r-core/programs-in-r/calculator-r.md?ref=a9dd3d1ba466213caf46d1b4c5efb65db272244e)
- [ ] [enkidevs/curriculum/r/r-core/programs-in-r/factorial-r.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/r/r-core/programs-in-r/factorial-r.md?ref=a9dd3d1ba466213caf46d1b4c5efb65db272244e)
- [ ] [enkidevs/curriculum/r/r-core/programs-in-r/fibonacci-sequence-r.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/r/r-core/programs-in-r/fibonacci-sequence-r.md?ref=a9dd3d1ba466213caf46d1b4c5efb65db272244e)
- [ ] [enkidevs/curriculum/r/r-core/programs-in-r/fizz-buzz-r.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/r/r-core/programs-in-r/fizz-buzz-r.md?ref=a9dd3d1ba466213caf46d1b4c5efb65db272244e)
- [ ] [enkidevs/curriculum/r/r-core/programs-in-r/prime-number-checker-r.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/r/r-core/programs-in-r/prime-number-checker-r.md?ref=a9dd3d1ba466213caf46d1b4c5efb65db272244e)
- [ ] [enkidevs/curriculum/r/r-core/programs-in-r/reverse-a-string-r.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/r/r-core/programs-in-r/reverse-a-string-r.md?ref=a9dd3d1ba466213caf46d1b4c5efb65db272244e)
- [ ] [enkidevs/curriculum/r/r-core/reading-and-writing-data-to-and-from-files/as-numeric.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/r/r-core/reading-and-writing-data-to-and-from-files/as-numeric.md?ref=a9dd3d1ba466213caf46d1b4c5efb65db272244e)
- [ ] [enkidevs/curriculum/r/r-core/reading-and-writing-data-to-and-from-files/open-and-close-a-file.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/r/r-core/reading-and-writing-data-to-and-from-files/open-and-close-a-file.md?ref=a9dd3d1ba466213caf46d1b4c5efb65db272244e)
- [ ] [enkidevs/curriculum/r/r-core/reading-and-writing-data-to-and-from-files/readline-in-r.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/r/r-core/reading-and-writing-data-to-and-from-files/readline-in-r.md?ref=a9dd3d1ba466213caf46d1b4c5efb65db272244e)
- [ ] [enkidevs/curriculum/r/r-core/reading-and-writing-data-to-and-from-files/the-file-function.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/r/r-core/reading-and-writing-data-to-and-from-files/the-file-function.md?ref=a9dd3d1ba466213caf46d1b4c5efb65db272244e)
- [ ] [enkidevs/curriculum/r/r-core/reading-and-writing-data-to-and-from-files/writelines-in-r.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/r/r-core/reading-and-writing-data-to-and-from-files/writelines-in-r.md?ref=a9dd3d1ba466213caf46d1b4c5efb65db272244e)
- [ ] [enkidevs/curriculum/r/r-core/unordered-data-types-r/another-way-to-create-dictionaries-in-r.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/r/r-core/unordered-data-types-r/another-way-to-create-dictionaries-in-r.md?ref=a9dd3d1ba466213caf46d1b4c5efb65db272244e)
- [ ] [enkidevs/curriculum/r/r-core/unordered-data-types-r/dictionary-methods-in-r-ii.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/r/r-core/unordered-data-types-r/dictionary-methods-in-r-ii.md?ref=a9dd3d1ba466213caf46d1b4c5efb65db272244e)
- [ ] [enkidevs/curriculum/r/r-core/unordered-data-types-r/dictionary-methods-in-r.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/r/r-core/unordered-data-types-r/dictionary-methods-in-r.md?ref=a9dd3d1ba466213caf46d1b4c5efb65db272244e)
- [ ] [enkidevs/curriculum/r/r-core/unordered-data-types-r/intro-to-dictionaries-r.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/r/r-core/unordered-data-types-r/intro-to-dictionaries-r.md?ref=a9dd3d1ba466213caf46d1b4c5efb65db272244e)
- [ ] [enkidevs/curriculum/r/r-core/unordered-data-types-r/unordered-data-types-in-r-ii.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/r/r-core/unordered-data-types-r/unordered-data-types-in-r-ii.md?ref=a9dd3d1ba466213caf46d1b4c5efb65db272244e)
- [ ] [enkidevs/curriculum/r/r-core/unordered-data-types-r/unordered-data-types-in-r.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/r/r-core/unordered-data-types-r/unordered-data-types-in-r.md?ref=a9dd3d1ba466213caf46d1b4c5efb65db272244e)
- [ ] [enkidevs/curriculum/r/r-core/variables-and-data-types/assignment-operators-r.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/r/r-core/variables-and-data-types/assignment-operators-r.md?ref=a9dd3d1ba466213caf46d1b4c5efb65db272244e)
- [ ] [enkidevs/curriculum/r/r-core/variables-and-data-types/basic-data-types-r.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/r/r-core/variables-and-data-types/basic-data-types-r.md?ref=a9dd3d1ba466213caf46d1b4c5efb65db272244e)
- [ ] [enkidevs/curriculum/r/r-core/variables-and-data-types/combining-variables-in-r.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/r/r-core/variables-and-data-types/combining-variables-in-r.md?ref=a9dd3d1ba466213caf46d1b4c5efb65db272244e)
- [ ] [enkidevs/curriculum/r/r-core/variables-and-data-types/creating-and-storing-variables-in-r.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/r/r-core/variables-and-data-types/creating-and-storing-variables-in-r.md?ref=a9dd3d1ba466213caf46d1b4c5efb65db272244e)
- [ ] [enkidevs/curriculum/r/r-core/variables-and-data-types/printing-variables-in-r.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/r/r-core/variables-and-data-types/printing-variables-in-r.md?ref=a9dd3d1ba466213caf46d1b4c5efb65db272244e)

**Pull request merged**
