### PR TITLE
[Python refactor] Functions

### PR DESCRIPTION
**Pull request by sebaraba**
## Done:

- [x] more-practice-functions
- [x] functions
- [x] functions2
- [x] ciphers
- [x] functions-scope

### CODE REVIEW

**Comment by enki-hq** [comment]
Failed parsing files: 
  - python/core/functions/py-more-practice-functions.md: 
 > duplicated mapping key at line 13, column -23:
    tags:
    ^

**Comment by enki-hq** [comment]
Failed parsing files: 
  - python/core/functions/py-more-practice-functions.md: 
 > duplicated mapping key at line 13, column -23:
    tags:
    ^

**Comment by enki-hq** [comment]
### Insight previews:
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/python/core/functions/py-more-practice-functions.md?ref=bfc57527c1d0bdb8cb799c4f96db51230d4cb488
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/python/core/functions/py-practice-ciphers.md?ref=bfc57527c1d0bdb8cb799c4f96db51230d4cb488
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/python/core/functions/py-practice-functions-scope.md?ref=bfc57527c1d0bdb8cb799c4f96db51230d4cb488
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/python/core/functions/py-practice-functions.md?ref=bfc57527c1d0bdb8cb799c4f96db51230d4cb488
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/python/core/functions/py-practice-functions2.md?ref=bfc57527c1d0bdb8cb799c4f96db51230d4cb488

**Comment by lizTheDeveloper** [comment]
we got all of these in

**Pull request closed without merging**
