### PR TITLE
Update loops-part-1.md

### PR DESCRIPTION
**Pull request by nestorsgarzonc**
The loops was a error and if in the do-while loop the algorithm doesn't made nothing

### CODE REVIEW

**Comment by enki-hq** [comment]
### Insight previews:
- [ ] [enkidevs/curriculum/javascript/core/flow-control/loops-part-1.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/javascript/core/flow-control/loops-part-1.md?ref=4ff0af59ecb113b9386b315e7fbba62c3f61a42c)

**Comment by nem035** [comment]
Hi @nestorsgarzonc, thanks for the contribution!

In this particular case, the loop not functioning is intended.

I think you may have missed the sentence right above the code:

> Note that the loop will never run if the expression is never true

Maybe we should emphasize this sentence more? Something like:

> **Note** that the loop will never run if the expression is never true

We can also add (and improve) comments in the code to further elaborate:

```js
// 0 to 9
var i = 10;

// this loop will never run because i = 0
// and thus the condition i < 10 means
// 10 < 10, which is never true
while (i < 10) {
  console.log(i)
  i++;
}
```

CC @kapnobatai137 (our content lead) for an opinion

**Comment by nestorsgarzonc** [comment]
Yes, is better

**Comment by kapnobatai137** [comment]
I've applied the suggestions and I've also added a new code block in which we showcase a `while()` condition that evaluates to `true`:
```
// 0 to 9
var i = 0;
while (i < 10) {
  console.log(i);
  i++;
}
```

**Pull request merged**
