### PR TITLE
What are drawables

### PR DESCRIPTION
**Pull request by tgmiller5**
@lizTheDeveloper please include work in progress on this pull request

Update the files to reflect different types of drawables.
Need to add a Readme file. 

@lizTheDeveloper please put this in awaiting review mode

### CODE REVIEW

**Comment by enki-hq** [comment]
Invalid headline on line 0: test

**Comment by enki-hq** [comment]
Invalid token on line 1: 	author: tlawson

**Comment by enki-hq** [comment]
Invalid token on line 1: 	author: tlawson

**Comment by enki-hq** [comment]
Invalid token on line 1: 	author: tlawson

**Comment by enki-hq** [comment]
Invalid token on line 1: 	author: tlawson

**Comment by enki-hq** [comment]
Invalid token on line 1: 	author: tlawson

**Comment by enki-hq** [comment]
Invalid token on line 1: 	author: tlawson

**Comment by enki-hq** [comment]
Invalid token on line 1: 	author: tlawson

**Comment by enki-hq** [comment]
Invalid token on line 1: 	author: tlawson

**Comment by enki-hq** [comment]
Invalid token on line 1: 	author: tlawson

**Comment by enki-hq** [comment]
Invalid token on line 1: 	author: tlawson

**Comment by enki-hq** [comment]
Invalid token on line 1: 	author: tlawson

**Comment by enki-hq** [comment]
Invalid token on line 1: 	author: tlawson

**Comment by enki-hq** [comment]
Invalid token on line 1: 	author: tlawson

**Comment by enki-hq** [comment]
Invalid token on line 1: 	author: tlawson

**Comment by enki-hq** [comment]
Invalid token on line 1: 	author: tlawson

**Comment by enki-hq** [comment]
Invalid token on line 1: 	author: tlawson

**Comment by enki-hq** [comment]
Invalid token on line 1: 	author: tlawson

**Comment by enki-hq** [comment]
Invalid token on line 1: 	author: tlawson

**Comment by enki-hq** [comment]
Invalid token on line 1: 	author: tlawson

**Comment by enki-hq** [comment]
Invalid token on line 1: 	author: tlawson

**Comment by enki-hq** [comment]
Invalid token on line 1: 	author: tlawson

**Comment by enki-hq** [comment]
Invalid token on line 1: 	author: tlawson

**Comment by enki-hq** [comment]
Invalid token on line 1: 	author: tlawson

**Comment by enki-hq** [comment]
Invalid token on line 1: 	author: tlawson

**Comment by enki-hq** [comment]
Invalid token on line 1: 	author: tlawson

**Comment by enki-hq** [comment]
can not read a block mapping entry; a multiline key may not be an implicit key at line 16, column 2:
    	## Content
     ^

**Comment by enki-hq** [comment]
can not read a block mapping entry; a multiline key may not be an implicit key at line 16, column 1:
    
    ^

**Comment by enki-hq** [comment]
Invalid headline on line 0:  create-animation-drawables

**Comment by tgmiller5** [comment]
@lizTheDeveloper please put this in awaiting review mode

**Comment by tgmiller5** [comment]
@lizTheDeveloper please put this in awaiting review mode

**Comment by tgmiller5** [comment]
@lizTheDeveloper please put this in awaiting review mode

**Pull request merged**
