### PR TITLE
Linux - Type in/standalone

### PR DESCRIPTION
**Pull request by mihaiberq**

### CODE REVIEW

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| what-is-linux | <ul><li>`Image Source` pointing to `https://www.cyberciti.biz/humour/dad-what-are-clouds-made-of-in-it/` is broken because `HTTP_503`</li></ul> |
| check-iptables-firewall-status | <ul><li>`www.cyberciti.biz` pointing to `http://www.cyberciti.biz/faq/rhel-fedorta-linux-iptables-firewall-configuration-tutorial/` is broken because `HTTP_503`</li></ul> |
| how-to-pause-a-process-and-run-others-in-the-background | <ul><li>`Background processes` pointing to `http://www.cyberciti.biz/faq/linux-command-line-run-in-background/` is broken because `HTTP_503`</li></ul> |
| block-ips-using-fail2ban | Link checking took too long. Verify it manually. |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| what-is-linux | <ul><li>`Image Source` pointing to `https://www.cyberciti.biz/humour/dad-what-are-clouds-made-of-in-it/` is broken because `HTTP_503`</li></ul> |
| how-to-pause-a-process-and-run-others-in-the-background | <ul><li>`Background processes` pointing to `http://www.cyberciti.biz/faq/linux-command-line-run-in-background/` is broken because `HTTP_503`</li></ul> |
| check-iptables-firewall-status | <ul><li>`www.cyberciti.biz` pointing to `http://www.cyberciti.biz/faq/rhel-fedorta-linux-iptables-firewall-configuration-tutorial/` is broken because `HTTP_503`</li></ul> |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| how-to-pause-a-process-and-run-others-in-the-background | <ul><li>`Background processes` pointing to `http://www.cyberciti.biz/faq/linux-command-line-run-in-background/` is broken because `HTTP_503`</li></ul> |
| what-is-linux | <ul><li>`Image Source` pointing to `https://www.cyberciti.biz/humour/dad-what-are-clouds-made-of-in-it/` is broken because `HTTP_503`</li></ul> |
| check-iptables-firewall-status | <ul><li>`www.cyberciti.biz` pointing to `http://www.cyberciti.biz/faq/rhel-fedorta-linux-iptables-firewall-configuration-tutorial/` is broken because `HTTP_503`</li></ul> |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Review by kapnobatai137 — APPROVED** [review]

**Pull request merged**
