### PR TITLE
Rerender all programatically

### PR DESCRIPTION
**Pull request by milesflo**

### CODE REVIEW

**Comment by enki-hq** [comment]
end of the stream or a document separator is expected at line 7, column 8:
    answers:
           ^

**Comment by enki-hq** [comment]
end of the stream or a document separator is expected at line 7, column 8:
    answers:
           ^

**Comment by enki-hq** [comment]
end of the stream or a document separator is expected at line 2, column 1:
    ```
    ^

**Comment by enki-hq** [comment]
end of the stream or a document separator is expected at line 2, column 1:
    ```
    ^

**Comment by enki-hq** [comment]
end of the stream or a document separator is expected at line 2, column 1:
    ```
    ^

**Comment by milesflo** [comment]
Consider adding [this branch](https://github.com/enkidevs/curriculum/pull/643) before merging into master.

**Comment by enki-hq** [comment]
end of the stream or a document separator is expected at line 2, column 1:
    ```
    ^

**Comment by enki-hq** [comment]
end of the stream or a document separator is expected at line 2, column 1:
    ```
    ^

**Pull request merged**
