### PR TITLE
Update notifications-api.md

### PR DESCRIPTION
**Pull request by Stefan-Stojanovic**
Fix incorrect syntax:
 Notification.permissions -> Notification.permission*

### CODE REVIEW

**Comment by enki-hq** [comment]
### Topic

| Topic Name | Error Message |
|:-:|:-:|
| error-not-found | Topic should have at least one workout with the "workout" aspect. |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Topic

| Topic Name | Error Message |
|:-:|:-:|
| error-not-found | Topic should have at least one workout with the "workout" aspect. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Review by kapnobatai137 — CHANGES_REQUESTED** [review]
we should:
- update the resource title `developer.mozilla.org` to `Notification`
- on line 21 change \*Notification.permission\* to be inline code \`Notification.permission\`
- line 36 add a space between `//` and `notification logic` (`// notification logic`)
- replace any `var` with `let`

**Comment by enki-hq** [comment]
### Topic

| Topic Name | Error Message |
|:-:|:-:|
| error-not-found | Topic should have at least one workout with the "workout" aspect. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Topic

| Topic Name | Error Message |
|:-:|:-:|
| error-not-found | Topic should have at least one workout with the "workout" aspect. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by Stefan-Stojanovic** [comment]
> we should:
> 
> * update the resource title `developer.mozilla.org` to `Notification`
> * on line 21 change *Notification.permission* to be inline code `Notification.permission`
> * line 36 add a space between `//` and `notification logic` (`// notification logic`)
> * replace any `var` with `let`

done

**Review by kapnobatai137 — APPROVED** [review]

**Pull request merged**
