### PR TITLE
HTML Stubs course

### PR DESCRIPTION
**Pull request by matthewleach**
You can update comments, can you update this one to show:
- the tree of workouts
  - with insights under them like this ✅ <- and a status emoji

### CODE REVIEW

**Comment by enki-hq** [comment]
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/citation-elements/address.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/citation-elements/blockquotes.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/citation-elements/figure-and-figcaption.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/citation-elements/intro-bdi.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/citation-elements/intro-bdo.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/citation-elements/intro-cite.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/citation-elements/intro-q.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/computer-code/intro-code.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/computer-code/intro-kbd.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/computer-code/intro-pre.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/computer-code/intro-samp.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/computer-code/intro-var.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/core-html-elements/headings-h1-h6.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/core-html-elements/paragraphs.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/core-html-elements/update-hyperlinks.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/core-html-elements/update-images.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/formatting-elements/button.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/formatting-elements/iframe.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/formatting-elements/intro-hr.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/formatting-elements/intro-span.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/formatting-elements/meter.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/formatting-elements/progress.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/formatting-text-elements/editing-s-del-ins-u-mark.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/formatting-text-elements/emphasis-i-and-em.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/formatting-text-elements/important-b-and-strong.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/formatting-text-elements/intro-abbr.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/formatting-text-elements/intro-br.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/formatting-text-elements/intro-dfn.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/formatting-text-elements/intro-time.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/formatting-text-elements/intro-wbr.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/formatting-text-elements/small.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/formatting-text-elements/sub-and-superscript-sub-and-sup.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/forms/check-boxes.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/forms/dropdown-list.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/forms/image-button.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/forms/intro-form.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/forms/radio-buttons.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/forms/submit-and-reset.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/forms/text-area.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/forms/text-field.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/head-elements/link-external-css.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/head-elements/style-internal-css.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/head-elements/title.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/html-structure/attributes.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/html-structure/comments.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/html-structure/elements.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/html-structure/html-structure-define.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/html-structure/html-tags.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/images/image-alt.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/images/image-base.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/images/image-height-width.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/images/image-map.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/images/image-title.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/images/image-types.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/links/image-link.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/links/image-mailto.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/links/link-absolute-paths.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/links/link-download.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/links/link-relative-paths.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/links/link-target.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/lists/description-lists.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/lists/list-orders.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/lists/nested-lists.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/lists/ordered-lists.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/lists/unordered-lists.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/media/audio.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/media/embed.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/media/video.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/meta-elements/author.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/meta-elements/charset.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/meta-elements/description.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/meta-elements/http-equiv.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/meta-elements/keywords.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/meta-elements/meta-intro.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/meta-elements/robots.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/sectioning-elements/article.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/sectioning-elements/aside.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/sectioning-elements/div.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/sectioning-elements/footer.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/sectioning-elements/header.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/sectioning-elements/main.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/sectioning-elements/nav.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/sectioning-elements/section.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/sectioning-elements/semantic-containers.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/tables/caption.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/tables/colgroup-and-col.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/tables/colspan.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/tables/intro-th.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/tables/rowspan.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/tables/table-tr-and-td.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/tables/thead-tbody-and-tfoot.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/web-introduction/css-defined.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/web-introduction/html-css-browser.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/web-introduction/html-css-code.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/web-introduction/html-css-intro.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/web-introduction/html-defined.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/web-page-structure/body-element.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/web-page-structure/doctype.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/web-page-structure/head-element.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/web-page-structure/html-element.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b
- [ ] https://enkipro.com/preview-insight/sagelabs/content/Web/HTML/web-page-structure/optional-elements.md?ref=e84a37e97942a7f342b6cf4c7dff40000f7ab06b

**Comment by enki-hq** [comment]
Invalid section title on line 42: # Quiz

**Comment by enki-hq** [comment]
Invalid section title on line 42: # Quiz

**Comment by enki-hq** [comment]
Invalid section title on line 42: # Quiz

**Comment by enki-hq** [comment]
Invalid section title on line 42: # Quiz

**Comment by enki-hq** [comment]
Invalid section title on line 42: # Quiz

**Comment by enki-hq** [comment]
Invalid section title on line 42: # Quiz

**Comment by enki-hq** [comment]
Invalid section title on line 42: # Quiz

**Comment by enki-hq** [comment]
Invalid section title on line 42: # Quiz

**Comment by enki-hq** [comment]
Invalid section title on line 42: # Quiz

**Comment by enki-hq** [comment]
Invalid section title on line 42: # Quiz

**Comment by enki-hq** [comment]
Invalid section title on line 42: # Quiz

**Comment by lizTheDeveloper** [comment]
merging to local branch so I can make some updates

**Pull request merged**
