### PR TITLE
Update readmes and setupCodes for JavaScript coding insights

### PR DESCRIPTION
**Pull request by Stefan-Stojanovic**

### CODE REVIEW

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Insight previews:
- [ ] [enkidevs/curriculum/javascript/javascript-core/is-it-a-palindrome-exercise/is-it-a-palindrome-exercise.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-core/is-it-a-palindrome-exercise/is-it-a-palindrome-exercise.md?ref=155f5089983240099537fb35703fd6bde1b0e671)
- [ ] [enkidevs/curriculum/javascript/javascript-core/largest-array-element-exercise/largest-array-element-exercise.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-core/largest-array-element-exercise/largest-array-element-exercise.md?ref=155f5089983240099537fb35703fd6bde1b0e671)
- [ ] [enkidevs/curriculum/javascript/javascript-core/update-object-values-exercise/update-object-values-exercise.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-core/update-object-values-exercise/update-object-values-exercise.md?ref=155f5089983240099537fb35703fd6bde1b0e671)
- [ ] [enkidevs/curriculum/javascript/javascript-core/weekend-and-weekday-switch-exercise/weekend-and-weekday-switch.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-core/weekend-and-weekday-switch-exercise/weekend-and-weekday-switch.md?ref=155f5089983240099537fb35703fd6bde1b0e671)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/js-adding-and-sorting-arrays/js-adding-and-sorting-arrays.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/js-adding-and-sorting-arrays/js-adding-and-sorting-arrays.md?ref=155f5089983240099537fb35703fd6bde1b0e671)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/js-arithmetic-operation/js-arithmetic-operation.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/js-arithmetic-operation/js-arithmetic-operation.md?ref=155f5089983240099537fb35703fd6bde1b0e671)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/js-array-of-characters-to-string/js-array-of-characters-to-string.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/js-array-of-characters-to-string/js-array-of-characters-to-string.md?ref=155f5089983240099537fb35703fd6bde1b0e671)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/js-beginning-and-end-pairs/js-beginning-and-end-pairs.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/js-beginning-and-end-pairs/js-beginning-and-end-pairs.md?ref=155f5089983240099537fb35703fd6bde1b0e671)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/js-calculator-class/js-calculator-class.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/js-calculator-class/js-calculator-class.md?ref=155f5089983240099537fb35703fd6bde1b0e671)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/js-dice-roll/js-dice-roll.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/js-dice-roll/js-dice-roll.md?ref=155f5089983240099537fb35703fd6bde1b0e671)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/js-even-or-odd/js-even-or-odd.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/js-even-or-odd/js-even-or-odd.md?ref=155f5089983240099537fb35703fd6bde1b0e671)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/js-factorial-calculator/js-factorial-calculator.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/js-factorial-calculator/js-factorial-calculator.md?ref=155f5089983240099537fb35703fd6bde1b0e671)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/js-fibonacci-sequence/js-fibonacci-sequence.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/js-fibonacci-sequence/js-fibonacci-sequence.md?ref=155f5089983240099537fb35703fd6bde1b0e671)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/js-happy-birthday/js-happy-birthday.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/js-happy-birthday/js-happy-birthday.md?ref=155f5089983240099537fb35703fd6bde1b0e671)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/js-harmonic-series/js-harmonic-series.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/js-harmonic-series/js-harmonic-series.md?ref=155f5089983240099537fb35703fd6bde1b0e671)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/js-iterate-over-object-values/js-iterate-over-object-values.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/js-iterate-over-object-values/js-iterate-over-object-values.md?ref=155f5089983240099537fb35703fd6bde1b0e671)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/js-iterate-over-two-arrays/js-iterate-over-two-arrays.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/js-iterate-over-two-arrays/js-iterate-over-two-arrays.md?ref=155f5089983240099537fb35703fd6bde1b0e671)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/js-least-frequent-character/js-least-frequent-character.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/js-least-frequent-character/js-least-frequent-character.md?ref=155f5089983240099537fb35703fd6bde1b0e671)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/js-miles-to-kilometres/js-miles-to-kilometres.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/js-miles-to-kilometres/js-miles-to-kilometres.md?ref=155f5089983240099537fb35703fd6bde1b0e671)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/js-multiplication-table/js-multiplication-table.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/js-multiplication-table/js-multiplication-table.md?ref=155f5089983240099537fb35703fd6bde1b0e671)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/js-object-combination/js-combine-objects.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/js-object-combination/js-combine-objects.md?ref=155f5089983240099537fb35703fd6bde1b0e671)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/js-pascals-triangle/js-pascals-triangle.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/js-pascals-triangle/js-pascals-triangle.md?ref=155f5089983240099537fb35703fd6bde1b0e671)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/js-print-primes/js-print-primes.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/js-print-primes/js-print-primes.md?ref=155f5089983240099537fb35703fd6bde1b0e671)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/js-remove-duplicate-from-array/js-remove-duplicate-from-array.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/js-remove-duplicate-from-array/js-remove-duplicate-from-array.md?ref=155f5089983240099537fb35703fd6bde1b0e671)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/js-remove-odd-numbers-from-array/js-remove-odd-numbers-from-array.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/js-remove-odd-numbers-from-array/js-remove-odd-numbers-from-array.md?ref=155f5089983240099537fb35703fd6bde1b0e671)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/js-reverse-a-string/js-reverse-a-string.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/js-reverse-a-string/js-reverse-a-string.md?ref=155f5089983240099537fb35703fd6bde1b0e671)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/js-smallest-array-element/js-smallest-array-element.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/js-smallest-array-element/js-smallest-array-element.md?ref=155f5089983240099537fb35703fd6bde1b0e671)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/js-sort-arrays-in-a-object/js-sort-arrays-in-a-object.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/js-sort-arrays-in-a-object/js-sort-arrays-in-a-object.md?ref=155f5089983240099537fb35703fd6bde1b0e671)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/js-squared-object-keys/js-squared-object-keys.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/js-squared-object-keys/js-squared-object-keys.md?ref=155f5089983240099537fb35703fd6bde1b0e671)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/js-stopping-a-loop/js-stopping-a-loop.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/js-stopping-a-loop/js-stopping-a-loop.md?ref=155f5089983240099537fb35703fd6bde1b0e671)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/js-string-length/js-string-length.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/js-string-length/js-string-length.md?ref=155f5089983240099537fb35703fd6bde1b0e671)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/js-sum-and-product-of-two-arrays/js-sum-and-product-of-two-arrays.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/js-sum-and-product-of-two-arrays/js-sum-and-product-of-two-arrays.md?ref=155f5089983240099537fb35703fd6bde1b0e671)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/js-sum-items-in-object/js-sum-items-in-object.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/js-sum-items-in-object/js-sum-items-in-object.md?ref=155f5089983240099537fb35703fd6bde1b0e671)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/js-word-length/js-word-length.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/js-word-length/js-word-length.md?ref=155f5089983240099537fb35703fd6bde1b0e671)

**Review by nem035 — APPROVED** [review]
Nice :fist_raised:

**Review by nem035 — APPROVED** [review]

**Pull request merged**
