### PR TITLE
Update what-is-go.md

### PR DESCRIPTION
**Pull request by Dungle12345**
Anh

### CODE REVIEW

**Comment by enki-hq** [comment]
Failed parsing files: 
  - go/go-introduction/go-introduction/what-is-go.md: 
 > Cannot compile node with invalid type paragraph

**Comment by Dungle12345** [comment]
Hshd###

**Comment by Dungle12345** [comment]
Gdjdjxj

**Comment by Dungle12345** [comment]
Anh

**Comment by Dungle12345** [comment]
Anh

**Comment by enki-hq** [comment]
Failed parsing files: 
  - go/go-introduction/go-introduction/what-is-go.md: 
 > Cannot compile node with invalid type paragraph

**Comment by Dungle12345** [comment]
Anh

**Comment by Dungle12345** [comment]
https://github.com/enkidevs/curriculum.wiki.git

**Comment by Dungle12345** [comment]
Bsnshdhdjdjdjejejejjeje

**Comment by Dungle12345** [comment]
Hu

**Comment by Dungle12345** [comment]
123456789

**Comment by Dungle12345** [comment]
nhưngDungle12345

**Pull request closed without merging**
