### PR TITLE
Update iife-pattern.md

### PR DESCRIPTION
**Pull request by hellotaotao**

### CODE REVIEW

**Comment by enki-hq** [comment]
### Insight previews:
- [ ] [enkidevs/curriculum/javascript/javascript-core/functions-ii/iife-pattern.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-core/functions-ii/iife-pattern.md?ref=0450231ba477888170cbf78043b886e168a1cce8)

**Comment by nem035** [comment]
Hi @hellotaotao, thanks for your contribution :fist_raised: 

Before I accept it, I wanted to clarify something about IIFEs.

For regular functions, both ways of writing an IIFE are perfectly valid.

```js
(function () {
  console.log('this works');
}());
// ^ invocation parenthesis are inside the outer parenthesis

(function () {
  console.log('so does this');
})();
// ^ invocation parenthesis are outside of the outer parenthesis
```

Try the code above, the output will be:
Screenshot from 2021-03-25 16-50-12

[Checkout this SO thread for more details.](https://stackoverflow.com/questions/3384504/location-of-parenthesis-for-auto-executing-anonymous-javascript-functions)

---

In the case of [arrow functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions) however, the placement of the `()` **does matter** .

```js
(() => {
  console.log('this does not work');
}()); // <-- ERROR
// ^ invocation parenthesis are inside the outer parenthesis

(() => {
  console.log('but this works');
})();
// ^ invocation parenthesis are outside of the outer parenthesis
```

The short answer of why is that it the `=>` symbol is read in a different order by JavaScript than the `function` keyword, leading it to "wrongly" confuse an IIFE with a a function that returns an invoked object, i.e. `() => {}()`.

[See this SO answer for a detailed explanation](https://stackoverflow.com/a/34589765)

Since both regular and arrow function IIFE's work with the `()` on the outside, your contribution makes more sense :muscle:

**Review by kapnobatai137 — APPROVED** [review]

**Comment by hellotaotao** [comment]
hi @nem035
Thank you for your very detailed explanation. 
I have to admit that my pull request here was very biased because it is mainly based on my personal preference when both syntaxes are valid. That said, I feel I am not alone because even the articles provided in the "Learn More" section also seem to prefer putting the () on the outside.
However, now I realise that my PR has created an obvious inconsistency in this article, as in the beginning of the article the syntax has now been changed to (function(){})() while the example code later is still using (function(){}()).
Please either revert my PR, or update the example as well. I am happy with either, but something has to be done to keep the consistency.
I am sorry for my hasty PR.

**Comment by kapnobatai137** [comment]
> hi @nem035
> Thank you for your very detailed explanation.
> I have to admit that my pull request here was very biased because it is mainly based on my personal preference when both syntaxes are valid. That said, I feel I am not alone because even the articles provided in the "Learn More" section also seem to prefer putting the () on the outside.
> However, now I realise that my PR has created an obvious inconsistency in this article, as in the beginning of the article the syntax has now been changed to (function(){})() while the example code later is still using (function(){}()).
> Please either revert my PR, or update the example as well. I am happy with either, but something has to be done to keep the consistency.
> I am sorry for my hasty PR.

Hey @hellotaotao,

Thanks again for your PR, it wasn't hasty and it helped us improve our content :muscle:. 

After we merged it, we create a new PR (#2665) to update the second example as well as include @nem035's comment as a footnote in the comment, so everything is good now :ok_hand:

**Pull request merged**
