### PR TITLE
replace old note format with emojis in web

### PR DESCRIPTION
**Pull request by Stefan-Stojanovic**

### CODE REVIEW

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| thead-tbody-and-tfoot | <ul><li>`CodePen: Scrolling Table CSS` pointing to `https://codepen.io/enkidevs/pen/JBXyoJ` is broken because `HTTP_403`</li><li>`Codepen Example` pointing to `https://codepen.io/stefan-stojanovic/pen/jKbJgQ` is broken because `HTTP_403`</li></ul> |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| thead-tbody-and-tfoot | <ul><li>`CodePen: Scrolling Table CSS` pointing to `https://codepen.io/enkidevs/pen/JBXyoJ` is broken because `HTTP_403`</li><li>`Codepen Example` pointing to `https://codepen.io/stefan-stojanovic/pen/jKbJgQ` is broken because `HTTP_403`</li></ul> |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| thead-tbody-and-tfoot | <ul><li>`CodePen: Table example` pointing to `https://codepen.io/stefan-stojanovic/pen/jKbJgQ` is broken because `HTTP_403`</li></ul> |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Insight previews:
- [ ] [enkidevs/curriculum/web/html/citation-elements/intro-bdo.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/web/html/citation-elements/intro-bdo.md?ref=1aa05200646f17ce461634f6df029dd73d568591)
- [ ] [enkidevs/curriculum/web/html/computer-code/intro-code.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/web/html/computer-code/intro-code.md?ref=1aa05200646f17ce461634f6df029dd73d568591)
- [ ] [enkidevs/curriculum/web/html/formatting-elements/button.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/web/html/formatting-elements/button.md?ref=1aa05200646f17ce461634f6df029dd73d568591)
- [ ] [enkidevs/curriculum/web/html/formatting-elements/intro-hr.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/web/html/formatting-elements/intro-hr.md?ref=1aa05200646f17ce461634f6df029dd73d568591)
- [ ] [enkidevs/curriculum/web/html/formatting-text-elements-ii/intro-dfn.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/web/html/formatting-text-elements-ii/intro-dfn.md?ref=1aa05200646f17ce461634f6df029dd73d568591)
- [ ] [enkidevs/curriculum/web/html/formatting-text-elements-ii/intro-wbr.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/web/html/formatting-text-elements-ii/intro-wbr.md?ref=1aa05200646f17ce461634f6df029dd73d568591)
- [ ] [enkidevs/curriculum/web/html/formatting-text-elements/editing-u-mark.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/web/html/formatting-text-elements/editing-u-mark.md?ref=1aa05200646f17ce461634f6df029dd73d568591)
- [ ] [enkidevs/curriculum/web/html/formatting-text-elements/sub-and-superscript-sub-and-sup.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/web/html/formatting-text-elements/sub-and-superscript-sub-and-sup.md?ref=1aa05200646f17ce461634f6df029dd73d568591)
- [ ] [enkidevs/curriculum/web/html/forms-ii/check-boxes.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/web/html/forms-ii/check-boxes.md?ref=1aa05200646f17ce461634f6df029dd73d568591)
- [ ] [enkidevs/curriculum/web/html/forms-ii/checkbox-groups.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/web/html/forms-ii/checkbox-groups.md?ref=1aa05200646f17ce461634f6df029dd73d568591)
- [ ] [enkidevs/curriculum/web/html/forms-ii/radio-buttons-ii.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/web/html/forms-ii/radio-buttons-ii.md?ref=1aa05200646f17ce461634f6df029dd73d568591)
- [ ] [enkidevs/curriculum/web/html/forms-ii/radio-buttons.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/web/html/forms-ii/radio-buttons.md?ref=1aa05200646f17ce461634f6df029dd73d568591)
- [ ] [enkidevs/curriculum/web/html/forms-iii/min-and-max.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/web/html/forms-iii/min-and-max.md?ref=1aa05200646f17ce461634f6df029dd73d568591)
- [ ] [enkidevs/curriculum/web/html/forms-iii/range.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/web/html/forms-iii/range.md?ref=1aa05200646f17ce461634f6df029dd73d568591)
- [ ] [enkidevs/curriculum/web/html/forms-iv/height-and-width.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/web/html/forms-iv/height-and-width.md?ref=1aa05200646f17ce461634f6df029dd73d568591)
- [ ] [enkidevs/curriculum/web/html/forms/text-field.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/web/html/forms/text-field.md?ref=1aa05200646f17ce461634f6df029dd73d568591)
- [ ] [enkidevs/curriculum/web/html/global-attributes/global-attributes-3.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/web/html/global-attributes/global-attributes-3.md?ref=1aa05200646f17ce461634f6df029dd73d568591)
- [ ] [enkidevs/curriculum/web/html/html-best-practices/doctype-always-first.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/web/html/html-best-practices/doctype-always-first.md?ref=1aa05200646f17ce461634f6df029dd73d568591)
- [ ] [enkidevs/curriculum/web/html/html-entities/non-breaking-space.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/web/html/html-entities/non-breaking-space.md?ref=1aa05200646f17ce461634f6df029dd73d568591)
- [ ] [enkidevs/curriculum/web/html/html-structure/elements.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/web/html/html-structure/elements.md?ref=1aa05200646f17ce461634f6df029dd73d568591)
- [ ] [enkidevs/curriculum/web/html/links/link-absolute-paths.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/web/html/links/link-absolute-paths.md?ref=1aa05200646f17ce461634f6df029dd73d568591)
- [ ] [enkidevs/curriculum/web/html/links/link-target.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/web/html/links/link-target.md?ref=1aa05200646f17ce461634f6df029dd73d568591)
- [ ] [enkidevs/curriculum/web/html/lists/list-orders.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/web/html/lists/list-orders.md?ref=1aa05200646f17ce461634f6df029dd73d568591)
- [ ] [enkidevs/curriculum/web/html/media/video-formats.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/web/html/media/video-formats.md?ref=1aa05200646f17ce461634f6df029dd73d568591)
- [ ] [enkidevs/curriculum/web/html/meta-elements-ii/http-equiv.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/web/html/meta-elements-ii/http-equiv.md?ref=1aa05200646f17ce461634f6df029dd73d568591)
- [ ] [enkidevs/curriculum/web/html/meta-elements/meta-intro.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/web/html/meta-elements/meta-intro.md?ref=1aa05200646f17ce461634f6df029dd73d568591)
- [ ] [enkidevs/curriculum/web/html/meter-and-progress/meter-attributes-ii.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/web/html/meter-and-progress/meter-attributes-ii.md?ref=1aa05200646f17ce461634f6df029dd73d568591)
- [ ] [enkidevs/curriculum/web/html/sectioning-elements/nav.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/web/html/sectioning-elements/nav.md?ref=1aa05200646f17ce461634f6df029dd73d568591)
- [ ] [enkidevs/curriculum/web/html/semantic-sections/section.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/web/html/semantic-sections/section.md?ref=1aa05200646f17ce461634f6df029dd73d568591)
- [ ] [enkidevs/curriculum/web/html/tables/caption.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/web/html/tables/caption.md?ref=1aa05200646f17ce461634f6df029dd73d568591)
- [ ] [enkidevs/curriculum/web/html/tables/thead-tbody-and-tfoot.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/web/html/tables/thead-tbody-and-tfoot.md?ref=1aa05200646f17ce461634f6df029dd73d568591)
- [ ] [enkidevs/curriculum/web/html/web-page-structure/head-element.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/web/html/web-page-structure/head-element.md?ref=1aa05200646f17ce461634f6df029dd73d568591)
- [ ] [enkidevs/curriculum/web/styling/colors-tips/hexadecimal-color-system.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/web/styling/colors-tips/hexadecimal-color-system.md?ref=1aa05200646f17ce461634f6df029dd73d568591)
- [ ] [enkidevs/curriculum/web/styling/css-basics/internal-css.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/web/styling/css-basics/internal-css.md?ref=1aa05200646f17ce461634f6df029dd73d568591)
- [ ] [enkidevs/curriculum/web/styling/responsive-design-tips/disabling-default-callouts-using-webkit-touch-callout.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/web/styling/responsive-design-tips/disabling-default-callouts-using-webkit-touch-callout.md?ref=1aa05200646f17ce461634f6df029dd73d568591)

**Review by nem035 — APPROVED** [review]

**Pull request merged**
