### PR TITLE
Fix: Typo, -m was missing

### PR DESCRIPTION
**Pull request by devskyrocket**

### CODE REVIEW

**Comment by enki-hq** [comment]
### Insight previews:
- [ ] [enkidevs/curriculum/git/essentials/commits/how-to-write-a-git-commit-message.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/git/essentials/commits/how-to-write-a-git-commit-message.md?ref=f207ed4e9bb88cc22e78531766f05380a547e65a)

**Comment by devskyrocket** [comment]
@nem035 I'm refreshing my knowledge, and the Enki app is fantastic for this! I just want to contribute back with this little typo fix.

**Review by nem035 — APPROVED** [review]
Thanks for the contribution, stoked to hear you're enjoying the app. Happy learning!

**Comment by Stefan-Stojanovic** [comment]
Thank you for your contribution! I've merged your changes 🚀

**Pull request merged**
