### PR TITLE
update questions & questions metadata for react topic

### PR DESCRIPTION
**Pull request by Loopiezlol**

### CODE REVIEW

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| react-shallow-compare-in-react | The revision question context `insight:question-format-context`is unrecognized. |
| react-shortcut-for-transferring-props | The practice question context `insight:question-format-context` is unrecognized. |
| react-use-proptypes-on-stateless-components | The practice question context `insight:question-format-context` is unrecognized. |
| react-the-redux-store | The practice question context `insight:question-format-context` is unrecognized. |
| react-understanding-pure-impure-functions | The practice question context `insight:question-format-context` is unrecognized. |
| react-use-redux-with-react-2 | The practice question context `insight:question-format-context` is unrecognized. |
| react-use-redux-with-react | The practice question context `insight:question-format-context` is unrecognized. |
| react-your-first-reducer | The practice question context `insight:question-format-context` is unrecognized. |
| react-component-lifecycle-methods | The practice question context `insight:question-format-context` is unrecognized. |
| react-event-handling-in-react | The practice question context `insight:question-format-context` is unrecognized. |
| react-forms-in-react | The practice question context `insight:question-format-context` is unrecognized. |
| react-rendering-multiple-components | The practice question context `insight:question-format-context` is unrecognized. |
| react-the-component-lifecycle | The practice question context `insight:question-format-context` is unrecognized. |
| react-conditional-rendering-part-1 | The practice question context `insight:question-format-context` is unrecognized. |
| react-conditional-rendering-part-2 | The practice question context `insight:question-format-context` is unrecognized. |
| react-destructuring-arguments | The practice question context `insight:question-format-context` is unrecognized. |
| react-jsx-spread-attributes | The practice question context `insight:question-format-context` is unrecognized. |
| react-the-ref-callback-attribute | The practice question context `insight:question-format-context` is unrecognized. |
| react-what-i-need-to-use-react | The practice question context `insight:question-format-context` is unrecognized. |
| react-what-is-jsx | The practice question context `insight:question-format-context` is unrecognized. |
| react-what-is-react | The practice question context `insight:question-format-context` is unrecognized. |
| react-why-use-react | The practice question context `insight:question-format-context` is unrecognized. |
| react-data-flow-in-react | The practice question context `insight:question-format-context` is unrecognized. |
| react-function-components | The practice question context `insight:question-format-context` is unrecognized. |
| react-what-are-props | The practice question context `insight:question-format-context` is unrecognized. |
| react-what-is-state | The practice question context `insight:question-format-context` is unrecognized. |
| react-the-react-component | The revision question context `insight:question-format-context`is unrecognized. |
| react-the-react-element | The practice question context `insight:question-format-context` is unrecognized. |
| react-using-react-components | The practice question context `insight:question-format-context` is unrecognized. |
| react-current-state-and-next-state | The practice question context `insight:question-format-context` is unrecognized. |
| react-dependency-array-for-useeffect-ii | The practice question context `insight:question-format-context` is unrecognized. |
| react-dependency-array-for-useeffect | The practice question context `insight:question-format-context` is unrecognized. |
| react-dont-mutate-state | The practice question context `insight:question-format-context` is unrecognized. |
| react-setstate-is-async | The practice question context `insight:question-format-context` is unrecognized. |
| react-avoid-array-mutations | The practice question context `insight:question-format-context` is unrecognized. |
| react-avoid-object-mutations | The practice question context `insight:question-format-context` is unrecognized. |
| react-combine-reducers-in-redux | The practice question context `insight:question-format-context` is unrecognized. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| react-shallow-compare-in-react | The revision question context `insight:question-format-context`is unrecognized. |
| react-shortcut-for-transferring-props | The practice question context `insight:question-format-context` is unrecognized. |
| react-use-proptypes-on-stateless-components | The practice question context `insight:question-format-context` is unrecognized. |
| react-the-redux-store | The practice question context `insight:question-format-context` is unrecognized. |
| react-understanding-pure-impure-functions | The practice question context `insight:question-format-context` is unrecognized. |
| react-use-redux-with-react-2 | The practice question context `insight:question-format-context` is unrecognized. |
| react-use-redux-with-react | The practice question context `insight:question-format-context` is unrecognized. |
| react-your-first-reducer | The practice question context `insight:question-format-context` is unrecognized. |
| react-component-lifecycle-methods | The practice question context `insight:question-format-context` is unrecognized. |
| react-event-handling-in-react | The practice question context `insight:question-format-context` is unrecognized. |
| react-forms-in-react | The practice question context `insight:question-format-context` is unrecognized. |
| react-rendering-multiple-components | The practice question context `insight:question-format-context` is unrecognized. |
| react-the-component-lifecycle | The practice question context `insight:question-format-context` is unrecognized. |
| react-conditional-rendering-part-1 | The practice question context `insight:question-format-context` is unrecognized. |
| react-conditional-rendering-part-2 | The practice question context `insight:question-format-context` is unrecognized. |
| react-destructuring-arguments | The practice question context `insight:question-format-context` is unrecognized. |
| react-jsx-spread-attributes | The practice question context `insight:question-format-context` is unrecognized. |
| react-the-ref-callback-attribute | The practice question context `insight:question-format-context` is unrecognized. |
| react-what-i-need-to-use-react | The practice question context `insight:question-format-context` is unrecognized. |
| react-what-is-jsx | The practice question context `insight:question-format-context` is unrecognized. |
| react-what-is-react | The practice question context `insight:question-format-context` is unrecognized. |
| react-why-use-react | The practice question context `insight:question-format-context` is unrecognized. |
| react-data-flow-in-react | The practice question context `insight:question-format-context` is unrecognized. |
| react-function-components | The practice question context `insight:question-format-context` is unrecognized. |
| react-what-are-props | The practice question context `insight:question-format-context` is unrecognized. |
| react-what-is-state | The practice question context `insight:question-format-context` is unrecognized. |
| react-the-react-component | The revision question context `insight:question-format-context`is unrecognized. |
| react-the-react-element | The practice question context `insight:question-format-context` is unrecognized. |
| react-using-react-components | The practice question context `insight:question-format-context` is unrecognized. |
| react-current-state-and-next-state | The practice question context `insight:question-format-context` is unrecognized. |
| react-dependency-array-for-useeffect-ii | The practice question context `insight:question-format-context` is unrecognized. |
| react-dependency-array-for-useeffect | The practice question context `insight:question-format-context` is unrecognized. |
| react-dont-mutate-state | The practice question context `insight:question-format-context` is unrecognized. |
| react-setstate-is-async | The practice question context `insight:question-format-context` is unrecognized. |
| react-avoid-array-mutations | The practice question context `insight:question-format-context` is unrecognized. |
| react-avoid-object-mutations | The practice question context `insight:question-format-context` is unrecognized. |
| react-combine-reducers-in-redux | The practice question context `insight:question-format-context` is unrecognized. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Insight previews:
- [ ] [enkidevs/curriculum/react/react-intermediary/hooks-i/react-custom-hooks.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-intermediary/hooks-i/react-custom-hooks.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-intermediary/hooks-i/react-dependency-array.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-intermediary/hooks-i/react-dependency-array.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-intermediary/hooks-i/react-effects-with-cleanup.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-intermediary/hooks-i/react-effects-with-cleanup.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-intermediary/hooks-i/react-state-variables.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-intermediary/hooks-i/react-state-variables.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-intermediary/hooks-i/react-using-custom-hooks.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-intermediary/hooks-i/react-using-custom-hooks.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-intermediary/props-i/react-custom-proptype-s-to-be-required.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-intermediary/props-i/react-custom-proptype-s-to-be-required.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-intermediary/props-i/react-custom-validations-for-props.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-intermediary/props-i/react-custom-validations-for-props.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-intermediary/props-i/react-default-values-for-props.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-intermediary/props-i/react-default-values-for-props.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-intermediary/props-i/react-enhanced-prop-validation.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-intermediary/props-i/react-enhanced-prop-validation.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-intermediary/props-i/react-prop-validation.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-intermediary/props-i/react-prop-validation.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-intermediary/props-ii/react-children-in-react.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-intermediary/props-ii/react-children-in-react.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-intermediary/props-ii/react-children-methods.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-intermediary/props-ii/react-children-methods.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-intermediary/props-ii/react-specify-a-single-child.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-intermediary/props-ii/react-specify-a-single-child.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-intermediary/props-ii/react-type-of-the-children-props.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-intermediary/props-ii/react-type-of-the-children-props.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-intermediary/props-iii/react-clone-elements-in-react.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-intermediary/props-iii/react-clone-elements-in-react.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-intermediary/props-iii/react-shallow-compare-in-function-components.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-intermediary/props-iii/react-shallow-compare-in-function-components.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-intermediary/props-iii/react-shallow-compare-in-react.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-intermediary/props-iii/react-shallow-compare-in-react.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-intermediary/props-iii/react-shortcut-for-transferring-props.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-intermediary/props-iii/react-shortcut-for-transferring-props.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-intermediary/props-iii/react-use-proptypes-on-stateless-components.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-intermediary/props-iii/react-use-proptypes-on-stateless-components.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-intermediary/react-redux-i/react-the-redux-store.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-intermediary/react-redux-i/react-the-redux-store.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-intermediary/react-redux-i/react-understanding-pure-impure-functions.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-intermediary/react-redux-i/react-understanding-pure-impure-functions.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-intermediary/react-redux-i/react-use-redux-with-react-2.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-intermediary/react-redux-i/react-use-redux-with-react-2.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-intermediary/react-redux-i/react-use-redux-with-react.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-intermediary/react-redux-i/react-use-redux-with-react.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-intermediary/react-redux-i/react-your-first-reducer.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-intermediary/react-redux-i/react-your-first-reducer.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-introduction/basics-i/react-component-lifecycle-methods.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-introduction/basics-i/react-component-lifecycle-methods.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-introduction/basics-i/react-event-handling-in-react.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-introduction/basics-i/react-event-handling-in-react.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-introduction/basics-i/react-forms-in-react.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-introduction/basics-i/react-forms-in-react.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-introduction/basics-i/react-rendering-multiple-components.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-introduction/basics-i/react-rendering-multiple-components.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-introduction/basics-i/react-the-component-lifecycle.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-introduction/basics-i/react-the-component-lifecycle.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-introduction/basics-ii/react-conditional-rendering-part-1.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-introduction/basics-ii/react-conditional-rendering-part-1.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-introduction/basics-ii/react-conditional-rendering-part-2.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-introduction/basics-ii/react-conditional-rendering-part-2.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-introduction/basics-ii/react-destructuring-arguments.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-introduction/basics-ii/react-destructuring-arguments.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-introduction/basics-ii/react-jsx-spread-attributes.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-introduction/basics-ii/react-jsx-spread-attributes.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-introduction/basics-ii/react-the-ref-callback-attribute.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-introduction/basics-ii/react-the-ref-callback-attribute.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-introduction/intro-react/react-what-i-need-to-use-react.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-introduction/intro-react/react-what-i-need-to-use-react.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-introduction/intro-react/react-what-is-jsx.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-introduction/intro-react/react-what-is-jsx.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-introduction/intro-react/react-what-is-react.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-introduction/intro-react/react-what-is-react.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-introduction/intro-react/react-why-use-react.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-introduction/intro-react/react-why-use-react.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-introduction/introduction-to-hooks/react-effect-hooks.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-introduction/introduction-to-hooks/react-effect-hooks.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-introduction/introduction-to-hooks/react-rules-of-hooks.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-introduction/introduction-to-hooks/react-rules-of-hooks.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-introduction/introduction-to-hooks/react-state-hooks.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-introduction/introduction-to-hooks/react-state-hooks.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-introduction/introduction-to-hooks/react-what-are-hooks.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-introduction/introduction-to-hooks/react-what-are-hooks.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-introduction/introduction-to-hooks/react-why-were-hooks-needed.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-introduction/introduction-to-hooks/react-why-were-hooks-needed.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-introduction/react-fundamentals-ii/react-data-flow-in-react.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-introduction/react-fundamentals-ii/react-data-flow-in-react.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-introduction/react-fundamentals-ii/react-function-components.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-introduction/react-fundamentals-ii/react-function-components.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-introduction/react-fundamentals-ii/react-what-are-props.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-introduction/react-fundamentals-ii/react-what-are-props.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-introduction/react-fundamentals-ii/react-what-is-state.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-introduction/react-fundamentals-ii/react-what-is-state.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-introduction/react-fundamentals/react-the-react-component.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-introduction/react-fundamentals/react-the-react-component.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-introduction/react-fundamentals/react-the-react-element.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-introduction/react-fundamentals/react-the-react-element.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-introduction/react-fundamentals/react-using-react-components.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-introduction/react-fundamentals/react-using-react-components.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-tips/common-mistakes-in-react/react-current-state-and-next-state.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-tips/common-mistakes-in-react/react-current-state-and-next-state.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-tips/common-mistakes-in-react/react-dependency-array-for-useeffect-ii.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-tips/common-mistakes-in-react/react-dependency-array-for-useeffect-ii.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-tips/common-mistakes-in-react/react-dependency-array-for-useeffect.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-tips/common-mistakes-in-react/react-dependency-array-for-useeffect.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-tips/common-mistakes-in-react/react-dont-mutate-state.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-tips/common-mistakes-in-react/react-dont-mutate-state.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-tips/common-mistakes-in-react/react-setstate-is-async.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-tips/common-mistakes-in-react/react-setstate-is-async.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-tips/common-mistakes-in-react/react-value-types-and-the-initial-state.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-tips/common-mistakes-in-react/react-value-types-and-the-initial-state.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-tips/react-good-to-know/react-fragments-in-react.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-tips/react-good-to-know/react-fragments-in-react.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-tips/react-good-to-know/react-immutability-helpers-in-react.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-tips/react-good-to-know/react-immutability-helpers-in-react.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-tips/react-good-to-know/react-load-initial-data-via-ajax.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-tips/react-good-to-know/react-load-initial-data-via-ajax.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-tips/react-good-to-know/react-null-value-for-controlled-components-in-react.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-tips/react-good-to-know/react-null-value-for-controlled-components-in-react.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-tips/react-good-to-know/react-reactdom-render-ref.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-tips/react-good-to-know/react-reactdom-render-ref.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-tips/react-gotchas/react-dangerously-set-innerhtml.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-tips/react-gotchas/react-dangerously-set-innerhtml.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-tips/react-gotchas/react-if-else-statements-in-jsx-and-react.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-tips/react-gotchas/react-if-else-statements-in-jsx-and-react.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-tips/react-gotchas/react-react-in-line-styles.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-tips/react-gotchas/react-react-in-line-styles.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-tips/react-gotchas/react-self-closing-tags-in-jsx.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-tips/react-gotchas/react-self-closing-tags-in-jsx.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-tips/react-gotchas/react-using-false-in-jsx.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-tips/react-gotchas/react-using-false-in-jsx.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-tips/redux-tips/react-async-flow-in-redux.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-tips/redux-tips/react-async-flow-in-redux.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-tips/redux-tips/react-avoid-array-mutations.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-tips/redux-tips/react-avoid-array-mutations.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-tips/redux-tips/react-avoid-object-mutations.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-tips/redux-tips/react-avoid-object-mutations.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)
- [ ] [enkidevs/curriculum/react/react-tips/redux-tips/react-combine-reducers-in-redux.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/react/react-tips/redux-tips/react-combine-reducers-in-redux.md?ref=ed4ddaba6842c0842c80da7b6b583deb1145031e)

**Comment by enki-hq** [comment]
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| react-what-is-state | Link checking took too long. Verify it manually. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Review by kapnobatai137 — DISMISSED** [review]

**Review by kapnobatai137 — APPROVED** [review]

**Pull request merged**
