### PR TITLE
Add Python looping discussion insight 

### PR DESCRIPTION
**Pull request by Stefan-Stojanovic**

### CODE REVIEW

**Comment by enki-hq** [comment]
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| python-looping-discussion-insight | No Enki username has been found for this author. |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| python-looping-discussion-insight | No Enki username has been found for this author. |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| python-looping-discussion-insight | No Enki username has been found for this author. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Insight previews:
- [ ] [enkidevs/curriculum/python/python-core/looping/python-looping-discussion-insight.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/python/python-core/looping/python-looping-discussion-insight.md?ref=562f5cfceabc40431530c1be054714cf811275ec)

**Review by kapnobatai137 — APPROVED** [review]

**Pull request merged**
