### PR TITLE
Add 3 new workouts for Go

### PR DESCRIPTION
**Pull request by Stefan-Stojanovic**
- [x] Interfaces
- [x] Methods, Pointers and Functions
- [x] The Fmt package intro

- [x] Update Changelog

### CODE REVIEW

**Comment by enki-hq** [comment]
### Workout

| Workout Name | Error Message |
|:-:|:-:|
| methods-pointers-functions | One of the mentioned insights couldn't be found in this pull request or the database. |
| intro-to-fmt-package | One of the mentioned insights couldn't be found in this pull request or the database. |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Workout

| Workout Name | Error Message |
|:-:|:-:|
| intro-to-fmt-package | One of the mentioned insights couldn't be found in this pull request or the database. |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| fmt-package-verbs | The `how tot` category doesn't exist. |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Insight previews:
- [ ] [enkidevs/curriculum/go/intro/interfaces/empty-interfaces.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/go/intro/interfaces/empty-interfaces.md?ref=7397ff75cb593ad976c9d89e2d163e8740e91cb7)
- [ ] [enkidevs/curriculum/go/intro/interfaces/how-interfaces-are-implemented.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/go/intro/interfaces/how-interfaces-are-implemented.md?ref=7397ff75cb593ad976c9d89e2d163e8740e91cb7)
- [ ] [enkidevs/curriculum/go/intro/interfaces/implementing-interfaces.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/go/intro/interfaces/implementing-interfaces.md?ref=7397ff75cb593ad976c9d89e2d163e8740e91cb7)
- [ ] [enkidevs/curriculum/go/intro/interfaces/what-are-interfaces.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/go/intro/interfaces/what-are-interfaces.md?ref=7397ff75cb593ad976c9d89e2d163e8740e91cb7)
- [ ] [enkidevs/curriculum/go/intro/intro-to-fmt-package/fmt-package-verbs.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/go/intro/intro-to-fmt-package/fmt-package-verbs.md?ref=7397ff75cb593ad976c9d89e2d163e8740e91cb7)
- [ ] [enkidevs/curriculum/go/intro/intro-to-fmt-package/fmt-print-vs-println.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/go/intro/intro-to-fmt-package/fmt-print-vs-println.md?ref=7397ff75cb593ad976c9d89e2d163e8740e91cb7)
- [ ] [enkidevs/curriculum/go/intro/intro-to-fmt-package/fmt-printf.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/go/intro/intro-to-fmt-package/fmt-printf.md?ref=7397ff75cb593ad976c9d89e2d163e8740e91cb7)
- [ ] [enkidevs/curriculum/go/intro/intro-to-fmt-package/fmt-sprintf.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/go/intro/intro-to-fmt-package/fmt-sprintf.md?ref=7397ff75cb593ad976c9d89e2d163e8740e91cb7)
- [ ] [enkidevs/curriculum/go/intro/intro-to-fmt-package/intro-to-fmt.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/go/intro/intro-to-fmt-package/intro-to-fmt.md?ref=7397ff75cb593ad976c9d89e2d163e8740e91cb7)
- [ ] [enkidevs/curriculum/go/intro/methods-pointers-functions/methods-ii.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/go/intro/methods-pointers-functions/methods-ii.md?ref=7397ff75cb593ad976c9d89e2d163e8740e91cb7)
- [ ] [enkidevs/curriculum/go/intro/methods-pointers-functions/methods-with-receivers-ii.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/go/intro/methods-pointers-functions/methods-with-receivers-ii.md?ref=7397ff75cb593ad976c9d89e2d163e8740e91cb7)
- [ ] [enkidevs/curriculum/go/intro/methods-pointers-functions/methods-with-receivers.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/go/intro/methods-pointers-functions/methods-with-receivers.md?ref=7397ff75cb593ad976c9d89e2d163e8740e91cb7)
- [ ] [enkidevs/curriculum/go/intro/methods-pointers-functions/methods.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/go/intro/methods-pointers-functions/methods.md?ref=7397ff75cb593ad976c9d89e2d163e8740e91cb7)
- [ ] [enkidevs/curriculum/go/intro/methods-pointers-functions/pointers-and-functions.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/go/intro/methods-pointers-functions/pointers-and-functions.md?ref=7397ff75cb593ad976c9d89e2d163e8740e91cb7)
- [ ] [enkidevs/curriculum/go/intro/methods-pointers-functions/value-or-pointer-receiver.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/go/intro/methods-pointers-functions/value-or-pointer-receiver.md?ref=7397ff75cb593ad976c9d89e2d163e8740e91cb7)

**Review by kapnobatai137 — APPROVED** [review]

**Pull request merged**
