### PR TITLE
Blockchain c1w1

### PR DESCRIPTION
**Pull request by mihaiberq**
References #526

### CODE REVIEW

**Comment by enki-hq** [comment]
bad indentation of a sequence entry at line 3, column 16:
      - '[Ethereum's Inventor, Vitalik Buterin, abo ... 
                   ^

**Comment by enki-hq** [comment]
404 error making request GET https://api.github.com/repos/enkidevs/curriculum/contents/blockchain/fundamentals/the-blockchain/blockchain-applications.md: "Not Found"

**Comment by enki-hq** [comment]
404 error making request GET https://api.github.com/repos/enkidevs/curriculum/contents/blockchain/fundamentals/the-blockchain/blockchain-applications.md: "Not Found"

**Comment by Loopiezlol** [comment]
@mihaiberq that's the old git limitation. rename + update => addition + deletion resulting in a bad query for the deleted file

**Comment by mihaiberq** [comment]
Oh cool, good to know. Only that I wanted to delete that file and just added a new one.

**Comment by enki-hq** [comment]
404 error making request GET https://api.github.com/repos/enkidevs/curriculum/contents/blockchain/fundamentals/the-blockchain/blockchain-applications.md: "Not Found"

**Comment by mihaiberq** [comment]
Renamed it this time, still not working

**Comment by Loopiezlol** [comment]
so what's happening is that when trying to check the rules it'll query the contents of `blockchain/fundamentals/the-blockchain/blockchain-applications.md` . that file doesn't exist anymore (is shown as deleted) so it throws an error.

I think you can in the original rename it then in this PR update it

**Comment by enki-hq** [comment]
404 error making request GET https://api.github.com/repos/enkidevs/curriculum/contents/blockchain/fundamentals/the-blockchain/blockchain-applications.md: "Not Found"

**Comment by enki-hq** [comment]
404 error making request GET https://api.github.com/repos/enkidevs/curriculum/contents/blockchain/fundamentals/the-blockchain/blockchain-applications.md: "Not Found"

**Comment by enki-hq** [comment]
Must have exactly 1 yaml configuration but found 0 instead.

**Pull request merged**
