### PR TITLE
Update citation elements

### PR DESCRIPTION
**Pull request by Stefan-Stojanovic**

### CODE REVIEW

**Comment by enki-hq** [comment]
### Insight previews:
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/Web/HTML/citation-elements/address.md?ref=6e825356df2c0d2745458e550a084594954310a7

**Comment by enki-hq** [comment]
Rule insight:code-width failed for files: 
  - Web/HTML/citation-elements/blockquotes.md

**Comment by enki-hq** [comment]
Rule insight:quiz failed for files: 
  - Web/HTML/citation-elements/figure-and-figcaption.md

**Comment by lizTheDeveloper** [comment]
This has been migrated to #766

**Pull request closed without merging**
