### PR TITLE
Python intro to modules discussion insight

### PR DESCRIPTION
**Pull request by Stefan-Stojanovic**

### CODE REVIEW

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Insight previews:
- [ ] [enkidevs/curriculum/python/python-core/intro-to-modules/intro-to-modules-discussion.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/python/python-core/intro-to-modules/intro-to-modules-discussion.md?ref=85a31c71ddc66c78a77bd8cc5bd8860de0ef4e34)

**Review by nem035 — DISMISSED** [review]
Looks great

**Review by kapnobatai137 — DISMISSED** [review]

**Review by kapnobatai137 — APPROVED** [review]

**Pull request merged**
