### PR TITLE
Update think-like-a-coder.md

### PR DESCRIPTION
**Pull request by Stefan-Stojanovic**
@abdullahtahir147 let me know if everything looks good

### CODE REVIEW

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Insight previews:
- [ ] [enkidevs/curriculum/coding-intro/coding-intro-core/core-concepts/think-like-a-coder.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/coding-intro/coding-intro-core/core-concepts/think-like-a-coder.md?ref=5e8ebad8d090818238252164ddc9c51e57b1b102)

**Review by abdullahtahir147 — APPROVED** [review]
Looks good!

**Pull request merged**
