### PR TITLE
[JS] Error Handling Exercises

### PR DESCRIPTION
**Pull request by milesflo**
This platform does not support the use of `debugger`, so objective 4 of this standard could not be properly covered.

### CODE REVIEW

**Comment by enki-hq** [comment]
Rule insight:type failed for files: 
  - javascript/core/errors/exception-practice.md

**Comment by enki-hq** [comment]
Rule insight:category failed for files: 
  - javascript/core/errors/js-practice-custom-errors.md
  - javascript/core/errors/js-practice-error-throwing.md
  - javascript/core/errors/js-practice-invalid-input.md

**Comment by enki-hq** [comment]
Rule insight:type failed for files: 
  - javascript/core/errors/js-practice-custom-errors.md
  - javascript/core/errors/js-practice-error-throwing.md
  - javascript/core/errors/js-practice-invalid-input.md

**Comment by milesflo** [comment]
Branch did not follow naming convention

**Pull request closed without merging**
