### PR TITLE
Add Go Topic

### PR DESCRIPTION
**Pull request by Stefan-Stojanovic**

### CODE REVIEW

**Comment by enki-hq** [comment]
Failed parsing files: 
  - go/intro/for-loops-and-switch-statements/switch-ii.md: 
 > 	Cannot compile section node with name Footnote
  - go/intro/if-statements/if-else-is-stackable.md: 
 > 	Cannot compile section node with name Footnote

**Comment by enki-hq** [comment]
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| dependencies | Insight slug `dependencies` is not unique in the database. |
| data-types | Insight slug `data-types` is not unique in the database. |
| for-loops | Insight slug `for-loops` is not unique in the database. |
| packages | Insight slug `packages` is not unique in the database. |
| switch | Insight slug `switch` is not unique in the database. |
| if-statements | Insight slug `if-statements` is not unique in the database. |
| functions | Insight slug `functions` is not unique in the database. |
### Workout

| Workout Name | Error Message |
|:-:|:-:|
| Introduction | Workout slug `Introduction` contains forbidden characters. |
### Course

| Course Name | Error Message |
|:-:|:-:|
| intro | We couldn't find these workouts: `introduction`, `operators`. |
### Topic

| Topic Name | Error Message |
|:-:|:-:|
| go | Topic color `#69d6e1` does not conform to our HSV rules. Replace it with `#a6f7ff`. |
### Title

| File Name | Error Message |
|:-:|:-:|
| switch-ii | Insight title should be `` More on `Switch` Statements `` |
| if-else-is-stackable | Insight title should be `` `If..Else` Statements Are Stackable `` |
| if-else | Insight title should be `` `If..Else` `` |
| if-in-a-function | Insight title should be `` `If` in `Main()` Vs Separate Function `` |
| if-statements | Insight title should be `` `If` Statements `` |
| if-using-shorthand-notation | Insight title should be `` `If` Using Shorthand Notation `` |
| general/open-source.md | Glossary title should be `` Open-Source `` |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Workout

| Workout Name | Error Message |
|:-:|:-:|
| Introduction | Workout slug `Introduction` contains forbidden characters. |
| Introduction | One of the mentioned insights couldn't be found in this pull request or the database. |
### Course

| Course Name | Error Message |
|:-:|:-:|
| intro | We couldn't find these workouts: `introduction`. |
### Title

| File Name | Error Message |
|:-:|:-:|
| switch-ii | Insight title should be `` More on `Switch` Statements `` |
| go-if-statements | Insight title should be `` `If` Statements `` |
| if-else-is-stackable | Insight title should be `` `If..Else` Statements Are Stackable `` |
| if-else | Insight title should be `` `If..Else` `` |
| if-in-a-function | Insight title should be `` `If` in `Main()` Vs Separate Function `` |
| if-using-shorthand-notation | Insight title should be `` `If` Using Shorthand Notation `` |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Workout

| Workout Name | Error Message |
|:-:|:-:|
| Introduction | Workout slug `Introduction` contains forbidden characters. |
| Introduction | One of the mentioned insights couldn't be found in this pull request or the database. |
### Course

| Course Name | Error Message |
|:-:|:-:|
| intro | We couldn't find these workouts: `introduction`. |
### Title

| File Name | Error Message |
|:-:|:-:|
| switch-ii | Insight title should be `` More on `Switch` Statements `` |
| go-if-statements | Insight title should be `` `If` Statements `` |
| if-else-is-stackable | Insight title should be `` `If..Else` Statements Are Stackable `` |
| if-else | Insight title should be `` `If..Else` `` |
| if-in-a-function | Insight title should be `` `If` in `Main()` Vs Separate Function `` |
| if-using-shorthand-notation | Insight title should be `` `If` Using Shorthand Notation `` |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Course

| Course Name | Error Message |
|:-:|:-:|
| intro | We couldn't find these workouts: `introduction`. |
### Title

| File Name | Error Message |
|:-:|:-:|
| switch-ii | Insight title should be `` More on `Switch` Statements `` |
| go-if-statements | Insight title should be `` `If` Statements `` |
| if-else-is-stackable | Insight title should be `` `If..Else` Statements Are Stackable `` |
| if-else | Insight title should be `` `If..Else` `` |
| if-in-a-function | Insight title should be `` `If` in `Main()` Vs Separate Function `` |
| if-using-shorthand-notation | Insight title should be `` `If` Using Shorthand Notation `` |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Course

| Course Name | Error Message |
|:-:|:-:|
| intro | We couldn't find these workouts: `introduction`. |
### Title

| File Name | Error Message |
|:-:|:-:|
| switch-ii | Insight title should be `` More on `Switch` Statements `` |
| go-if-statements | Insight title should be `` `If` Statements `` |
| if-else-is-stackable | Insight title should be `` `If..Else` Statements Are Stackable `` |
| if-else | Insight title should be `` `If..Else` `` |
| if-in-a-function | Insight title should be `` `If` in `Main()` Vs Separate Function `` |
| if-using-shorthand-notation | Insight title should be `` `If` Using Shorthand Notation `` |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Course

| Course Name | Error Message |
|:-:|:-:|
| intro | We couldn't find these workouts: `introduction`. |
### Title

| File Name | Error Message |
|:-:|:-:|
| switch-ii | Insight title should be `` More on `Switch` Statements `` |
| go-if-statements | Insight title should be `` `If` Statements `` |
| if-else-is-stackable | Insight title should be `` `If..Else` Statements Are Stackable `` |
| if-else | Insight title should be `` `If..Else` `` |
| if-in-a-function | Insight title should be `` `If` in `Main()` Vs Separate Function `` |
| if-using-shorthand-notation | Insight title should be `` `If` Using Shorthand Notation `` |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Course

| Course Name | Error Message |
|:-:|:-:|
| intro | We couldn't find these workouts: `introduction`. |
### Title

| File Name | Error Message |
|:-:|:-:|
| switch-ii | Insight title should be `` More on `Switch` Statements `` |
| go-if-statements | Insight title should be `` `If` Statements `` |
| if-else-is-stackable | Insight title should be `` `If..Else` Statements Are Stackable `` |
| if-else | Insight title should be `` `If..Else` `` |
| if-in-a-function | Insight title should be `` `If` in `Main()` Vs Separate Function `` |
| if-using-shorthand-notation | Insight title should be `` `If` Using Shorthand Notation `` |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Title

| File Name | Error Message |
|:-:|:-:|
| switch-ii | Insight title should be `` More on `Switch` Statements `` |
| go-if-statements | Insight title should be `` `If` Statements `` |
| if-else-is-stackable | Insight title should be `` `If..Else` Statements Are Stackable `` |
| if-else | Insight title should be `` `If..Else` `` |
| if-in-a-function | Insight title should be `` `If` in `Main()` Vs Separate Function `` |
| if-using-shorthand-notation | Insight title should be `` `If` Using Shorthand Notation `` |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Title

| File Name | Error Message |
|:-:|:-:|
| switch-ii | Insight title should be `` More on `Switch` Statements `` |
| go-if-statements | Insight title should be `` `If` Statements `` |
| if-else-is-stackable | Insight title should be `` `If..Else` Statements Are Stackable `` |
| if-else | Insight title should be `` `If..Else` `` |
| if-in-a-function | Insight title should be `` `If` in `Main()` Vs Separate Function `` |
| if-using-shorthand-notation | Insight title should be `` `If` Using Shorthand Notation `` |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Title

| File Name | Error Message |
|:-:|:-:|
| switch-ii | Insight title should be `` More on `Switch` Statements `` |
| go-if-statements | Insight title should be `` `If` Statements `` |
| if-else-is-stackable | Insight title should be `` `If..Else` Statements Are Stackable `` |
| if-else | Insight title should be `` `If..Else` `` |
| if-in-a-function | Insight title should be `` `If` in `Main()` Vs Separate Function `` |
| if-using-shorthand-notation | Insight title should be `` `If` Using Shorthand Notation `` |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
Failed parsing files: 
  - go/intro/for-loops-and-switch-statements/switch-ii.md: 
 > 	Cannot compile section node with name Footnote

**Comment by enki-hq** [comment]
### Title

| File Name | Error Message |
|:-:|:-:|
| switch-ii | Insight title should be `` More on `Switch` Statements `` |
| go-if-statements | Insight title should be `` `If` Statements `` |
| if-else-is-stackable | Insight title should be `` `If..Else` Statements Are Stackable `` |
| if-else | Insight title should be `` `If..Else` `` |
| if-in-a-function | Insight title should be `` `If` in `Main()` Vs Separate Function `` |
| if-using-shorthand-notation | Insight title should be `` `If` Using Shorthand Declaration `` |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Title

| File Name | Error Message |
|:-:|:-:|
| switch-ii | Insight title should be `` More on `Switch` Statements `` |
| go-if-statements | Insight title should be `` `If` Statements `` |
| if-else-is-stackable | Insight title should be `` `If..Else` Statements Are Stackable `` |
| if-else | Insight title should be `` `If..Else` `` |
| if-in-a-function | Insight title should be `` `If` in `Main()` Vs Separate Function `` |
| if-using-shorthand-notation | Insight title should be `` `If` Using Shorthand Declaration `` |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Title

| File Name | Error Message |
|:-:|:-:|
| switch-ii | Insight title should be `` More on `Switch` Statements `` |
| go-if-statements | Insight title should be `` `If` Statements `` |
| if-else-is-stackable | Insight title should be `` `If..Else` Statements Are Stackable `` |
| if-else | Insight title should be `` `If..Else` `` |
| if-in-a-function | Insight title should be `` `If` in `Main()` Vs Separate Function `` |
| if-using-shorthand-notation | Insight title should be `` `If` Using Shorthand Declaration `` |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Title

| File Name | Error Message |
|:-:|:-:|
| switch-ii | Insight title should be `` More on `Switch` Statements `` |
| go-if-statements | Insight title should be `` `If` Statements `` |
| if-else-is-stackable | Insight title should be `` `If..Else` Statements Are Stackable `` |
| if-else | Insight title should be `` `If..Else` `` |
| if-in-a-function | Insight title should be `` `If` in `Main()` Vs Separate Function `` |
| if-using-shorthand-notation | Insight title should be `` `If` Using Shorthand Declaration `` |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Course

| Course Name | Error Message |
|:-:|:-:|
| intro | We couldn't find these workouts: `for-loops-and-switch-statements`. |
### Title

| File Name | Error Message |
|:-:|:-:|
| switch-ii | Insight title should be `` More on `Switch` Statements `` |
| go-if-statements | Insight title should be `` `If` Statements `` |
| if-else-is-stackable | Insight title should be `` `If..Else` Statements Are Stackable `` |
| if-else | Insight title should be `` `If..Else` `` |
| if-in-a-function | Insight title should be `` `If` in `Main()` Vs Separate Function `` |
| if-using-shorthand-notation | Insight title should be `` `If` Using Shorthand Declaration `` |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Title

| File Name | Error Message |
|:-:|:-:|
| switch-ii | Insight title should be `` More on `Switch` Statements `` |
| go-if-statements | Insight title should be `` `If` Statements `` |
| if-else-is-stackable | Insight title should be `` `If..Else` Statements Are Stackable `` |
| if-else | Insight title should be `` `If..Else` `` |
| if-in-a-function | Insight title should be `` `If` in `Main()` Vs Separate Function `` |
| if-using-shorthand-notation | Insight title should be `` `If` Using Shorthand Declaration `` |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Title

| File Name | Error Message |
|:-:|:-:|
| switch-ii | Insight title should be `` More on `Switch` Statements `` |
| go-if-statements | Insight title should be `` `If` Statements `` |
| if-else-is-stackable | Insight title should be `` `If..Else` Statements Are Stackable `` |
| if-else | Insight title should be `` `If..Else` `` |
| if-in-a-function | Insight title should be `` `If` in `Main()` Vs Separate Function `` |
| if-using-shorthand-notation | Insight title should be `` `If` Using Shorthand Declaration `` |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Title

| File Name | Error Message |
|:-:|:-:|
| switch-ii | Insight title should be `` More on `Switch` Statements `` |
| go-if-statements | Insight title should be `` `If` Statements `` |
| if-else-is-stackable | Insight title should be `` `If..Else` Statements Are Stackable `` |
| if-else | Insight title should be `` `If..Else` `` |
| if-in-a-function | Insight title should be `` `If` in `Main()` Vs Separate Function `` |
| if-using-shorthand-notation | Insight title should be `` `If` Using Shorthand Declaration `` |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Title

| File Name | Error Message |
|:-:|:-:|
| switch-ii | Insight title should be `` More on `Switch` Statements `` |
| go-if-statements | Insight title should be `` `If` Statements `` |
| if-else-is-stackable | Insight title should be `` `If..Else` Statements Are Stackable `` |
| if-else | Insight title should be `` `If..Else` `` |
| if-in-a-function | Insight title should be `` `If` in `Main()` Vs Separate Function `` |
| if-using-shorthand-notation | Insight title should be `` `If` Using Shorthand Declaration `` |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Title

| File Name | Error Message |
|:-:|:-:|
| switch-ii | Insight title should be `` More on `Switch` Statements `` |
| go-if-statements | Insight title should be `` `If` Statements `` |
| if-else-is-stackable | Insight title should be `` `If..Else` Statements Are Stackable `` |
| if-else | Insight title should be `` `If..Else` `` |
| if-in-a-function | Insight title should be `` `If` in `Main()` Vs Separate Function `` |
| if-using-shorthand-notation | Insight title should be `` `If` Using Shorthand Declaration `` |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Review by kapnobatai137 — APPROVED** [review]

**Pull request merged**
