### PR TITLE
Golang {WIP}

### PR DESCRIPTION
**Pull request by Stefan-Stojanovic**

### CODE REVIEW

**Comment by enki-hq** [comment]
Rule topic:slug failed for files: 
  - go/README.md

**Comment by enki-hq** [comment]
Rule topic:data failed for files: 
  - go/README.md

**Comment by enki-hq** [comment]
Rule insight:slug failed for files: 
  - go/intro/Introduction/packages.md
  - go/intro/Introduction/dependencies.md

**Comment by enki-hq** [comment]
Rule insight:questions failed for files: 
  - go/intro/Introduction/dependencies.md
  - go/intro/Introduction/packages.md

**Comment by enki-hq** [comment]
Rule workout:slug failed for files: 
  - go/intro/Introduction/README.md

**Comment by enki-hq** [comment]
Rule course:name-description failed for files: 
  - go/intro/README.md

**Comment by enki-hq** [comment]
Rule course:sections failed for files: 
  - go/intro/README.md

**Comment by enki-hq** [comment]
Rule topic:slug failed for files: 
  - go/README.md

**Comment by enki-hq** [comment]
Rule topic:data failed for files: 
  - go/README.md

**Comment by enki-hq** [comment]
Rule insight:slug failed for files: 
  - go/intro/Introduction/packages.md
  - go/intro/Introduction/dependencies.md

**Comment by enki-hq** [comment]
Rule insight:questions failed for files: 
  - go/intro/Introduction/dependencies.md
  - go/intro/Introduction/packages.md

**Comment by enki-hq** [comment]
Rule workout:slug failed for files: 
  - go/intro/Introduction/README.md

**Comment by enki-hq** [comment]
Rule course:name-description failed for files: 
  - go/intro/README.md

**Comment by enki-hq** [comment]
Rule course:sections failed for files: 
  - go/intro/README.md

**Comment by enki-hq** [comment]
Rule topic:slug failed for files: 
  - go/README.md

**Comment by enki-hq** [comment]
Rule insight:slug failed for files: 
  - go/intro/Introduction/packages.md
  - go/intro/Introduction/dependencies.md

**Comment by enki-hq** [comment]
Rule insight:questions failed for files: 
  - go/intro/Introduction/dependencies.md
  - go/intro/Introduction/packages.md

**Comment by enki-hq** [comment]
Rule workout:slug failed for files: 
  - go/intro/Introduction/README.md

**Comment by enki-hq** [comment]
Rule course:sections failed for files: 
  - go/intro/README.md

**Comment by enki-hq** [comment]
Rule topic:slug failed for files: 
  - go/README.md

**Comment by enki-hq** [comment]
Rule insight:slug failed for files: 
  - go/intro/Introduction/dependencies.md

**Comment by enki-hq** [comment]
Rule insight:questions failed for files: 
  - go/intro/Introduction/dependencies.md
  - go/intro/Introduction/packages-in-go.md

**Comment by enki-hq** [comment]
Rule workout:slug failed for files: 
  - go/intro/Introduction/README.md

**Comment by enki-hq** [comment]
Rule course:sections failed for files: 
  - go/intro/README.md

**Comment by enki-hq** [comment]
Rule topic:slug failed for files: 
  - go/README.md

**Comment by enki-hq** [comment]
Rule insight:slug failed for files: 
  - go/intro/Introduction/dependencies.md

**Comment by enki-hq** [comment]
Rule insight:questions failed for files: 
  - go/intro/Introduction/dependencies.md
  - go/intro/Introduction/packages-in-go.md

**Comment by enki-hq** [comment]
Rule workout:slug failed for files: 
  - go/intro/Introduction/README.md

**Comment by enki-hq** [comment]
Rule workout:insights failed for files: 
  - go/intro/Introduction/README.md

**Comment by enki-hq** [comment]
Rule course:sections failed for files: 
  - go/intro/README.md

**Comment by enki-hq** [comment]
Rule topic:slug failed for files: 
  - go/README.md

**Comment by enki-hq** [comment]
Rule insight:questions failed for files: 
  - go/intro/Introduction/packages-in-go.md

**Comment by enki-hq** [comment]
Rule workout:slug failed for files: 
  - go/intro/Introduction/README.md

**Comment by enki-hq** [comment]
Rule course:sections failed for files: 
  - go/intro/README.md

**Comment by enki-hq** [comment]
Rule topic:slug failed for files: 
  - go/README.md

**Comment by enki-hq** [comment]
Rule insight:questions failed for files: 
  - go/intro/Introduction/packages-in-go.md

**Comment by enki-hq** [comment]
Rule workout:slug failed for files: 
  - go/intro/Introduction/README.md

**Comment by enki-hq** [comment]
Rule workout:insights failed for files: 
  - go/intro/Introduction/README.md

**Comment by enki-hq** [comment]
Rule insight:questions failed for files: 
  - go/intro/Introduction/packages-in-go.md

**Comment by enki-hq** [comment]
Rule course:sections failed for files: 
  - go/intro/README.md

**Comment by enki-hq** [comment]
Rule topic:slug failed for files: 
  - go/README.md

**Comment by enki-hq** [comment]
Rule workout:slug failed for files: 
  - go/intro/Introduction/README.md

**Comment by enki-hq** [comment]
Rule course:sections failed for files: 
  - go/intro/README.md

**Comment by enki-hq** [comment]
Rule topic:slug failed for files: 
  - go/README.md

**Comment by enki-hq** [comment]
Rule insight:questions failed for files: 
  - go/intro/Introduction/packages-in-go.md

**Comment by enki-hq** [comment]
Rule workout:slug failed for files: 
  - go/intro/Introduction/README.md

**Comment by enki-hq** [comment]
Rule course:sections failed for files: 
  - go/intro/README.md

**Comment by enki-hq** [comment]
Rule topic:slug failed for files: 
  - go/README.md

**Comment by enki-hq** [comment]
Rule workout:slug failed for files: 
  - go/intro/Introduction/README.md

**Comment by enki-hq** [comment]
Rule course:sections failed for files: 
  - go/intro/README.md

**Comment by enki-hq** [comment]
Rule topic:slug failed for files: 
  - go/README.md

**Comment by enki-hq** [comment]
Rule workout:slug failed for files: 
  - go/intro/Introduction/README.md

**Comment by enki-hq** [comment]
Rule course:sections failed for files: 
  - go/intro/README.md

**Comment by enki-hq** [comment]
Rule topic:slug failed for files: 
  - go/README.md

**Comment by enki-hq** [comment]
Rule workout:slug failed for files: 
  - go/intro/Introduction/README.md

**Comment by enki-hq** [comment]
Rule course:sections failed for files: 
  - go/intro/README.md

**Comment by enki-hq** [comment]
Rule topic:slug failed for files: 
  - go/README.md

**Comment by enki-hq** [comment]
Rule workout:slug failed for files: 
  - go/intro/Introduction/README.md

**Comment by enki-hq** [comment]
Rule course:sections failed for files: 
  - go/intro/README.md

**Comment by enki-hq** [comment]
Rule topic:slug failed for files: 
  - go/README.md

**Comment by enki-hq** [comment]
Rule insight:slug failed for files: 
  - go/intro/variables-and-constants/data-types.md
  - go/intro/functions/functions.md

**Comment by enki-hq** [comment]
Rule workout:slug failed for files: 
  - go/intro/Introduction/README.md

**Comment by enki-hq** [comment]
Rule workout:insights failed for files: 
  - go/intro/functions/README.md

**Comment by enki-hq** [comment]
Rule course:sections failed for files: 
  - go/intro/README.md

**Comment by enki-hq** [comment]
Rule topic:slug failed for files: 
  - go/README.md

**Comment by enki-hq** [comment]
Rule insight:slug failed for files: 
  - go/intro/functions/functions.md
  - go/intro/variables-and-constants/data-types.md

**Comment by enki-hq** [comment]
Rule workout:slug failed for files: 
  - go/intro/Introduction/README.md

**Comment by enki-hq** [comment]
Rule workout:insights failed for files: 
  - go/intro/functions/README.md

**Comment by enki-hq** [comment]
Rule course:sections failed for files: 
  - go/intro/README.md

**Comment by enki-hq** [comment]
Rule topic:slug failed for files: 
  - go/README.md

**Comment by enki-hq** [comment]
Rule insight:slug failed for files: 
  - go/intro/functions/functions.md
  - go/intro/variables-and-constants/data-types.md

**Comment by enki-hq** [comment]
Rule workout:slug failed for files: 
  - go/intro/Introduction/README.md

**Comment by enki-hq** [comment]
Rule workout:insights failed for files: 
  - go/intro/functions/README.md

**Comment by enki-hq** [comment]
Rule course:sections failed for files: 
  - go/intro/README.md

**Comment by enki-hq** [comment]
Rule topic:slug failed for files: 
  - go/README.md

**Comment by enki-hq** [comment]
Rule insight:slug failed for files: 
  - go/intro/functions/functions.md
  - go/intro/variables-and-constants/data-types.md

**Comment by enki-hq** [comment]
Rule workout:slug failed for files: 
  - go/intro/Introduction/README.md

**Comment by enki-hq** [comment]
Rule course:sections failed for files: 
  - go/intro/README.md

**Comment by enki-hq** [comment]
Rule topic:slug failed for files: 
  - go/README.md

**Comment by enki-hq** [comment]
Failed parsing files: 
  - go/intro/Introduction/what-is-go.md: 
 > 	bad indentation of a sequence entry at line 12, column 3:
      - '[Official Website](https://go ... 
      ^
  - go/intro/Introduction/why-is-go-useful.md: 
 > 	bad indentation of a sequence entry at line 16, column 3:
      - '[The Go proverbs](https://go- ... 
      ^

**Comment by Stefan-Stojanovic** [comment]
Outdated and closed

**Pull request closed without merging**
