### PR TITLE
Add Application Security Course

### PR DESCRIPTION
**Pull request by lizTheDeveloper**
This is the application security course. It's based on the OWASP top ten.

- [x] Outline:

- [x] Standards
- [x] Intro
- [x] xss
- [x] xxe
- [x] sql injection
- [ ] authentication
- [x] access control
- [x] deserialization
- [ ] sensitive data
- [x] security configuration
- [x] dependency analysis
- [ ] metasploit
- [ ] wireshark
- [ ] security-regression-testing

### CODE REVIEW

**Comment by enki-hq** [comment]
Failed parsing files: 
  - .archived/security/application-security/README.md: 
 > duplicated mapping key at line 78, column 7:
          4: Establish a review cadence th ... 
          ^
  - security/application-security/README.md: 
 > duplicated mapping key at line 82, column 7:
          4: Establish a review cadence th ... 
          ^

**Comment by enki-hq** [comment]
Failed parsing files: 
  - .archived/security/application-security/README.md: 
 > Passed in empty readme text

**Comment by enki-hq** [comment]
Rule insight:standards failed for files: 
  - security/application-security/intro/automated-tools.md
  - security/application-security/intro/what-else-do-you-need-to-know.md
  - security/application-security/intro/what-is-appsec.md

**Comment by enki-hq** [comment]
Rule course:slug failed for files: 
  - security/application-security/README.md

**Comment by enki-hq** [comment]
Rule insight:standards failed for files: 
  - security/appsec/intro/what-else-do-you-need-to-know.md
  - security/appsec/intro/what-is-appsec.md

**Comment by enki-hq** [comment]
Rule insight:standards failed for files: 
  - security/appsec/intro/what-is-appsec.md

**Comment by enki-hq** [comment]
### Insight previews:
- [ ] https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/security/appsec/intro/automated-tools.md?ref=ac531a5681790599edde798ca56dae4644fdbead
- [ ] https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/security/appsec/intro/owasp-top-ten.md?ref=ac531a5681790599edde798ca56dae4644fdbead
- [ ] https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/security/appsec/intro/owasp.md?ref=ac531a5681790599edde798ca56dae4644fdbead
- [ ] https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/security/appsec/intro/what-else-do-you-need-to-know.md?ref=ac531a5681790599edde798ca56dae4644fdbead
- [ ] https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/security/appsec/intro/what-is-appsec.md?ref=ac531a5681790599edde798ca56dae4644fdbead

**Comment by enki-hq** [comment]
Rule insight:questions failed for files: 
  - security/appsec/xss/mitigate-xss.md

**Comment by enki-hq** [comment]
Rule workout:insights failed for files: 
  - security/appsec/xss/README.md

**Comment by enki-hq** [comment]
Rule workout:exercises failed for files: 
  - security/appsec/xss/README.md

**Comment by enki-hq** [comment]
Rule insight:code-width failed for files: 
  - security/appsec/xxe/xxe-introduction.md
  - security/appsec/xxe/xxe-prevention.md

**Comment by enki-hq** [comment]
Rule insight:questions failed for files: 
  - security/appsec/xss/mitigate-xss.md
  - security/appsec/xxe/xxe-security.md

**Comment by enki-hq** [comment]
Rule insight:standards failed for files: 
  - security/appsec/xxe/detect-xxe.md

**Comment by enki-hq** [comment]
Rule insight:code-width failed for files: 
  - security/appsec/xxe/xxe-introduction.md
  - security/appsec/xxe/xxe-prevention.md

**Comment by enki-hq** [comment]
Rule insight:questions failed for files: 
  - security/appsec/xxe/xxe-security.md

**Comment by enki-hq** [comment]
Rule insight:code-width failed for files: 
  - security/appsec/xxe/xxe-introduction.md
  - security/appsec/xxe/xxe-prevention.md

**Comment by enki-hq** [comment]
Rule insight:code-width failed for files: 
  - security/appsec/xxe/xxe-introduction.md
  - security/appsec/xxe/xxe-prevention.md

**Comment by enki-hq** [comment]
Rule insight:code-width failed for files: 
  - security/appsec/sql-injection/identify-sql-injection.md
  - security/appsec/sql-injection/other-forms-of-injection-attacks.md
  - security/appsec/sql-injection/sql-injection.md
  - security/appsec/xxe/xxe-introduction.md
  - security/appsec/xxe/xxe-prevention.md

**Comment by enki-hq** [comment]
Rule workout:insights failed for files: 
  - security/appsec/sql-injection/README.md

**Comment by enki-hq** [comment]
Rule workout:insights failed for files: 
  - security/appsec/sql-injection/README.md

**Comment by enki-hq** [comment]
Rule insight:code-width failed for files: 
  - security/appsec/deserialization/identify-deserialization.md

**Comment by enki-hq** [comment]
Rule workout:insights failed for files: 
  - security/appsec/deserialization/README.md
  - security/appsec/sql-injection/README.md

**Comment by enki-hq** [comment]
Rule workout:exercises failed for files: 
  - security/appsec/deserialization/README.md

**Comment by enki-hq** [comment]
Rule insight:code-width failed for files: 
  - security/appsec/deserialization/identify-deserialization.md

**Comment by enki-hq** [comment]
Rule workout:insights failed for files: 
  - security/appsec/sql-injection/README.md
  - security/appsec/deserialization/README.md

**Comment by enki-hq** [comment]
Rule workout:exercises failed for files: 
  - security/appsec/deserialization/README.md

**Comment by enki-hq** [comment]
Rule insight:code-width failed for files: 
  - security/appsec/deserialization/identify-deserialization.md

**Comment by enki-hq** [comment]
Rule workout:insights failed for files: 
  - security/appsec/deserialization/README.md

**Comment by enki-hq** [comment]
Rule workout:exercises failed for files: 
  - security/appsec/deserialization/README.md

**Comment by enki-hq** [comment]
Rule insight:code-width failed for files: 
  - security/appsec/deserialization/identify-deserialization.md

**Comment by enki-hq** [comment]
Rule insight:code-width failed for files: 
  - security/appsec/deserialization/identify-deserialization.md

**Comment by enki-hq** [comment]
Rule insight:code-width failed for files: 
  - security/appsec/deserialization/identify-deserialization.md

**Comment by enki-hq** [comment]
Rule insight:code-width failed for files: 
  - security/appsec/deserialization/identify-deserialization.md

**Comment by enki-hq** [comment]
Failed parsing files: 
  - security/appsec/dependency-analysis/establish-upgrade-process.md: 
 > Missing compiler for node of type `questionGap`: `[object Object]`

**Comment by enki-hq** [comment]
Failed parsing files: 
  - security/appsec/dependency-analysis/establish-upgrade-process.md: 
 > Missing compiler for node of type `questionGap`: `[object Object]`

**Comment by enki-hq** [comment]
Failed parsing files: 
  - security/appsec/dependency-analysis/establish-upgrade-process.md: 
 > Missing compiler for node of type `questionGap`: `[object Object]`

**Comment by enki-hq** [comment]
Failed parsing files: 
  - security/appsec/dependency-analysis/establish-upgrade-process.md: 
 > Missing compiler for node of type `questionGap`: `[object Object]`

**Comment by enki-hq** [comment]
Failed parsing files: 
  - security/appsec/dependency-analysis/establish-upgrade-process.md: 
 > Missing compiler for node of type `questionGap`: `[object Object]`

**Comment by enki-hq** [comment]
Failed parsing files: 
  - security/appsec/access-control/fix-broken-access-control.md: 
 > Missing compiler for node of type `questionGap`: `[object Object]`
  - security/appsec/access-control/identify-broken-access-control.md: 
 > Missing compiler for node of type `questionGap`: `[object Object]`
  - security/appsec/access-control/monitor-broken-access-control.md: 
 > Missing compiler for node of type `questionGap`: `[object Object]`
  - security/appsec/dependency-analysis/establish-upgrade-process.md: 
 > Missing compiler for node of type `questionGap`: `[object Object]`

**Comment by enki-hq** [comment]
Failed parsing files: 
  - security/appsec/access-control/fix-broken-access-control.md: 
 > Missing compiler for node of type `questionGap`: `[object Object]`
  - security/appsec/access-control/identify-broken-access-control.md: 
 > Missing compiler for node of type `questionGap`: `[object Object]`
  - security/appsec/access-control/monitor-broken-access-control.md: 
 > Missing compiler for node of type `questionGap`: `[object Object]`
  - security/appsec/dependency-analysis/establish-upgrade-process.md: 
 > Missing compiler for node of type `questionGap`: `[object Object]`

**Comment by enki-hq** [comment]
Failed parsing files: 
  - security/appsec/access-control/fix-broken-access-control.md: 
 > Missing compiler for node of type `questionGap`: `[object Object]`
  - security/appsec/access-control/identify-broken-access-control.md: 
 > Missing compiler for node of type `questionGap`: `[object Object]`
  - security/appsec/access-control/monitor-broken-access-control.md: 
 > Missing compiler for node of type `questionGap`: `[object Object]`
  - security/appsec/dependency-analysis/establish-upgrade-process.md: 
 > Missing compiler for node of type `questionGap`: `[object Object]`

**Comment by enki-hq** [comment]
Rule insight:code-width failed for files: 
  - security/appsec/deserialization/identify-deserialization.md

**Comment by enki-hq** [comment]
Rule insight:standards failed for files: 
  - security/appsec/dependency-analysis/upgrade-process-cadence.md

**Comment by enki-hq** [comment]
Rule course:standards failed for files: 
  - .archived/security/securing-unix-the-osi-model/README.md
  - security/appsec/README.md

**Comment by enki-hq** [comment]
Rule insight:code-width failed for files: 
  - security/appsec/deserialization/identify-deserialization.md

**Comment by enki-hq** [comment]
Rule insight:standards failed for files: 
  - security/appsec/dependency-analysis/upgrade-process-cadence.md

**Comment by enki-hq** [comment]
Rule insight:standards failed for files: 
  - security/appsec/dependency-analysis/upgrade-process-cadence.md

**Comment by lizTheDeveloper** [comment]
hey @alexmackey - thanks for your recommendations earlier, check out this OWASP course I put together. Recently I finally got some time to write curriculum myself- would love someone to sanity-check it. It's based on OWASP's top ten vulnerability categories but has a lot about process control and how to perform some of the analysis required to mitigate them. 

I have a few more workouts I want to add, but I've tried to strike a balance in the course between two extremes: "look at how many tickets you can create for devs to fix things, so many tickets" and "hey security is important but be realistic about how much time developers get to spend on it, be targeted and develop a strategy using process control".

**Comment by mihaiberq** [comment]
I'm half-way done reading through the content and, so far, all I can say is well done @lizTheDeveloper . Awesome bit-sized information, great resources and a much better structure of the course.

However, there are a couple of comments I have:
- Links are part of the insight now and users can see them during their workout, i.e. no need for `bookmark this insight to receive...`
- We do not support `pdf` as link type. here is a list of link types mapped to their available emojis:
```
website: 'earth',
blog: 'earth',
book: 'book',
tutorial: 'flask',
discussion: 'chat',
documentation: 'document',
'release notes': 'newspaper'
```
- While the new app accepts hyperlinks, the mix of in-line hyperlinks and learn more links is not consistent (no hyperlinks, only learn more > half and half > no learn more links, only hyperlinks)

**Comment by nem035** [comment]
Another issue is that there are code blocks without the language tag (mainly xml ones that I've seen).

**Comment by enki-hq** [comment]
Rule insight:questions failed for files: 
  - security/appsec/sql-injection/sql-injection.md

**Comment by enki-hq** [comment]
Rule insight:questions failed for files: 
  - security/appsec/sql-injection/sql-injection.md

**Comment by enki-hq** [comment]
Rule insight:questions failed for files: 
  - security/appsec/sql-injection/sql-injection.md

**Pull request merged**
