### PR TITLE
Update three-ways-to-substitute-a-substring-of-a-string.md

### PR DESCRIPTION
**Pull request by Stefan-Stojanovic**
Replace numbers with dashes because they all render as `1` in the app.

Screenshot_20200129-145209_Enki

### CODE REVIEW

**Comment by enki-hq** [comment]
### Insight previews:
- [ ] [enkidevs/curriculum/python/core/working-with-strings/three-ways-to-substitute-a-substring-of-a-string.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/python/core/working-with-strings/three-ways-to-substitute-a-substring-of-a-string.md?ref=10c9a18b031386c2e666cae444fb269f0d89fce8)

**Comment by kapnobatai137** [comment]
@sourabhv is this a bug from the app?

**Comment by nem035** [comment]
This is a rendering bug but we should merge this PR first since it might take a bit of time to fix the app bug.

**Comment by kapnobatai137** [comment]
should we check if other insights are affected?

**Pull request merged**
