### PR TITLE
Update total-number-of-actors.md

### PR DESCRIPTION
**Pull request by Stefan-Stojanovic**
Remove the double dot from the 2nd answer in the RQ

### CODE REVIEW

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Insight previews:
- [ ] [enkidevs/curriculum/python-data-analysis/python-data-analysis-core/analyzing-iii/total-number-of-actors.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python-data-analysis/python-data-analysis-core/analyzing-iii/total-number-of-actors.md?ref=b04d1d914f07b38463ffe33ed7aaf8ba51bfe60e)

**Review by kapnobatai137 — CHANGES_REQUESTED** [review]
@Stefan-Stojanovic let's remove the type-in-the-gap format from the practice question

**Review by kapnobatai137 — APPROVED** [review]
:rocket:

**Pull request merged**
