### PR TITLE
Update basic-git-configuration.md and database-server-types.md

### PR DESCRIPTION
**Pull request by Fonseverin**
Username on GitHub isn't equal to `user.name`.

### CODE REVIEW

**Comment by enki-hq** [comment]
### Insight previews:
- [ ] https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/git/essentials/getting-started/basic-git-configuration.md?ref=07b2018154f9ac7906f21d1c2e9ff426eea01764

**Comment by nem035** [comment]
Thanks again for the contribution @Fonseverin, this is definitely helpful.

I have one minor comment. The addition of `LAMP` is likely too specific for this particular piece of content, which is meant to be a general overview of database servers. `LAMP` is an acronym for a specific software stack (like MEAN or MERN) that includes many software components, not just a database, and is thus too specific for this particular lesson.

**Comment by nem035** [comment]
Hi @Fonseverin , can you possibly remove the `LAMP` foot note? As mentioned in the comment above, it's not really related to this particular piece of content. Other than that, the PR looks great 👍

**Comment by nem035** [comment]
Closing due to staleness. Feel free to reopen if you'd like to @Fonseverin

**Pull request closed without merging**
