### PR TITLE
add discussion question for git

### PR DESCRIPTION
**Pull request by Stefan-Stojanovic**

### CODE REVIEW

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Insight previews:
- [ ] [enkidevs/curriculum/git/essentials/getting-started/some-common-terminology.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/git/essentials/getting-started/some-common-terminology.md?ref=b7efb7b77d780949c7219ae008a5073febb5ca87)
- [ ] [enkidevs/curriculum/git/essentials/intro-git/what-you-will-get-out-of-git.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/git/essentials/intro-git/what-you-will-get-out-of-git.md?ref=b7efb7b77d780949c7219ae008a5073febb5ca87)

**Review by kapnobatai137 — APPROVED** [review]

**Pull request merged**
