### PR TITLE
Add JS questions to github

### PR DESCRIPTION
**Pull request by Stefan-Stojanovic**

### CODE REVIEW

**Comment by enki-hq** [comment]
### Course

| Course Name | Error Message |
|:-:|:-:|
| javascript-playground-questions | Course does not have sections. |
### Topic

| Topic Name | Error Message |
|:-:|:-:|
| javascript-playground-questions | Topic should have at least one workout with the "workout" aspect. |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Course

| Course Name | Error Message |
|:-:|:-:|
| javascript-playground-questions | Course does not have sections. |
### Topic

| Topic Name | Error Message |
|:-:|:-:|
| javascript-playground-questions | Topic should have at least one workout with the "workout" aspect. |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Course

| Course Name | Error Message |
|:-:|:-:|
| javascript-playground-questions | Course does not have sections. |
### Topic

| Topic Name | Error Message |
|:-:|:-:|
| javascript-playground-questions | Topic should have at least one workout with the "workout" aspect. |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by Stefan-Stojanovic** [comment]
Closing this one and uploading different copy

**Pull request closed without merging**
