### PR TITLE
Fix typo in tsc-array-tuple.md

### PR DESCRIPTION
**Pull request by chillinPanda**

### CODE REVIEW

**Comment by enki-hq** [comment]
### Insight previews:
- [ ] [enkidevs/curriculum/typescript/typescript-introduction/tsc-basic-types/tsc-array-tuple.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/typescript/typescript-introduction/tsc-basic-types/tsc-array-tuple.md?ref=388ab4a0c24469ebd028ae930184d0dac2fd9bf0)

**Review by nem035 — APPROVED** [review]
Thanks for the contribution @chillinPanda :raised_hands:

**Comment by Stefan-Stojanovic** [comment]
Thank you for the contribution, @chillinPanda. I've applied your changes 🚀

**Comment by chillinPanda** [comment]
Happy to contribute :) thank you for the fast merge

**Pull request merged**
