### PR TITLE
Securing the X stub insights

### PR DESCRIPTION
**Pull request by milesflo**

### CODE REVIEW

**Comment by lizTheDeveloper** [comment]
These are fantastic - remove `stub:true` from the ones that are your own writing :D 💯  🌈  ✨

**Comment by milesflo** [comment]
Will push a commit containing standards and point values once I get the O.K. on the standards PR https://github.com/sagelabs/standards/pull/31

**Comment by lizTheDeveloper** [comment]
Merged sagelabs/standards#31 so you are good to tag

**Comment by milesflo** [comment]
Points in.

**Pull request merged**
