### PR TITLE
Add new topic colors and icons

### PR DESCRIPTION
**Pull request by sourabhv**
⚠️ ⚠️ ⚠️  SHOULD MERGE AFTER DB MIGRATION ⚠️ ⚠️ ⚠️

### CODE REVIEW

**Comment by enki-hq** [comment]
### Topic

| Topic Name | Error Message |
|:-:|:-:|
| airtable | Topic color `#FFEEA6` does not conform to our HSV rules. Replace it with `#ffeea6`. |
| blockchain | Topic color `#FFA7ED` does not conform to our HSV rules. Replace it with `#ffa6ed`. |
| coding-intro | Topic color `#A6BAFF` does not conform to our HSV rules. Replace it with `#a6baff`. |
| comp-sci | Topic color `#DEA6FF` does not conform to our HSV rules. Replace it with `#dea6ff`. |
| data-analysis | Topic color `#FFA7A6` does not conform to our HSV rules. Replace it with `#ffa7a6`. |
| docker | Topic color `#A6DEFF` does not conform to our HSV rules. Replace it with `#a6deff`. |
| git | Topic color `#FFC3A6` does not conform to our HSV rules. Replace it with `#ffc3a6`. |
| java | Topic color `#FFA7A6` does not conform to our HSV rules. Replace it with `#ffa7a6`. |
| javascript | Topic color `#FFE4A6` does not conform to our HSV rules. Replace it with `#ffe4a6`. |
| linux | Topic color `#A7CBFF` does not conform to our HSV rules. Replace it with `#a6caff`. |
| mongodb | Topic color `#B2FFA7` does not conform to our HSV rules. Replace it with `#b1ffa6`. |
| nocode-webflow | Topic color `#A6ADFF` does not conform to our HSV rules. Replace it with `#a6adff`. |
| python | Topic color `#D2FFA6` does not conform to our HSV rules. Replace it with `#d2ffa6`. |
| react | Topic color `#A7EDFF` does not conform to our HSV rules. Replace it with `#a6edff`. |
| regular-expressions | Topic color `#A6D9FF` does not conform to our HSV rules. Replace it with `#a6d9ff`. |
| security | Topic color `#A7FBFF` does not conform to our HSV rules. Replace it with `#a6fbff`. |
| spreadsheets | Topic color `#A6FFD5` does not conform to our HSV rules. Replace it with `#a6ffd5`. |
| sql | Topic color `#A6EAFF` does not conform to our HSV rules. Replace it with `#a6eaff`. |
| typescript | Topic color `#A6DBFF` does not conform to our HSV rules. Replace it with `#a6dbff`. |
| web | Topic color `#C3A6FF` does not conform to our HSV rules. Replace it with `#c3a6ff`. |
| zapier | Topic color `#FFC0A6` does not conform to our HSV rules. Replace it with `#ffc0a6`. |
### Title

| File Name | Error Message |
|:-:|:-:|
| mongodb | Topic title should be `` Mongodb `` |
| sql | Topic title should be `` Sql `` |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Review by kapnobatai137 — DISMISSED** [review]

**Comment by sourabhv** [comment]
@kapnobatai137 do you know why there are false positives errors?

**Comment by enki-hq** [comment]
### Topic

| Topic Name | Error Message |
|:-:|:-:|
| airtable | Topic color `#FFEEA6` does not conform to our HSV rules. Replace it with `#ffeea6`. |
| blockchain | Topic color `#FFA6ED` does not conform to our HSV rules. Replace it with `#ffa6ed`. |
| coding-intro | Topic color `#A6BAFF` does not conform to our HSV rules. Replace it with `#a6baff`. |
| comp-sci | Topic color `#DEA6FF` does not conform to our HSV rules. Replace it with `#dea6ff`. |
| data-analysis | Topic color `#FFA7A6` does not conform to our HSV rules. Replace it with `#ffa7a6`. |
| docker | Topic color `#A6DEFF` does not conform to our HSV rules. Replace it with `#a6deff`. |
| git | Topic color `#FFC3A6` does not conform to our HSV rules. Replace it with `#ffc3a6`. |
| java | Topic color `#FFA7A6` does not conform to our HSV rules. Replace it with `#ffa7a6`. |
| javascript | Topic color `#FFE4A6` does not conform to our HSV rules. Replace it with `#ffe4a6`. |
| linux | Topic color `#A6CAFF` does not conform to our HSV rules. Replace it with `#a6caff`. |
| mongodb | Topic color `#B1FFA6` does not conform to our HSV rules. Replace it with `#b1ffa6`. |
| nocode-webflow | Topic color `#A6ADFF` does not conform to our HSV rules. Replace it with `#a6adff`. |
| python | Topic color `#D2FFA6` does not conform to our HSV rules. Replace it with `#d2ffa6`. |
| react | Topic color `#A6EDFF` does not conform to our HSV rules. Replace it with `#a6edff`. |
| regular-expressions | Topic color `#A6D9FF` does not conform to our HSV rules. Replace it with `#a6d9ff`. |
| security | Topic color `#A6FBFF` does not conform to our HSV rules. Replace it with `#a6fbff`. |
| spreadsheets | Topic color `#A6FFD5` does not conform to our HSV rules. Replace it with `#a6ffd5`. |
| sql | Topic color `#A6EAFF` does not conform to our HSV rules. Replace it with `#a6eaff`. |
| typescript | Topic color `#A6DBFF` does not conform to our HSV rules. Replace it with `#a6dbff`. |
| web | Topic color `#C3A6FF` does not conform to our HSV rules. Replace it with `#c3a6ff`. |
| zapier | Topic color `#FFC0A6` does not conform to our HSV rules. Replace it with `#ffc0a6`. |
### Title

| File Name | Error Message |
|:-:|:-:|
| mongodb | Topic title should be `` Mongodb `` |
| sql | Topic title should be `` Sql `` |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by kapnobatai137** [comment]
@sourabhv

for the title rule, I'm in the process of updating it so you can ignore those

for the colour rule, I have no idea. I'm going to take a look at the rule code in a bit and see where the issue is

**Comment by sourabhv** [comment]
Migrated. Should be safe to merge as long as we are sure this won't delete `deprecated*` fields

**Comment by enki-hq** [comment]
### Title

| File Name | Error Message |
|:-:|:-:|
| mongodb | Topic title should be `` Mongodb `` |
| sql | Topic title should be `` Sql `` |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Review by kapnobatai137 — APPROVED** [review]

**Comment by enki-hq** [comment]
### Title

| File Name | Error Message |
|:-:|:-:|
| mongodb | Topic title should be `` Mongodb `` |
| sql | Topic title should be `` Sql `` |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Title

| File Name | Error Message |
|:-:|:-:|
| mongodb | Topic title should be `` Mongodb `` |
| sql | Topic title should be `` Sql `` |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Pull request merged**
