### PR TITLE
Add 5 spreadsheet workouts

### PR DESCRIPTION
**Pull request by Stefan-Stojanovic**
- [x] Conditional Formatting
- [x] Math Functions
- [x] Importing Data 2
- [x] More Functions & Formulas
- [x] Parser Functions

After reviewed and approved:

- [ ] Tick this and update CHANNELLOG file

### CODE REVIEW

**Comment by enki-hq** [comment]
Failed parsing files: 
  - spreadsheets/intermediate/conditional-formatting/conditional-formatting-features-ii.md: 
 > 	No valid answer list in question node
  - spreadsheets/intermediate/conditional-formatting/conditional-formatting-features.md: 
 > 	No valid answer list in question node
  - spreadsheets/intermediate/more-functions-and-formulas/concat.md: 
 > 	No valid answer list in question node
  - spreadsheets/intermediate/more-functions-and-formulas/concatenate.md: 
 > 	No valid answer list in question node
  - spreadsheets/intermediate/more-functions-and-formulas/date-time-functions.md: 
 > 	No valid answer list in question node
  - spreadsheets/intermediate/more-functions-and-formulas/proper.md: 
 > 	No valid answer list in question node

**Comment by enki-hq** [comment]
Rule workout:aspects failed for files: 
  - spreadsheets/intermediate/conditional-formatting/README.md
  - spreadsheets/intermediate/importing-data-ii/README.md
  - spreadsheets/intermediate/math-functions/README.md
  - spreadsheets/intermediate/more-functions-and-formulas/README.md
  - spreadsheets/intermediate/parser-functions/README.md

**Comment by enki-hq** [comment]
Rule workout:insights failed for files: 
  - spreadsheets/intermediate/parser-functions/README.md

**Comment by enki-hq** [comment]
Rule workout:aspects failed for files: 
  - spreadsheets/intermediate/importing-data-ii/README.md
  - spreadsheets/intermediate/math-functions/README.md
  - spreadsheets/intermediate/more-functions-and-formulas/README.md
  - spreadsheets/intermediate/parser-functions/README.md

**Comment by enki-hq** [comment]
Rule workout:insights failed for files: 
  - spreadsheets/intermediate/parser-functions/README.md

**Comment by enki-hq** [comment]
Rule workout:aspects failed for files: 
  - spreadsheets/intermediate/math-functions/README.md
  - spreadsheets/intermediate/more-functions-and-formulas/README.md
  - spreadsheets/intermediate/parser-functions/README.md

**Comment by enki-hq** [comment]
Rule workout:insights failed for files: 
  - spreadsheets/intermediate/parser-functions/README.md

**Comment by enki-hq** [comment]
Rule workout:aspects failed for files: 
  - spreadsheets/intermediate/more-functions-and-formulas/README.md
  - spreadsheets/intermediate/parser-functions/README.md

**Comment by enki-hq** [comment]
Rule workout:insights failed for files: 
  - spreadsheets/intermediate/parser-functions/README.md

**Comment by enki-hq** [comment]
Rule workout:aspects failed for files: 
  - spreadsheets/intermediate/parser-functions/README.md

**Comment by enki-hq** [comment]
Rule workout:insights failed for files: 
  - spreadsheets/intermediate/parser-functions/README.md

**Comment by enki-hq** [comment]
### Insight previews:
- [ ] [enkidevs/curriculum/spreadsheets/intermediate/conditional-formatting/conditional-formatting-examples.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/spreadsheets/intermediate/conditional-formatting/conditional-formatting-examples.md?ref=77739399aef05a7cae48b4b6368d0f514cf60b44)
- [ ] [enkidevs/curriculum/spreadsheets/intermediate/conditional-formatting/conditional-formatting-features-ii.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/spreadsheets/intermediate/conditional-formatting/conditional-formatting-features-ii.md?ref=77739399aef05a7cae48b4b6368d0f514cf60b44)
- [ ] [enkidevs/curriculum/spreadsheets/intermediate/conditional-formatting/conditional-formatting-features.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/spreadsheets/intermediate/conditional-formatting/conditional-formatting-features.md?ref=77739399aef05a7cae48b4b6368d0f514cf60b44)
- [ ] [enkidevs/curriculum/spreadsheets/intermediate/conditional-formatting/what-can-conditional-formatting-do.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/spreadsheets/intermediate/conditional-formatting/what-can-conditional-formatting-do.md?ref=77739399aef05a7cae48b4b6368d0f514cf60b44)
- [ ] [enkidevs/curriculum/spreadsheets/intermediate/conditional-formatting/what-is-conditional-formatting.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/spreadsheets/intermediate/conditional-formatting/what-is-conditional-formatting.md?ref=77739399aef05a7cae48b4b6368d0f514cf60b44)
- [ ] [enkidevs/curriculum/spreadsheets/intermediate/importing-data-ii/importfeed.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/spreadsheets/intermediate/importing-data-ii/importfeed.md?ref=77739399aef05a7cae48b4b6368d0f514cf60b44)
- [ ] [enkidevs/curriculum/spreadsheets/intermediate/importing-data-ii/importhtml.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/spreadsheets/intermediate/importing-data-ii/importhtml.md?ref=77739399aef05a7cae48b4b6368d0f514cf60b44)
- [ ] [enkidevs/curriculum/spreadsheets/intermediate/importing-data-ii/importrange.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/spreadsheets/intermediate/importing-data-ii/importrange.md?ref=77739399aef05a7cae48b4b6368d0f514cf60b44)
- [ ] [enkidevs/curriculum/spreadsheets/intermediate/importing-data-ii/importxml.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/spreadsheets/intermediate/importing-data-ii/importxml.md?ref=77739399aef05a7cae48b4b6368d0f514cf60b44)
- [ ] [enkidevs/curriculum/spreadsheets/intermediate/math-functions/ceiling-function.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/spreadsheets/intermediate/math-functions/ceiling-function.md?ref=77739399aef05a7cae48b4b6368d0f514cf60b44)
- [ ] [enkidevs/curriculum/spreadsheets/intermediate/math-functions/countunique-function.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/spreadsheets/intermediate/math-functions/countunique-function.md?ref=77739399aef05a7cae48b4b6368d0f514cf60b44)
- [ ] [enkidevs/curriculum/spreadsheets/intermediate/math-functions/even-odd-iseven-isodd.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/spreadsheets/intermediate/math-functions/even-odd-iseven-isodd.md?ref=77739399aef05a7cae48b4b6368d0f514cf60b44)
- [ ] [enkidevs/curriculum/spreadsheets/intermediate/math-functions/floor-function.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/spreadsheets/intermediate/math-functions/floor-function.md?ref=77739399aef05a7cae48b4b6368d0f514cf60b44)
- [ ] [enkidevs/curriculum/spreadsheets/intermediate/math-functions/power-function.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/spreadsheets/intermediate/math-functions/power-function.md?ref=77739399aef05a7cae48b4b6368d0f514cf60b44)
- [ ] [enkidevs/curriculum/spreadsheets/intermediate/more-functions-and-formulas/concat.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/spreadsheets/intermediate/more-functions-and-formulas/concat.md?ref=77739399aef05a7cae48b4b6368d0f514cf60b44)
- [ ] [enkidevs/curriculum/spreadsheets/intermediate/more-functions-and-formulas/concatenate.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/spreadsheets/intermediate/more-functions-and-formulas/concatenate.md?ref=77739399aef05a7cae48b4b6368d0f514cf60b44)
- [ ] [enkidevs/curriculum/spreadsheets/intermediate/more-functions-and-formulas/date-time-functions.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/spreadsheets/intermediate/more-functions-and-formulas/date-time-functions.md?ref=77739399aef05a7cae48b4b6368d0f514cf60b44)
- [ ] [enkidevs/curriculum/spreadsheets/intermediate/more-functions-and-formulas/proper.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/spreadsheets/intermediate/more-functions-and-formulas/proper.md?ref=77739399aef05a7cae48b4b6368d0f514cf60b44)
- [ ] [enkidevs/curriculum/spreadsheets/intermediate/more-functions-and-formulas/unique.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/spreadsheets/intermediate/more-functions-and-formulas/unique.md?ref=77739399aef05a7cae48b4b6368d0f514cf60b44)
- [ ] [enkidevs/curriculum/spreadsheets/intermediate/parser-functions/to-date.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/spreadsheets/intermediate/parser-functions/to-date.md?ref=77739399aef05a7cae48b4b6368d0f514cf60b44)
- [ ] [enkidevs/curriculum/spreadsheets/intermediate/parser-functions/to-dollars.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/spreadsheets/intermediate/parser-functions/to-dollars.md?ref=77739399aef05a7cae48b4b6368d0f514cf60b44)
- [ ] [enkidevs/curriculum/spreadsheets/intermediate/parser-functions/to-percent.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/spreadsheets/intermediate/parser-functions/to-percent.md?ref=77739399aef05a7cae48b4b6368d0f514cf60b44)
- [ ] [enkidevs/curriculum/spreadsheets/intermediate/parser-functions/to-pure-number.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/spreadsheets/intermediate/parser-functions/to-pure-number.md?ref=77739399aef05a7cae48b4b6368d0f514cf60b44)
- [ ] [enkidevs/curriculum/spreadsheets/intermediate/parser-functions/to-text.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/spreadsheets/intermediate/parser-functions/to-text.md?ref=77739399aef05a7cae48b4b6368d0f514cf60b44)

**Comment by kapnobatai137** [comment]
closed in favour of #2312

**Pull request closed without merging**
