### PR TITLE
[WIP] Security: Application Security: OWASP

### PR DESCRIPTION
**Pull request by lizTheDeveloper**

### CODE REVIEW

**Comment by enki-hq** [comment]
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/.archived/security/custom-workout/black-hat.md?ref=20ce052ad5b927432fed330789395051ddd37561
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/.archived/security/custom-workout/grey-hat.md?ref=20ce052ad5b927432fed330789395051ddd37561
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/.archived/security/custom-workout/war-games.md?ref=20ce052ad5b927432fed330789395051ddd37561
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/.archived/security/custom-workout/white-hat.md?ref=20ce052ad5b927432fed330789395051ddd37561
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/.archived/security/custom-workout/xss-introduction.md?ref=20ce052ad5b927432fed330789395051ddd37561
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/security/core/application-layer/identifying-the-application-layer.md?ref=20ce052ad5b927432fed330789395051ddd37561
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/security/core/application-layer/securing-the-application-layer.md?ref=20ce052ad5b927432fed330789395051ddd37561
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/security/core/data-link-layer/identifying-the-data-link-layer.md?ref=20ce052ad5b927432fed330789395051ddd37561
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/security/core/data-link-layer/securing-the-data-link-layer.md?ref=20ce052ad5b927432fed330789395051ddd37561
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/security/core/network-layer/identifying-the-network-layer.md?ref=20ce052ad5b927432fed330789395051ddd37561
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/security/core/network-layer/securing-the-network-layer.md?ref=20ce052ad5b927432fed330789395051ddd37561
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/security/core/osi-model/introducing-the-osi-model.md?ref=20ce052ad5b927432fed330789395051ddd37561
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/security/core/physical-layer/identifying-the-physical-layer.md?ref=20ce052ad5b927432fed330789395051ddd37561
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/security/core/physical-layer/securing-the-physical-layer.md?ref=20ce052ad5b927432fed330789395051ddd37561
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/security/core/presentation-layer/identifying-the-presentation-layer.md?ref=20ce052ad5b927432fed330789395051ddd37561
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/security/core/presentation-layer/securing-the-presentation-layer.md?ref=20ce052ad5b927432fed330789395051ddd37561
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/security/core/session-layer/identifying-the-session-layer.md?ref=20ce052ad5b927432fed330789395051ddd37561
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/security/core/session-layer/securing-the-session-layer.md?ref=20ce052ad5b927432fed330789395051ddd37561
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/security/core/transport-layer/identifying-the-transport-layer.md?ref=20ce052ad5b927432fed330789395051ddd37561
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/security/core/transport-layer/securing-the-transport-layer.md?ref=20ce052ad5b927432fed330789395051ddd37561

**Comment by lizTheDeveloper** [comment]
@milesflo are these commits on master somewhere, like in another PR?
If not can you rerender them so I can get them in

**Comment by enki-hq** [comment]
Failed parsing files: 
  - security/README.md: 
 > duplicated mapping key at line 9, column 1:
    icon: '[-949 951 100 100] <switc ... 
    ^
  - javascript/ecmascript-2015/function-improvements/arrow-functions-part-2.md: 
 > duplicated mapping key at line 31, column -126:
    links:
    ^
  - security/owasp-top-10-application-vulnerabilities/a1-injection/identifying-sql-injection-risks.md: 
 > Must have exactly 1 headline but found 2 instead.
  - security/owasp-top-10-application-vulnerabilities/a2-broken-authentication/a2-broken-authentication.md: 
 > Must have exactly 1 headline but found 2 instead.
  - security/owasp-top-10-application-vulnerabilities/a3-sensitive-data-exposure/a3-sensitive-data-exposure.md: 
 > Must have exactly 1 headline but found 2 instead.
  - security/owasp-top-10-application-vulnerabilities/a4-xml-external-entities/a4-xml-external-entities.md: 
 > Must have exactly 1 headline but found 2 instead.
  - security/owasp-top-10-application-vulnerabilities/broken-authentication/a2-broken-authentication.md: 
 > Must have exactly 1 headline but found 2 instead.
  - security/owasp-top-10-application-vulnerabilities/injection/identifying-sql-injection-risks.md: 
 > Must have exactly 1 headline but found 2 instead.
  - security/owasp-top-10-application-vulnerabilities/injection/mitigating-sql-injection-orm.md: 
 > Must have exactly 1 headline but found 2 instead.
  - security/owasp-top-10-application-vulnerabilities/injection/mitigating-sql-injection-parameters.md: 
 > Must have exactly 1 headline but found 2 instead.
  - security/owasp-top-10-application-vulnerabilities/injection/mitigating-sql-injection-whitelist.md: 
 > Must have exactly 1 headline but found 2 instead.
  - security/owasp-top-10-application-vulnerabilities/sensitive-data-exposure/a3-sensitive-data-exposure.md: 
 > Must have exactly 1 headline but found 2 instead.
  - security/owasp-top-10-application-vulnerabilities/xml-external-entities/a4-xml-external-entities.md: 
 > Must have exactly 1 headline but found 2 instead.

**Comment by ryanwarsaw** [comment]
@milesflo @lizTheDeveloper Do we want to merge this in or close it?

**Comment by milesflo** [comment]
No this PR's ancient... It's not worth bringing into the fold today. I'll leave this here if we want to create a new PR for it.

**Pull request closed without merging**
