### PR TITLE
Apply shorter copy to coding exercises

### PR DESCRIPTION
**Pull request by Stefan-Stojanovic**

### CODE REVIEW

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Insight previews:
- [ ] [enkidevs/curriculum/javascript/javascript-core/is-it-a-palindrome-exercise/is-it-a-palindrome-exercise.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-core/is-it-a-palindrome-exercise/is-it-a-palindrome-exercise.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/javascript/javascript-core/largest-array-element-exercise/largest-array-element-exercise.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-core/largest-array-element-exercise/largest-array-element-exercise.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/javascript/javascript-core/update-object-values-exercise/update-object-values-exercise.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-core/update-object-values-exercise/update-object-values-exercise.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/javascript/javascript-core/weekend-and-weekday-switch-exercise/weekend-and-weekday-switch.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-core/weekend-and-weekday-switch-exercise/weekend-and-weekday-switch.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/js-adding-and-sorting-arrays/js-adding-and-sorting-arrays.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/js-adding-and-sorting-arrays/js-adding-and-sorting-arrays.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/js-arithmetic-operation/js-arithmetic-operation.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/js-arithmetic-operation/js-arithmetic-operation.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/js-array-of-characters-to-string/js-array-of-characters-to-string.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/js-array-of-characters-to-string/js-array-of-characters-to-string.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/js-beginning-and-end-pairs/js-beginning-and-end-pairs.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/js-beginning-and-end-pairs/js-beginning-and-end-pairs.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/js-calculator-class/js-calculator-class.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/js-calculator-class/js-calculator-class.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/js-dice-roll/js-dice-roll.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/js-dice-roll/js-dice-roll.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/js-even-or-odd/js-even-or-odd.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/js-even-or-odd/js-even-or-odd.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/js-factorial-calculator/js-factorial-calculator.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/js-factorial-calculator/js-factorial-calculator.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/js-fibonacci-sequence/js-fibonacci-sequence.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/js-fibonacci-sequence/js-fibonacci-sequence.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/js-happy-birthday/js-happy-birthday.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/js-happy-birthday/js-happy-birthday.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/js-harmonic-series/js-harmonic-series.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/js-harmonic-series/js-harmonic-series.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/js-iterate-over-object-values/js-iterate-over-object-values.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/js-iterate-over-object-values/js-iterate-over-object-values.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/js-iterate-over-two-arrays/js-iterate-over-two-arrays.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/js-iterate-over-two-arrays/js-iterate-over-two-arrays.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/js-least-frequent-character/js-least-frequent-character.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/js-least-frequent-character/js-least-frequent-character.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/js-miles-to-kilometres/js-miles-to-kilometres.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/js-miles-to-kilometres/js-miles-to-kilometres.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/js-multiplication-table/js-multiplication-table.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/js-multiplication-table/js-multiplication-table.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/js-object-combination/js-combine-objects.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/js-object-combination/js-combine-objects.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/js-pascals-triangle/js-pascals-triangle.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/js-pascals-triangle/js-pascals-triangle.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/js-print-primes/js-print-primes.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/js-print-primes/js-print-primes.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/js-remove-duplicate-from-array/js-remove-duplicate-from-array.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/js-remove-duplicate-from-array/js-remove-duplicate-from-array.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/js-remove-odd-numbers-from-array/js-remove-odd-numbers-from-array.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/js-remove-odd-numbers-from-array/js-remove-odd-numbers-from-array.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/js-reverse-a-string/js-reverse-a-string.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/js-reverse-a-string/js-reverse-a-string.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/js-smallest-array-element/js-smallest-array-element.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/js-smallest-array-element/js-smallest-array-element.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/js-sort-arrays-in-a-object/js-sort-arrays-in-a-object.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/js-sort-arrays-in-a-object/js-sort-arrays-in-a-object.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/js-squared-object-keys/js-squared-object-keys.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/js-squared-object-keys/js-squared-object-keys.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/js-stopping-a-loop/js-stopping-a-loop.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/js-stopping-a-loop/js-stopping-a-loop.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/js-string-length/js-string-length.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/js-string-length/js-string-length.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/js-sum-and-product-of-two-arrays/js-sum-and-product-of-two-arrays.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/js-sum-and-product-of-two-arrays/js-sum-and-product-of-two-arrays.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/js-sum-items-in-object/js-sum-items-in-object.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/js-sum-items-in-object/js-sum-items-in-object.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/js-word-length/js-word-length.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/js-word-length/js-word-length.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/python/python-core/arithmetic-operation-exercise/arithmetic-operation-exercise.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-core/arithmetic-operation-exercise/arithmetic-operation-exercise.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/python/python-core/day-of-the-week-function-exercise/day-of-the-week-function-exercise.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-core/day-of-the-week-function-exercise/day-of-the-week-function-exercise.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/python/python-core/even-or-odd-exercise/even-or-odd-exercise.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-core/even-or-odd-exercise/even-or-odd-exercise.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/python/python-core/pattern-printing-exercise/pattern-printing-exercise.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-core/pattern-printing-exercise/pattern-printing-exercise.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/python/python-core/populate-a-dictionary-exercise/populate-a-dictionary-exercise.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-core/populate-a-dictionary-exercise/populate-a-dictionary-exercise.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/python/python-core/populate-a-tuple-exercise/populate-a-tuple-exercise.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-core/populate-a-tuple-exercise/populate-a-tuple-exercise.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/python/python-core/remove-add-values-to-a-list-exercise/remove-add-values-to-a-list-exercise.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-core/remove-add-values-to-a-list-exercise/remove-add-values-to-a-list-exercise.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/python/python-core/value-in-a-string-exercise/check-if-value-is-in-string.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-core/value-in-a-string-exercise/check-if-value-is-in-string.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/python/python-playground-questions/adding-and-sorting-lists/adding-and-sorting-lists.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/adding-and-sorting-lists/adding-and-sorting-lists.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/python/python-playground-questions/arithmetic-operation/arithmetic-operation.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/arithmetic-operation/arithmetic-operation.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/python/python-playground-questions/beginning-and-end-pairs/beginning-and-end-pairs.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/beginning-and-end-pairs/beginning-and-end-pairs.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/python/python-playground-questions/calculator-class/calculator-class.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/calculator-class/calculator-class.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/python/python-playground-questions/combine-dictionaries/combine-dictionaries.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/combine-dictionaries/combine-dictionaries.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/python/python-playground-questions/dice-roll/dice-roll.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/dice-roll/dice-roll.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/python/python-playground-questions/even-or-odd/even-or-odd.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/even-or-odd/even-or-odd.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/python/python-playground-questions/factorial-calculator/factorial-calculator.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/factorial-calculator/factorial-calculator.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/python/python-playground-questions/fibonacci-sequence/fibonacci-sequence.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/fibonacci-sequence/fibonacci-sequence.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/python/python-playground-questions/happy-birthday/happy-birthday.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/happy-birthday/happy-birthday.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/python/python-playground-questions/harmonic-series/harmonic-series.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/harmonic-series/harmonic-series.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/python/python-playground-questions/iterate-over-dict-values/iterate-over-dict-values.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/iterate-over-dict-values/iterate-over-dict-values.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/python/python-playground-questions/iterate-over-two-lists/iterate-over-two-lists.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/iterate-over-two-lists/iterate-over-two-lists.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/python/python-playground-questions/least-frequent-character/least-frequent-character.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/least-frequent-character/least-frequent-character.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/python/python-playground-questions/list-of-characters-to-string/list-of-characters-to-string.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/list-of-characters-to-string/list-of-characters-to-string.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/python/python-playground-questions/miles-to-kilometres/miles-to-kilometres.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/miles-to-kilometres/miles-to-kilometres.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/python/python-playground-questions/multiplication-table/multiplication-table.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/multiplication-table/multiplication-table.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/python/python-playground-questions/pascals-triangle/pascals-triangle.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/pascals-triangle/pascals-triangle.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/python/python-playground-questions/print-primes/print-primes.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/print-primes/print-primes.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/python/python-playground-questions/remove-duplicate-from-tuple/remove-duplicate-from-tuple.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/remove-duplicate-from-tuple/remove-duplicate-from-tuple.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/python/python-playground-questions/remove-odd-numbers-from-list/remove-odd-numbers-from-list.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/remove-odd-numbers-from-list/remove-odd-numbers-from-list.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/python/python-playground-questions/reverse-a-string/reverse-a-string.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/reverse-a-string/reverse-a-string.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/python/python-playground-questions/smallest-list-element/smallest-list-element.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/smallest-list-element/smallest-list-element.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/python/python-playground-questions/sort-lists-in-a-dict/sort-lists-in-a-dict.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/sort-lists-in-a-dict/sort-lists-in-a-dict.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/python/python-playground-questions/squared-dictionary-keys/squared-dictionary-keys.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/squared-dictionary-keys/squared-dictionary-keys.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/python/python-playground-questions/stopping-a-loop/stopping-a-loop.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/stopping-a-loop/stopping-a-loop.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/python/python-playground-questions/string-length/string-length.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/string-length/string-length.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/python/python-playground-questions/sum-and-product-of-two-tuples/sum-and-product-of-two-tuples.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/sum-and-product-of-two-tuples/sum-and-product-of-two-tuples.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/python/python-playground-questions/sum-items-in-dict/sum-items-in-dict.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/sum-items-in-dict/sum-items-in-dict.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)
- [ ] [enkidevs/curriculum/python/python-playground-questions/word-length/word-length.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/word-length/word-length.md?ref=3f4d695e898fa320fa14c34f29dd8367dc09679a)

**Comment by Stefan-Stojanovic** [comment]
I think I did not miss any whitespace, but to make sure can someone give it another look? My VSCode kept either giving extra whitespace or it was lacking it

**Comment by Stefan-Stojanovic** [comment]
apparently, 2 out of those 72 coding insights, have had a slightly different copy and was creating problems when copy-pasting, I think I have finally fixed it, still need another set of eyes to make sure this is what we want

**Review by nem035 — APPROVED** [review]

**Pull request merged**
