### PR TITLE
Update datetime-object.md

### PR DESCRIPTION
**Pull request by Stefan-Stojanovic**
`date_two != date_one`
and
`date_one != date_two`
and
`date_one > date_two`
Provide the output "True"

I've changed the possible answers so there is only one solution.

### CODE REVIEW

**Comment by enki-hq** [comment]
### Insight previews:
- [ ] [enkidevs/curriculum/python/core/playing-with-time/datetime-object.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/python/core/playing-with-time/datetime-object.md?ref=6fd456ca9c4b857f1c338e6929aba506e226ace6)

**Comment by kapnobatai137** [comment]
hmmm, looking at comments this might require some more improvements. will come back to this

**Comment by Stefan-Stojanovic** [comment]
> hmmm, looking at comments this might require some more improvements. will come back to this

Maybe we should merge the question because this might affect people's progress in the topic?

Having a broken question can make people stop with the whole topic as opposed to just skipping it?

**Comment by kapnobatai137** [comment]
> > hmmm, looking at comments this might require some more improvements. will come back to this
> 
> Maybe we should merge the question because this might affect people's progress in the topic?
> 
> Having a broken question can make people stop with the whole topic as opposed to just skipping it?
> 
> And note down that the insight needs improving

you are 100% right that we should. merging now

**Pull request merged**
