### PR TITLE
Add type in the gap HTML

### PR DESCRIPTION
**Pull request by Stefan-Stojanovic**
Marked if applied to all insights:

- [x] Shorten all Headlines (If possible)

- [x] Remove all backticks and HTML tags from every headline

- [x] Add type in the gap and change context to standalone to all applicable questions

- [x] Change some questions to support type in the gap

### CODE REVIEW

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
Failed parsing files: 
  - web/html/lists/description-lists.md: 
 > 	No valid answer list in question node

**Comment by enki-hq** [comment]
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| table-tr-and-td | <ul><li>`CodePen: Table without Style` pointing to `https://codepen.io/enkidevs/pen/JBXWLL` is broken because `HTTP_403`</li><li>`CodePen: Table with Style` pointing to `https://codepen.io/enkidevs/pen/JBXWbr` is broken because `HTTP_403`</li></ul> |
| thead-tbody-and-tfoot | <ul><li>`CodePen: Scrolling Table CSS` pointing to `https://codepen.io/enkidevs/pen/JBXyoJ` is broken because `HTTP_403`</li><li>`Codepen Example` pointing to `https://codepen.io/stefan-stojanovic/pen/jKbJgQ` is broken because `HTTP_403`</li></ul> |
| intro-th | <ul><li>`CodePen: Table Default style of th element` pointing to `https://codepen.io/enkidevs/pen/ejZgbN` is broken because `HTTP_403`</li><li>`CodePen: Table tabular header` pointing to `https://codepen.io/enkidevs/pen/ajNpdb` is broken because `HTTP_403`</li><li>`CodePen: Table multiple spans` pointing to `https://codepen.io/enkidevs/pen/XBdpgW` is broken because `HTTP_403`</li><li>`CodePen: Table multiple spans` pointing to `https://codepen.io/enkidevs/pen/NBNdwO` is broken because `HTTP_403`</li><li>`CodePen: Table abbr attribute` pointing to `https://codepen.io/enkidevs/pen/ajNJdW` is broken because `HTTP_403`</li></ul> |
| video | <ul><li>`CodePen: Video: Simple HTML Player` pointing to `https://codepen.io/enkidevs/pen/MBYOJb` is broken because `HTTP_403`</li></ul> |
| submit-and-reset | The practice question context `stanndalone` is unrecognized. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| table-tr-and-td | <ul><li>`CodePen: Table without Style` pointing to `https://codepen.io/enkidevs/pen/JBXWLL` is broken because `HTTP_403`</li><li>`CodePen: Table with Style` pointing to `https://codepen.io/enkidevs/pen/JBXWbr` is broken because `HTTP_403`</li></ul> |
| thead-tbody-and-tfoot | <ul><li>`CodePen: Scrolling Table CSS` pointing to `https://codepen.io/enkidevs/pen/JBXyoJ` is broken because `HTTP_403`</li><li>`Codepen Example` pointing to `https://codepen.io/stefan-stojanovic/pen/jKbJgQ` is broken because `HTTP_403`</li></ul> |
| intro-th | <ul><li>`CodePen: Table Default style of th element` pointing to `https://codepen.io/enkidevs/pen/ejZgbN` is broken because `HTTP_403`</li><li>`CodePen: Table tabular header` pointing to `https://codepen.io/enkidevs/pen/ajNpdb` is broken because `HTTP_403`</li><li>`CodePen: Table multiple spans` pointing to `https://codepen.io/enkidevs/pen/XBdpgW` is broken because `HTTP_403`</li><li>`CodePen: Table multiple spans` pointing to `https://codepen.io/enkidevs/pen/NBNdwO` is broken because `HTTP_403`</li><li>`CodePen: Table abbr attribute` pointing to `https://codepen.io/enkidevs/pen/ajNJdW` is broken because `HTTP_403`</li></ul> |
| video | <ul><li>`CodePen: Video: Simple HTML Player` pointing to `https://codepen.io/enkidevs/pen/MBYOJb` is broken because `HTTP_403`</li></ul> |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| table-tr-and-td | <ul><li>`CodePen: Table without Style` pointing to `https://codepen.io/enkidevs/pen/JBXWLL` is broken because `HTTP_403`</li><li>`CodePen: Table with Style` pointing to `https://codepen.io/enkidevs/pen/JBXWbr` is broken because `HTTP_403`</li></ul> |
| intro-th | <ul><li>`CodePen: Table Default style of th element` pointing to `https://codepen.io/enkidevs/pen/ejZgbN` is broken because `HTTP_403`</li><li>`CodePen: Table tabular header` pointing to `https://codepen.io/enkidevs/pen/ajNpdb` is broken because `HTTP_403`</li><li>`CodePen: Table multiple spans` pointing to `https://codepen.io/enkidevs/pen/XBdpgW` is broken because `HTTP_403`</li><li>`CodePen: Table multiple spans` pointing to `https://codepen.io/enkidevs/pen/NBNdwO` is broken because `HTTP_403`</li><li>`CodePen: Table abbr attribute` pointing to `https://codepen.io/enkidevs/pen/ajNJdW` is broken because `HTTP_403`</li></ul> |
| thead-tbody-and-tfoot | <ul><li>`CodePen: Scrolling Table CSS` pointing to `https://codepen.io/enkidevs/pen/JBXyoJ` is broken because `HTTP_403`</li><li>`Codepen Example` pointing to `https://codepen.io/stefan-stojanovic/pen/jKbJgQ` is broken because `HTTP_403`</li></ul> |
| video | <ul><li>`CodePen: Video: Simple HTML Player` pointing to `https://codepen.io/enkidevs/pen/MBYOJb` is broken because `HTTP_403`</li></ul> |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Review by kapnobatai137 — APPROVED** [review]

**Pull request merged**
