### PR TITLE
Update web-introduction

### PR DESCRIPTION
**Pull request by Stefan-Stojanovic**

### CODE REVIEW

**Comment by enki-hq** [comment]
### Insight previews:
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/Web/HTML/web-introduction/css-defined.md?ref=76a9df2c49e920410e9d255b416da4492dded810

**Comment by matthewleach** [comment]
Work in Progress - NEEDS SVG IMAGE

**Comment by nem035** [comment]
@matthewleach , it's better to add a `[WIP]` prefix to the title of your PR rather than leave a comment since it's more obvious this way 👍

**Comment by lizTheDeveloper** [comment]
@matthewleach and @Stefan-Stojanovic I have moved this to the `html-course-updates` branch

**Pull request closed without merging**
