### PR TITLE
added MDN links to Javascript curriculum 

### PR DESCRIPTION
**Pull request by masakistewart**

### CODE REVIEW

**Comment by enki-hq** [comment]
bad indentation of a sequence entry at line 3, column 10:
      - [MDN](https://developer.mozilla.org/e ... 
             ^

**Comment by enki-hq** [comment]
bad indentation of a sequence entry at line 3, column 28:
      - [EcmaScript 6 Features](https://github.com/lukehoban/es ... 
                               ^

**Comment by enki-hq** [comment]
bad indentation of a sequence entry at line 3, column 104:
     ... t/Reference/Global_Objects/Map)'{website}
                                         ^

**Comment by lizTheDeveloper** [comment]
awesome- these links will help a lot of people learning ECMAScript 💯

**Pull request merged**
