### PR TITLE
Lua patch: Archiving Workouts

### PR DESCRIPTION
**Pull request by junoocha**
**NOTE: When accepting this pull request, it should be coordinated with the other Lua Patch that focuses on revamping the installation workout, as these two pull requests are connected.

When everything is ready, the plan is to first merge this PR into master, then have the second branch to pull the changes and then merge immediately.
**

Due to the changes that were planned in the changes to the Lua installation workout, there are three workouts to be archived.

intro-to-lua-ii

Due to the switch from downloading and installing and IDE to simply using an online IDE or Roblox Studio, it effectively renders this workout to be pointless and will be archived.
io-operations-in-lua-i and -ii

Due to the use of an online IDE/ Roblox Studio for the Lua Course, IO operations are not needed, as they cannot be used properly with an online IDE. Most importantly, IO operations are deprecated in Roblox studio and will not be used in the future, hence leading to the archive of these workouts.

### CODE REVIEW

**Comment by enki-hq** [comment]
### Course

| Course Name | Error Message |
|:-:|:-:|
| intro-to-lua-ii | Course does not have sections. |
| io-operations-in-lua-i | Course does not have sections. |
| io-operations-in-lua-ii | Course does not have sections. |

> If you notice anything wrong with these rules contact content-team@enki.com.

**Comment by enki-hq** [comment]
### Course

| Course Name | Error Message |
|:-:|:-:|
| intro-to-lua-ii | Course does not have sections. |
| io-operations-in-lua-i | Course does not have sections. |
| io-operations-in-lua-ii | Course does not have sections. |

> If you notice anything wrong with these rules contact content-team@enki.com.

**Comment by enki-hq** [comment]
### Insight previews:
- [ ] [enkidevs/curriculum/.archived/lua/lua-core/intro-to-lua-ii/installing-lua-i.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/.archived/lua/lua-core/intro-to-lua-ii/installing-lua-i.md?ref=7a23c9a4ed96703c49895681b1e1af4c044768e2)
- [ ] [enkidevs/curriculum/.archived/lua/lua-core/intro-to-lua-ii/installing-lua-ii.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/.archived/lua/lua-core/intro-to-lua-ii/installing-lua-ii.md?ref=7a23c9a4ed96703c49895681b1e1af4c044768e2)
- [ ] [enkidevs/curriculum/.archived/lua/lua-core/intro-to-lua-ii/installing-lua-iii.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/.archived/lua/lua-core/intro-to-lua-ii/installing-lua-iii.md?ref=7a23c9a4ed96703c49895681b1e1af4c044768e2)
- [ ] [enkidevs/curriculum/.archived/lua/lua-core/io-operations-in-lua-i/io-read-in-lua-i.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/.archived/lua/lua-core/io-operations-in-lua-i/io-read-in-lua-i.md?ref=7a23c9a4ed96703c49895681b1e1af4c044768e2)
- [ ] [enkidevs/curriculum/.archived/lua/lua-core/io-operations-in-lua-i/io-read-in-lua-ii.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/.archived/lua/lua-core/io-operations-in-lua-i/io-read-in-lua-ii.md?ref=7a23c9a4ed96703c49895681b1e1af4c044768e2)
- [ ] [enkidevs/curriculum/.archived/lua/lua-core/io-operations-in-lua-i/io-write-in-lua-i.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/.archived/lua/lua-core/io-operations-in-lua-i/io-write-in-lua-i.md?ref=7a23c9a4ed96703c49895681b1e1af4c044768e2)
- [ ] [enkidevs/curriculum/.archived/lua/lua-core/io-operations-in-lua-i/io-write-in-lua-ii.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/.archived/lua/lua-core/io-operations-in-lua-i/io-write-in-lua-ii.md?ref=7a23c9a4ed96703c49895681b1e1af4c044768e2)
- [ ] [enkidevs/curriculum/.archived/lua/lua-core/io-operations-in-lua-i/the-io-library-in-lua.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/.archived/lua/lua-core/io-operations-in-lua-i/the-io-library-in-lua.md?ref=7a23c9a4ed96703c49895681b1e1af4c044768e2)
- [ ] [enkidevs/curriculum/.archived/lua/lua-core/io-operations-in-lua-ii/io-input-output-in-lua.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/.archived/lua/lua-core/io-operations-in-lua-ii/io-input-output-in-lua.md?ref=7a23c9a4ed96703c49895681b1e1af4c044768e2)
- [ ] [enkidevs/curriculum/.archived/lua/lua-core/io-operations-in-lua-ii/io-lines-in-lua.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/.archived/lua/lua-core/io-operations-in-lua-ii/io-lines-in-lua.md?ref=7a23c9a4ed96703c49895681b1e1af4c044768e2)
- [ ] [enkidevs/curriculum/.archived/lua/lua-core/io-operations-in-lua-ii/io-open-in-lua-i.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/.archived/lua/lua-core/io-operations-in-lua-ii/io-open-in-lua-i.md?ref=7a23c9a4ed96703c49895681b1e1af4c044768e2)
- [ ] [enkidevs/curriculum/.archived/lua/lua-core/io-operations-in-lua-ii/io-open-in-lua-ii.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/.archived/lua/lua-core/io-operations-in-lua-ii/io-open-in-lua-ii.md?ref=7a23c9a4ed96703c49895681b1e1af4c044768e2)

**Comment by junoocha** [comment]
Due to the inconveniences that follow from archiving workouts, this PR is closed and a different option will be opted for.

**Pull request closed without merging**
