### PR TITLE
Update del-statement-for-lists.md

### PR DESCRIPTION
**Pull request by nem035**
I thought that `[0:2]` should be explained a bit more.

### CODE REVIEW

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Review by abdullahtahir147 — DISMISSED** [review]

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Insight previews:
- [ ] [enkidevs/curriculum/python/python-core/sequential-data-types-ii/del-statement-for-lists.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-core/sequential-data-types-ii/del-statement-for-lists.md?ref=56691e41743ddfa972285209e58f52d8dfbdc20c)

**Review by Stefan-Stojanovic — APPROVED** [review]

**Pull request merged**
