### PR TITLE
Add Core course for the DA with Python topic{wip}

### PR DESCRIPTION
**Pull request by Stefan-Stojanovic**

### CODE REVIEW

**Comment by enki-hq** [comment]
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| WIPintro-to-pandas-series | Insight slug `WIPintro-to-pandas-series` contains forbidden characters. |
### Workout

| Workout Name | Error Message |
|:-:|:-:|
| intro-jupyter-lab | One of the mentioned insights couldn't be found in this pull request or the database. |
| python-libraries | One of the mentioned insights couldn't be found in this pull request or the database. |
| the-ipython-shell | One of the mentioned insights couldn't be found in this pull request or the database. |
### Course

| Course Name | Error Message |
|:-:|:-:|
| core | We couldn't find these workouts: `the-jupyter-lab`. |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
Failed parsing files: 
  - data-analysis-with-python/core/intro-jupyter-lab/starting-jupyter-lab.md: 
 > 	No valid answer list in question node
  - data-analysis-with-python/core/the-ipython-shell/ipython-vs-regular-shell-examples.md: 
 > 	No valid answer list in question node
  - data-analysis-with-python/core/the-ipython-shell/what-is-ipython.md: 
 > 	No valid answer list in question node

**Comment by enki-hq** [comment]
### Workout

| Workout Name | Error Message |
|:-:|:-:|
| intro-jupyter-lab | One of the mentioned insights couldn't be found in this pull request or the database. |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Workout

| Workout Name | Error Message |
|:-:|:-:|
| intro-jupyter-lab | One of the mentioned insights couldn't be found in this pull request or the database. |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
Failed parsing files: 
  - data-analysis-with-python/core/intro-to-numpy/numpy-array-vs-python-list-ii.md: 
 > 	Cannot compile node with invalid type heading

**Comment by kapnobatai137** [comment]
@Stefan-Stojanovic is this PR relevant or can we close it and delete the branch?

**Comment by Stefan-Stojanovic** [comment]
Nah, this is irrelevant now. I will close it

**Pull request closed without merging**
