### PR TITLE
Update readmes and setupCodes for Python coding insights 

### PR DESCRIPTION
**Pull request by Stefan-Stojanovic**

### CODE REVIEW

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Insight previews:
- [ ] [enkidevs/curriculum/python/python-core/arithmetic-operation-exercise/arithmetic-operation-exercise.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-core/arithmetic-operation-exercise/arithmetic-operation-exercise.md?ref=d2d2cc9771acb17371fd67aa1a57f1a2a0c0be48)
- [ ] [enkidevs/curriculum/python/python-core/day-of-the-week-function-exercise/day-of-the-week-function-exercise.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-core/day-of-the-week-function-exercise/day-of-the-week-function-exercise.md?ref=d2d2cc9771acb17371fd67aa1a57f1a2a0c0be48)
- [ ] [enkidevs/curriculum/python/python-core/even-or-odd-exercise/even-or-odd-exercise.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-core/even-or-odd-exercise/even-or-odd-exercise.md?ref=d2d2cc9771acb17371fd67aa1a57f1a2a0c0be48)
- [ ] [enkidevs/curriculum/python/python-core/pattern-printing-exercise/pattern-printing-exercise.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-core/pattern-printing-exercise/pattern-printing-exercise.md?ref=d2d2cc9771acb17371fd67aa1a57f1a2a0c0be48)
- [ ] [enkidevs/curriculum/python/python-core/value-in-a-string-exercise/check-if-value-is-in-string.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-core/value-in-a-string-exercise/check-if-value-is-in-string.md?ref=d2d2cc9771acb17371fd67aa1a57f1a2a0c0be48)
- [ ] [enkidevs/curriculum/python/python-playground-questions/adding-and-sorting-lists/adding-and-sorting-lists.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/adding-and-sorting-lists/adding-and-sorting-lists.md?ref=d2d2cc9771acb17371fd67aa1a57f1a2a0c0be48)
- [ ] [enkidevs/curriculum/python/python-playground-questions/arithmetic-operation/arithmetic-operation.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/arithmetic-operation/arithmetic-operation.md?ref=d2d2cc9771acb17371fd67aa1a57f1a2a0c0be48)
- [ ] [enkidevs/curriculum/python/python-playground-questions/beginning-and-end-pairs/beginning-and-end-pairs.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/beginning-and-end-pairs/beginning-and-end-pairs.md?ref=d2d2cc9771acb17371fd67aa1a57f1a2a0c0be48)
- [ ] [enkidevs/curriculum/python/python-playground-questions/calculator-class/calculator-class.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/calculator-class/calculator-class.md?ref=d2d2cc9771acb17371fd67aa1a57f1a2a0c0be48)
- [ ] [enkidevs/curriculum/python/python-playground-questions/combine-dictionaries/combine-dictionaries.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/combine-dictionaries/combine-dictionaries.md?ref=d2d2cc9771acb17371fd67aa1a57f1a2a0c0be48)
- [ ] [enkidevs/curriculum/python/python-playground-questions/dice-roll/dice-roll.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/dice-roll/dice-roll.md?ref=d2d2cc9771acb17371fd67aa1a57f1a2a0c0be48)
- [ ] [enkidevs/curriculum/python/python-playground-questions/even-or-odd/even-or-odd.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/even-or-odd/even-or-odd.md?ref=d2d2cc9771acb17371fd67aa1a57f1a2a0c0be48)
- [ ] [enkidevs/curriculum/python/python-playground-questions/factorial-calculator/factorial-calculator.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/factorial-calculator/factorial-calculator.md?ref=d2d2cc9771acb17371fd67aa1a57f1a2a0c0be48)
- [ ] [enkidevs/curriculum/python/python-playground-questions/fibonacci-sequence/fibonacci-sequence.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/fibonacci-sequence/fibonacci-sequence.md?ref=d2d2cc9771acb17371fd67aa1a57f1a2a0c0be48)
- [ ] [enkidevs/curriculum/python/python-playground-questions/happy-birthday/happy-birthday.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/happy-birthday/happy-birthday.md?ref=d2d2cc9771acb17371fd67aa1a57f1a2a0c0be48)
- [ ] [enkidevs/curriculum/python/python-playground-questions/harmonic-series/harmonic-series.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/harmonic-series/harmonic-series.md?ref=d2d2cc9771acb17371fd67aa1a57f1a2a0c0be48)
- [ ] [enkidevs/curriculum/python/python-playground-questions/iterate-over-dict-values/iterate-over-dict-values.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/iterate-over-dict-values/iterate-over-dict-values.md?ref=d2d2cc9771acb17371fd67aa1a57f1a2a0c0be48)
- [ ] [enkidevs/curriculum/python/python-playground-questions/iterate-over-two-lists/iterate-over-two-lists.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/iterate-over-two-lists/iterate-over-two-lists.md?ref=d2d2cc9771acb17371fd67aa1a57f1a2a0c0be48)
- [ ] [enkidevs/curriculum/python/python-playground-questions/least-frequent-character/least-frequent-character.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/least-frequent-character/least-frequent-character.md?ref=d2d2cc9771acb17371fd67aa1a57f1a2a0c0be48)
- [ ] [enkidevs/curriculum/python/python-playground-questions/list-of-characters-to-string/list-of-characters-to-string.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/list-of-characters-to-string/list-of-characters-to-string.md?ref=d2d2cc9771acb17371fd67aa1a57f1a2a0c0be48)
- [ ] [enkidevs/curriculum/python/python-playground-questions/miles-to-kilometres/miles-to-kilometres.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/miles-to-kilometres/miles-to-kilometres.md?ref=d2d2cc9771acb17371fd67aa1a57f1a2a0c0be48)
- [ ] [enkidevs/curriculum/python/python-playground-questions/multiplication-table/multiplication-table.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/multiplication-table/multiplication-table.md?ref=d2d2cc9771acb17371fd67aa1a57f1a2a0c0be48)
- [ ] [enkidevs/curriculum/python/python-playground-questions/pascals-triangle/pascals-triangle.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/pascals-triangle/pascals-triangle.md?ref=d2d2cc9771acb17371fd67aa1a57f1a2a0c0be48)
- [ ] [enkidevs/curriculum/python/python-playground-questions/print-primes/print-primes.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/print-primes/print-primes.md?ref=d2d2cc9771acb17371fd67aa1a57f1a2a0c0be48)
- [ ] [enkidevs/curriculum/python/python-playground-questions/remove-duplicate-from-tuple/remove-duplicate-from-tuple.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/remove-duplicate-from-tuple/remove-duplicate-from-tuple.md?ref=d2d2cc9771acb17371fd67aa1a57f1a2a0c0be48)
- [ ] [enkidevs/curriculum/python/python-playground-questions/remove-odd-numbers-from-list/remove-odd-numbers-from-list.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/remove-odd-numbers-from-list/remove-odd-numbers-from-list.md?ref=d2d2cc9771acb17371fd67aa1a57f1a2a0c0be48)
- [ ] [enkidevs/curriculum/python/python-playground-questions/reverse-a-string/reverse-a-string.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/reverse-a-string/reverse-a-string.md?ref=d2d2cc9771acb17371fd67aa1a57f1a2a0c0be48)
- [ ] [enkidevs/curriculum/python/python-playground-questions/smallest-list-element/smallest-list-element.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/smallest-list-element/smallest-list-element.md?ref=d2d2cc9771acb17371fd67aa1a57f1a2a0c0be48)
- [ ] [enkidevs/curriculum/python/python-playground-questions/sort-lists-in-a-dict/sort-lists-in-a-dict.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/sort-lists-in-a-dict/sort-lists-in-a-dict.md?ref=d2d2cc9771acb17371fd67aa1a57f1a2a0c0be48)
- [ ] [enkidevs/curriculum/python/python-playground-questions/squared-dictionary-keys/squared-dictionary-keys.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/squared-dictionary-keys/squared-dictionary-keys.md?ref=d2d2cc9771acb17371fd67aa1a57f1a2a0c0be48)
- [ ] [enkidevs/curriculum/python/python-playground-questions/stopping-a-loop/stopping-a-loop.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/stopping-a-loop/stopping-a-loop.md?ref=d2d2cc9771acb17371fd67aa1a57f1a2a0c0be48)
- [ ] [enkidevs/curriculum/python/python-playground-questions/string-length/string-length.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/string-length/string-length.md?ref=d2d2cc9771acb17371fd67aa1a57f1a2a0c0be48)
- [ ] [enkidevs/curriculum/python/python-playground-questions/sum-and-product-of-two-tuples/sum-and-product-of-two-tuples.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/sum-and-product-of-two-tuples/sum-and-product-of-two-tuples.md?ref=d2d2cc9771acb17371fd67aa1a57f1a2a0c0be48)
- [ ] [enkidevs/curriculum/python/python-playground-questions/sum-items-in-dict/sum-items-in-dict.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/sum-items-in-dict/sum-items-in-dict.md?ref=d2d2cc9771acb17371fd67aa1a57f1a2a0c0be48)
- [ ] [enkidevs/curriculum/python/python-playground-questions/word-length/word-length.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/word-length/word-length.md?ref=d2d2cc9771acb17371fd67aa1a57f1a2a0c0be48)

**Review by nem035 — DISMISSED** [review]

**Review by nem035 — APPROVED** [review]

**Pull request merged**
