### PR TITLE
Update creating-your-first-notebook.md

### PR DESCRIPTION
**Pull request by nem035**

### CODE REVIEW

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Insight previews:
- [ ] [enkidevs/curriculum/python-data-analysis/python-data-analysis-core/analysis-environments/creating-your-first-notebook.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/python-data-analysis/python-data-analysis-core/analysis-environments/creating-your-first-notebook.md?ref=23e76cb8d4f1c805bd6c701df46c1dbb9f7f3ec6)

**Review by Stefan-Stojanovic — APPROVED** [review]

**Pull request merged**
