### PR TITLE
Update token-standards.md

### PR DESCRIPTION
**Pull request by G1ne**
Addition of 'other' token standards.

### CODE REVIEW

**Comment by enki-hq** [comment]
### Insight previews:
- [ ] https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/blockchain/fundamentals/ethereum-ii/token-standards.md?ref=a96cdaa69fc8fee81de20079cd109d80d674dbc6

**Comment by ryanwarsaw** [comment]
Hey! Thanks for the PR, tagging the appropriate people for review :)

**Comment by G1ne** [comment]
Thanks! I will try to contribute somewhat to the Blockchain course/threads, as I probably know that and HTML best.

**Comment by mihaiberq** [comment]
Thanks for the contribution @G1ne

**Pull request merged**
