### PR TITLE
Add python playground questions

### PR DESCRIPTION
**Pull request by Stefan-Stojanovic**

### CODE REVIEW

**Comment by enki-hq** [comment]
Failed parsing files: 
  - python/python-playground-questions/list-of-characters-to-string/list-of-characters-to-string.md: 
 > 	end of the stream or a document separator is expected at line 17, column 1:
    ]
    ^

**Comment by enki-hq** [comment]
Failed parsing files: 
  - python/python-playground-questions/list-of-characters-to-string/list-of-characters-to-string.md: 
 > 	end of the stream or a document separator is expected at line 17, column 1:
    ]
    ^

**Comment by enki-hq** [comment]
Failed parsing files: 
  - python/python-playground-questions/list-of-characters-to-string/list-of-characters-to-string.md: 
 > 	can not read a block mapping entry; a multiline key may not be an implicit key at line 16, column 1:
    
    ^

**Comment by enki-hq** [comment]
Failed parsing files: 
  - python/python-playground-questions/list-of-characters-to-string/list-of-characters-to-string.md: 
 > 	can not read a block mapping entry; a multiline key may not be an implicit key at line 16, column 1:
    
    ^

**Comment by enki-hq** [comment]
Failed parsing files: 
  - python/python-playground-questions/list-of-characters-to-string/list-of-characters-to-string.md: 
 > 	can not read a block mapping entry; a multiline key may not be an implicit key at line 15, column 1:
    
    ^

**Comment by enki-hq** [comment]
Failed parsing files: 
  - python/python-playground-questions/list-of-characters-to-string/list-of-characters-to-string.md: 
 > 	can not read a block mapping entry; a multiline key may not be an implicit key at line 15, column 1:
    
    ^

**Comment by enki-hq** [comment]
Failed parsing files: 
  - python/python-playground-questions/list-of-characters-to-string/list-of-characters-to-string.md: 
 > 	can not read a block mapping entry; a multiline key may not be an implicit key at line 18, column 1:
    
    ^

**Comment by enki-hq** [comment]
Failed parsing files: 
  - python/python-playground-questions/list-of-characters-to-string/list-of-characters-to-string.md: 
 > 	can not read a block mapping entry; a multiline key may not be an implicit key at line 17, column 1:
    
    ^

**Comment by enki-hq** [comment]
Failed parsing files: 
  - python/python-playground-questions/list-of-characters-to-string/list-of-characters-to-string.md: 
 > 	can not read a block mapping entry; a multiline key may not be an implicit key at line 16, column 1:
    
    ^

**Comment by enki-hq** [comment]
Failed parsing files: 
  - python/python-playground-questions/list-of-characters-to-string/list-of-characters-to-string.md: 
 > 	can not read a block mapping entry; a multiline key may not be an implicit key at line 17, column 1:
    
    ^

**Comment by enki-hq** [comment]
Failed parsing files: 
  - python/python-playground-questions/list-of-characters-to-string/list-of-characters-to-string.md: 
 > 	can not read a block mapping entry; a multiline key may not be an implicit key at line 16, column 1:
    
    ^

**Comment by enki-hq** [comment]
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| adding-and-sorting-lists | `setupCode`=undefined doesn't have the expected Object type |
| beginning-and-end-pairs | `setupCode`=undefined doesn't have the expected Object type |
| calculator-class | `setupCode`=undefined doesn't have the expected Object type |
| combine-dictionaries | `setupCode`=undefined doesn't have the expected Object type |
| dice-roll | `setupCode`=undefined doesn't have the expected Object type |
| even-or-odd | `setupCode`=undefined doesn't have the expected Object type |
| factorial-calculator | `setupCode`=undefined doesn't have the expected Object type |
| fibonacci-sequence | `setupCode`=undefined doesn't have the expected Object type |
| happy-birthday | `setupCode`=undefined doesn't have the expected Object type |
| harmonic-series | `setupCode`=undefined doesn't have the expected Object type |
| iterate-over-dict-values | `setupCode`=undefined doesn't have the expected Object type |
| iterate-over-two-lists | `setupCode`=undefined doesn't have the expected Object type |
| least-frequent-character | `setupCode`=undefined doesn't have the expected Object type |
| miles-to-kilometres | `setupCode`=undefined doesn't have the expected Object type |
| multiplication-table | `setupCode`=undefined doesn't have the expected Object type |
| pascals-triangle | `setupCode`=undefined doesn't have the expected Object type |
| print-primes | `setupCode`=undefined doesn't have the expected Object type |
| remove-duplicate-from-tuple | `setupCode`=undefined doesn't have the expected Object type |
| remove-odd-numbers-from-list | `setupCode`=undefined doesn't have the expected Object type |
| reverse-a-string | `setupCode`=undefined doesn't have the expected Object type |
| smallest-list-element | `setupCode`=undefined doesn't have the expected Object type |
| sort-lists-in-a-dict | `setupCode`=undefined doesn't have the expected Object type |
| squared-dictionary-keys | `setupCode`=undefined doesn't have the expected Object type |
| stopping-a-loop | `setupCode`=undefined doesn't have the expected Object type |
| string-length | `setupCode`=undefined doesn't have the expected Object type |
| sum-and-product-of-two-tuples | `setupCode`=undefined doesn't have the expected Object type |
| sum-items-in-dict | `setupCode`=undefined doesn't have the expected Object type |
| word-length | `setupCode`=undefined doesn't have the expected Object type |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
Failed parsing files: 
  - python/python-playground-questions/adding-and-sorting-lists/adding-and-sorting-lists.md: 
 > 	can not read a block mapping entry; a multiline key may not be an implicit key at line 17, column 1:
    
    ^
  - python/python-playground-questions/beginning-and-end-pairs/beginning-and-end-pairs.md: 
 > 	can not read a block mapping entry; a multiline key may not be an implicit key at line 17, column 1:
    
    ^
  - python/python-playground-questions/combine-dictionaries/combine-dictionaries.md: 
 > 	can not read a block mapping entry; a multiline key may not be an implicit key at line 19, column 1:
    
    ^
  - python/python-playground-questions/dice-roll/dice-roll.md: 
 > 	can not read a block mapping entry; a multiline key may not be an implicit key at line 16, column 1:
    
    ^
  - python/python-playground-questions/harmonic-series/harmonic-series.md: 
 > 	can not read a block mapping entry; a multiline key may not be an implicit key at line 16, column 1:
    
    ^
  - python/python-playground-questions/remove-odd-numbers-from-list/remove-odd-numbers-from-list.md: 
 > 	can not read a block mapping entry; a multiline key may not be an implicit key at line 17, column 1:
    
    ^
  - python/python-playground-questions/smallest-list-element/smallest-list-element.md: 
 > 	can not read a block mapping entry; a multiline key may not be an implicit key at line 16, column 1:
    
    ^

**Comment by enki-hq** [comment]
Failed parsing files: 
  - python/python-playground-questions/adding-and-sorting-lists/adding-and-sorting-lists.md: 
 > 	can not read a block mapping entry; a multiline key may not be an implicit key at line 17, column 1:
    
    ^
  - python/python-playground-questions/beginning-and-end-pairs/beginning-and-end-pairs.md: 
 > 	can not read a block mapping entry; a multiline key may not be an implicit key at line 17, column 1:
    
    ^
  - python/python-playground-questions/combine-dictionaries/combine-dictionaries.md: 
 > 	can not read a block mapping entry; a multiline key may not be an implicit key at line 19, column 1:
    
    ^
  - python/python-playground-questions/dice-roll/dice-roll.md: 
 > 	can not read a block mapping entry; a multiline key may not be an implicit key at line 16, column 1:
    
    ^
  - python/python-playground-questions/harmonic-series/harmonic-series.md: 
 > 	can not read a block mapping entry; a multiline key may not be an implicit key at line 16, column 1:
    
    ^
  - python/python-playground-questions/remove-odd-numbers-from-list/remove-odd-numbers-from-list.md: 
 > 	can not read a block mapping entry; a multiline key may not be an implicit key at line 17, column 1:
    
    ^
  - python/python-playground-questions/smallest-list-element/smallest-list-element.md: 
 > 	can not read a block mapping entry; a multiline key may not be an implicit key at line 16, column 1:
    
    ^

**Comment by enki-hq** [comment]
Failed parsing files: 
  - python/python-playground-questions/beginning-and-end-pairs/beginning-and-end-pairs.md: 
 > 	can not read a block mapping entry; a multiline key may not be an implicit key at line 17, column 1:
    
    ^
  - python/python-playground-questions/combine-dictionaries/combine-dictionaries.md: 
 > 	can not read a block mapping entry; a multiline key may not be an implicit key at line 19, column 1:
    
    ^
  - python/python-playground-questions/dice-roll/dice-roll.md: 
 > 	can not read a block mapping entry; a multiline key may not be an implicit key at line 16, column 1:
    
    ^
  - python/python-playground-questions/harmonic-series/harmonic-series.md: 
 > 	can not read a block mapping entry; a multiline key may not be an implicit key at line 16, column 1:
    
    ^
  - python/python-playground-questions/remove-odd-numbers-from-list/remove-odd-numbers-from-list.md: 
 > 	can not read a block mapping entry; a multiline key may not be an implicit key at line 17, column 1:
    
    ^
  - python/python-playground-questions/smallest-list-element/smallest-list-element.md: 
 > 	can not read a block mapping entry; a multiline key may not be an implicit key at line 16, column 1:
    
    ^

**Comment by enki-hq** [comment]
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| even-or-odd | `setupCode`=undefined doesn't have the expected Object type |
| factorial-calculator | `setupCode`=undefined doesn't have the expected Object type |
| fibonacci-sequence | `setupCode`=undefined doesn't have the expected Object type |
| happy-birthday | `setupCode`=undefined doesn't have the expected Object type |
| miles-to-kilometres | `setupCode`=undefined doesn't have the expected Object type |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Insight previews:
- [ ] [enkidevs/curriculum/python/python-playground-questions/adding-and-sorting-lists/adding-and-sorting-lists.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/adding-and-sorting-lists/adding-and-sorting-lists.md?ref=c97cf1a6a79b88280411cd1f453de1d5d7d6b1d9)
- [ ] [enkidevs/curriculum/python/python-playground-questions/arithmetic-operation/arithmetic-operation.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/arithmetic-operation/arithmetic-operation.md?ref=c97cf1a6a79b88280411cd1f453de1d5d7d6b1d9)
- [ ] [enkidevs/curriculum/python/python-playground-questions/beginning-and-end-pairs/beginning-and-end-pairs.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/beginning-and-end-pairs/beginning-and-end-pairs.md?ref=c97cf1a6a79b88280411cd1f453de1d5d7d6b1d9)
- [ ] [enkidevs/curriculum/python/python-playground-questions/calculator-class/calculator-class.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/calculator-class/calculator-class.md?ref=c97cf1a6a79b88280411cd1f453de1d5d7d6b1d9)
- [ ] [enkidevs/curriculum/python/python-playground-questions/combine-dictionaries/combine-dictionaries.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/combine-dictionaries/combine-dictionaries.md?ref=c97cf1a6a79b88280411cd1f453de1d5d7d6b1d9)
- [ ] [enkidevs/curriculum/python/python-playground-questions/dice-roll/dice-roll.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/dice-roll/dice-roll.md?ref=c97cf1a6a79b88280411cd1f453de1d5d7d6b1d9)
- [ ] [enkidevs/curriculum/python/python-playground-questions/even-or-odd/even-or-odd.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/even-or-odd/even-or-odd.md?ref=c97cf1a6a79b88280411cd1f453de1d5d7d6b1d9)
- [ ] [enkidevs/curriculum/python/python-playground-questions/factorial-calculator/factorial-calculator.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/factorial-calculator/factorial-calculator.md?ref=c97cf1a6a79b88280411cd1f453de1d5d7d6b1d9)
- [ ] [enkidevs/curriculum/python/python-playground-questions/fibonacci-sequence/fibonacci-sequence.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/fibonacci-sequence/fibonacci-sequence.md?ref=c97cf1a6a79b88280411cd1f453de1d5d7d6b1d9)
- [ ] [enkidevs/curriculum/python/python-playground-questions/happy-birthday/happy-birthday.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/happy-birthday/happy-birthday.md?ref=c97cf1a6a79b88280411cd1f453de1d5d7d6b1d9)
- [ ] [enkidevs/curriculum/python/python-playground-questions/harmonic-series/harmonic-series.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/harmonic-series/harmonic-series.md?ref=c97cf1a6a79b88280411cd1f453de1d5d7d6b1d9)
- [ ] [enkidevs/curriculum/python/python-playground-questions/iterate-over-dict-values/iterate-over-dict-values.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/iterate-over-dict-values/iterate-over-dict-values.md?ref=c97cf1a6a79b88280411cd1f453de1d5d7d6b1d9)
- [ ] [enkidevs/curriculum/python/python-playground-questions/iterate-over-two-lists/iterate-over-two-lists.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/iterate-over-two-lists/iterate-over-two-lists.md?ref=c97cf1a6a79b88280411cd1f453de1d5d7d6b1d9)
- [ ] [enkidevs/curriculum/python/python-playground-questions/least-frequent-character/least-frequent-character.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/least-frequent-character/least-frequent-character.md?ref=c97cf1a6a79b88280411cd1f453de1d5d7d6b1d9)
- [ ] [enkidevs/curriculum/python/python-playground-questions/list-of-characters-to-string/list-of-characters-to-string.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/list-of-characters-to-string/list-of-characters-to-string.md?ref=c97cf1a6a79b88280411cd1f453de1d5d7d6b1d9)
- [ ] [enkidevs/curriculum/python/python-playground-questions/miles-to-kilometres/miles-to-kilometres.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/miles-to-kilometres/miles-to-kilometres.md?ref=c97cf1a6a79b88280411cd1f453de1d5d7d6b1d9)
- [ ] [enkidevs/curriculum/python/python-playground-questions/multiplication-table/multiplication-table.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/multiplication-table/multiplication-table.md?ref=c97cf1a6a79b88280411cd1f453de1d5d7d6b1d9)
- [ ] [enkidevs/curriculum/python/python-playground-questions/pascals-triangle/pascals-triangle.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/pascals-triangle/pascals-triangle.md?ref=c97cf1a6a79b88280411cd1f453de1d5d7d6b1d9)
- [ ] [enkidevs/curriculum/python/python-playground-questions/print-primes/print-primes.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/print-primes/print-primes.md?ref=c97cf1a6a79b88280411cd1f453de1d5d7d6b1d9)
- [ ] [enkidevs/curriculum/python/python-playground-questions/remove-duplicate-from-tuple/remove-duplicate-from-tuple.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/remove-duplicate-from-tuple/remove-duplicate-from-tuple.md?ref=c97cf1a6a79b88280411cd1f453de1d5d7d6b1d9)
- [ ] [enkidevs/curriculum/python/python-playground-questions/remove-odd-numbers-from-list/remove-odd-numbers-from-list.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/remove-odd-numbers-from-list/remove-odd-numbers-from-list.md?ref=c97cf1a6a79b88280411cd1f453de1d5d7d6b1d9)
- [ ] [enkidevs/curriculum/python/python-playground-questions/reverse-a-string/reverse-a-string.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/reverse-a-string/reverse-a-string.md?ref=c97cf1a6a79b88280411cd1f453de1d5d7d6b1d9)
- [ ] [enkidevs/curriculum/python/python-playground-questions/smallest-list-element/smallest-list-element.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/smallest-list-element/smallest-list-element.md?ref=c97cf1a6a79b88280411cd1f453de1d5d7d6b1d9)
- [ ] [enkidevs/curriculum/python/python-playground-questions/sort-lists-in-a-dict/sort-lists-in-a-dict.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/sort-lists-in-a-dict/sort-lists-in-a-dict.md?ref=c97cf1a6a79b88280411cd1f453de1d5d7d6b1d9)
- [ ] [enkidevs/curriculum/python/python-playground-questions/squared-dictionary-keys/squared-dictionary-keys.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/squared-dictionary-keys/squared-dictionary-keys.md?ref=c97cf1a6a79b88280411cd1f453de1d5d7d6b1d9)
- [ ] [enkidevs/curriculum/python/python-playground-questions/stopping-a-loop/stopping-a-loop.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/stopping-a-loop/stopping-a-loop.md?ref=c97cf1a6a79b88280411cd1f453de1d5d7d6b1d9)
- [ ] [enkidevs/curriculum/python/python-playground-questions/string-length/string-length.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/string-length/string-length.md?ref=c97cf1a6a79b88280411cd1f453de1d5d7d6b1d9)
- [ ] [enkidevs/curriculum/python/python-playground-questions/sum-and-product-of-two-tuples/sum-and-product-of-two-tuples.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/sum-and-product-of-two-tuples/sum-and-product-of-two-tuples.md?ref=c97cf1a6a79b88280411cd1f453de1d5d7d6b1d9)
- [ ] [enkidevs/curriculum/python/python-playground-questions/sum-items-in-dict/sum-items-in-dict.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/sum-items-in-dict/sum-items-in-dict.md?ref=c97cf1a6a79b88280411cd1f453de1d5d7d6b1d9)
- [ ] [enkidevs/curriculum/python/python-playground-questions/word-length/word-length.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-playground-questions/word-length/word-length.md?ref=c97cf1a6a79b88280411cd1f453de1d5d7d6b1d9)

**Comment by enki-hq** [comment]
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| arithmetic-operation | Insight slug `arithmetic-operation` is not unique among other files. |
| arithmetic-operation | Insight slug `arithmetic-operation` is not unique among other files. |
### Workout

| Workout Name | Error Message |
|:-:|:-:|
| arithmetic-operation | Workout slug `arithmetic-operation` isn't unique among other topic workouts. |
| arithmetic-operation | Workout slug `arithmetic-operation` isn't unique among other topic workouts. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| arithmetic-operation | Insight slug `arithmetic-operation` is not unique among other files. |
| arithmetic-operation | Insight slug `arithmetic-operation` is not unique among other files. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| arithmetic-operation | Insight slug `arithmetic-operation` is not unique among other files. |
| arithmetic-operation | Insight slug `arithmetic-operation` is not unique among other files. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| arithmetic-operation | Insight slug `arithmetic-operation` is not unique among other files. |
| arithmetic-operation | Insight slug `arithmetic-operation` is not unique among other files. |
| even-or-odd | Insight slug `even-or-odd` is not unique among other files. |
| even-or-odd | Insight slug `even-or-odd` is not unique among other files. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| even-or-odd | Insight slug `even-or-odd` is not unique among other files. |
| arithmetic-operation | Insight slug `arithmetic-operation` is not unique among other files. |
| arithmetic-operation | Insight slug `arithmetic-operation` is not unique among other files. |
| even-or-odd | Insight slug `even-or-odd` is not unique among other files. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| arithmetic-operation | Insight slug `arithmetic-operation` is not unique among other files. |
| even-or-odd | Insight slug `even-or-odd` is not unique among other files. |
| arithmetic-operation | Insight slug `arithmetic-operation` is not unique among other files. |
| even-or-odd | Insight slug `even-or-odd` is not unique among other files. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| arithmetic-operation | Insight slug `arithmetic-operation` is not unique among other files. |
| arithmetic-operation | Insight slug `arithmetic-operation` is not unique among other files. |
| even-or-odd | Insight slug `even-or-odd` is not unique among other files. |
| even-or-odd | Insight slug `even-or-odd` is not unique among other files. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| even-or-odd | Insight slug `even-or-odd` is not unique among other files. |
| even-or-odd | Insight slug `even-or-odd` is not unique among other files. |
### Workout

| Workout Name | Error Message |
|:-:|:-:|
| arithmetic-operation-exercise | One of the mentioned insights couldn't be found in this pull request or the database. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Workout

| Workout Name | Error Message |
|:-:|:-:|
| even-or-odd-exercise | One of the mentioned insights couldn't be found in this pull request or the database. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Course

| Course Name | Error Message |
|:-:|:-:|
| python-core | We couldn't find these workouts: `populate-a-tuple-exercise`. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Workout

| Workout Name | Error Message |
|:-:|:-:|
| day-of-the-week-function-exercise | One of the mentioned insights couldn't be found in this pull request or the database. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Workout

| Workout Name | Error Message |
|:-:|:-:|
| day-of-the-week-function-exercise | One of the mentioned insights couldn't be found in this pull request or the database. |
### Course

| Course Name | Error Message |
|:-:|:-:|
| python-core | We couldn't find these workouts: `day-of-the-week-functon-exercise`. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Workout

| Workout Name | Error Message |
|:-:|:-:|
| day-of-the-week-function-exercise | One of the mentioned insights couldn't be found in this pull request or the database. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Review by nem035 — APPROVED** [review]

**Review by kapnobatai137 — APPROVED** [review]

**Pull request merged**
