### PR TITLE
Rewrite and fix python insights

### PR DESCRIPTION
**Pull request by sebaraba**
## To Do:

Users have reviewed these insights as "WTF" at a much higher rate than average, there might be something wrong with them.

- [x] https://enkipro.com/#/insight/5595a231cad05d1d48753c36
- [x] https://enkipro.com/#/insight/56c1fb0c0b57870600f40686
- [x] https://enkipro.com/#/insight/56c1fb5bbb514406009a72af
- [x] https://enkipro.com/#/insight/56c204a80b57870600f4079f
- [x] https://enkipro.com/#/insight/56c20ba50b57870600f407da
- [x] https://enkipro.com/#/insight/56c20c4abb514406009a73d5
- [x] https://enkipro.com/#/insight/56c327540b57870600f40ffd
- [x] https://enkipro.com/#/insight/56c33cb00b57870600f41132
- [x] https://enkipro.com/#/insight/56c3482abb514406009a7d5a
- [x] https://enkipro.com/#/insight/56c353350b57870600f411e2
- [x] https://enkipro.com/#/insight/56c358ac0b57870600f4123b
- [x] https://enkipro.com/#/insight/56c49b37b6162b08008eeafa
- [x] https://enkipro.com/#/insight/56c5d0343e75da0600154a75
- [x] https://enkipro.com/#/insight/56c5e92bbc623a0600ff36ff
- [x] https://enkipro.com/#/insight/56c5ef3e3e75da0600154cea
- [x] https://enkipro.com/#/insight/56c746bf14cb9f0600463f5a
- [x] https://enkipro.com/#/insight/56c75b1edc39f90600d79c53
- [ ] https://enkipro.com/#/insight/56cb188311cc3c0600eda56b
- [x] https://enkipro.com/#/insight/56cb3a5a7e8e7206000f7a1b
- [x] https://enkipro.com/#/insight/57e27bbfdb57e48b5209bf1c
- [x] https://enkipro.com/#/insight/57e2909868234b910dfcffe8
- [x] https://enkipro.com/#/insight/57e3f69617c7c1e362b56eb3
- [x] https://enkipro.com/#/insight/57e3fbed17c7c1e362b570b9
- [x] https://enkipro.com/#/insight/57e4089e17c7c1e362b576bf
- [x] https://enkipro.com/#/insight/57e51fdda76cc0416671b147
- [x] https://enkipro.com/#/insight/57e53fdda76cc0416671be03
- [ ] https://enkipro.com/#/insight/57e551eaac7220686029083a
- [x] https://enkipro.com/#/insight/57e818e6711eb6cd6f9f2a0f
- [x] https://enkipro.com/#/insight/57e83a3852fd4b1910f85a49
- [x] https://enkipro.com/#/insight/57ea4602711eb6cd6f9ff04f
- [x] https://enkipro.com/#/insight/597770b33df507ef0ee20322
- [x] https://enkipro.com/#/insight/597770b33df507ef0ee20326
- [ ] https://enkipro.com/#/insight/597b2ea96a4af7e10ee3e81a
- [x] https://enkipro.com/#/insight/59970ecd9cd99d51111c4d8f
- [ ] https://enkipro.com/#/insight/59970ecd9cd99d51111c4da5
- [x] https://enkipro.com/#/insight/59970ecd9cd99d51111c4db1

### CODE REVIEW

**Comment by enki-hq** [comment]
bad indentation of a sequence entry at line 3, column 16:
      - [Read More]("https://docs.python.org/3.5/li ... 
                   ^

**Comment by enki-hq** [comment]
bad indentation of a sequence entry at line 3, column 16:
      - [Read More]("https://docs.python.org/3.5/li ... 
                   ^

**Comment by Loopiezlol** [comment]
@sebaraba this failed and when merging because of the links being broken in one (or more) insights

you'll need to fix that and retrigger changes to those **all** files (like add an empty space if nothing's wrong in it)

**Comment by enki-hq** [comment]
### Insight previews:
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/python/core/basic-file-manipulation/how-to-open-a-file-object.md?ref=55192f0efcf91b8abd3de217d3fe789115f5946c
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/python/core/basic-file-manipulation/other-operations-on-files.md?ref=55192f0efcf91b8abd3de217d3fe789115f5946c
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/python/core/console-and-operators/arithmetic-operators.md?ref=55192f0efcf91b8abd3de217d3fe789115f5946c
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/python/core/console-and-operators/execution-order-of-arithmetic-operators.md?ref=55192f0efcf91b8abd3de217d3fe789115f5946c
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/python/core/console-and-operators/indentation-and-commenting.md?ref=55192f0efcf91b8abd3de217d3fe789115f5946c
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/python/core/console-and-operators/printing-to-the-console.md?ref=55192f0efcf91b8abd3de217d3fe789115f5946c
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/python/core/fundamental-data-structures/dictionary-standard-mapping-type.md?ref=55192f0efcf91b8abd3de217d3fe789115f5946c
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/python/core/fundamental-data-structures/variables-and-types.md?ref=55192f0efcf91b8abd3de217d3fe789115f5946c
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/python/core/meet-python/python-2.md?ref=55192f0efcf91b8abd3de217d3fe789115f5946c
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/python/core/meet-python/python-hello-world.md?ref=55192f0efcf91b8abd3de217d3fe789115f5946c
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/python/core/meet-python/what-is-python.md?ref=55192f0efcf91b8abd3de217d3fe789115f5946c
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/python/core/meet-python/why-learn-python.md?ref=55192f0efcf91b8abd3de217d3fe789115f5946c
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/python/data-structures/advanced-queues/prioritize-your-queue.md?ref=55192f0efcf91b8abd3de217d3fe789115f5946c
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/python/data-structures/advanced-queues/queue-s-and-threads.md?ref=55192f0efcf91b8abd3de217d3fe789115f5946c
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/python/data-structures/advanced-queues/special-queue-methods.md?ref=55192f0efcf91b8abd3de217d3fe789115f5946c
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/python/data-structures/bits-bytes-hexadecimals/bytes-type.md?ref=55192f0efcf91b8abd3de217d3fe789115f5946c
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/python/data-structures/more-on-dictionaries/dictionary-view-objects.md?ref=55192f0efcf91b8abd3de217d3fe789115f5946c
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/python/data-structures/more-on-lists/del-statement-for-lists.md?ref=55192f0efcf91b8abd3de217d3fe789115f5946c
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/python/data-structures/more-on-lists/using-a-list-as-a-stack.md?ref=55192f0efcf91b8abd3de217d3fe789115f5946c
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/python/data-structures/recipes/parallel-sorting-of-lists.md?ref=55192f0efcf91b8abd3de217d3fe789115f5946c
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/python/functional-programming/iterators/the-itertools-module.md?ref=55192f0efcf91b8abd3de217d3fe789115f5946c

**Comment by enki-hq** [comment]
Failed parsing files: 
  - python/core/basic-file-manipulation/how-to-open-a-file-object.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - python/core/basic-file-manipulation/other-operations-on-files.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - python/core/console-and-operators/arithmetic-operators.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - python/core/console-and-operators/execution-order-of-arithmetic-operators.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - python/core/console-and-operators/indentation-and-commenting.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - python/core/console-and-operators/printing-to-the-console.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - python/core/fundamental-data-structures/dictionary-standard-mapping-type.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - python/core/fundamental-data-structures/variables-and-types.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - python/core/meet-python/python-2.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - python/core/meet-python/python-hello-world.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - python/core/meet-python/what-is-python.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - python/core/meet-python/why-learn-python.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - python/data-structures/advanced-queues/prioritize-your-queue.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - python/data-structures/advanced-queues/queue-s-and-threads.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - python/data-structures/advanced-queues/special-queue-methods.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - python/data-structures/bits-bytes-hexadecimals/bytes-type.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - python/data-structures/more-on-dictionaries/dictionary-view-objects.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - python/data-structures/more-on-lists/del-statement-for-lists.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - python/data-structures/more-on-lists/using-a-list-as-a-stack.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - python/data-structures/recipes/parallel-sorting-of-lists.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - python/functional-programming/iterators/the-itertools-module.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.

**Pull request merged**
