### PR TITLE
js node + npm standards

### PR DESCRIPTION
**Pull request by Loopiezlol**
This PR is meant to include all standards for the `node` and `npm` courses, taken from `standards-sections` branch.

---

### Node

- [x] The node manifest omits some (3) workouts in its sections ordering, although they exist within it's folder:
  - best-practices
  - code-style-recommendations
  - operational-vs-programmer-errors

In addition, there are some insights left without standards
- [x] all insights in best-practices
- [x] all insights in code-style-recommendations
- [x] all insights in express
- [x] all insights in express-ii
- [x] all insights in operational-vs-programmer-errors
- [x] from file-io workout:
  - async-file-write-in-node-js
  - synchronous-file-write-read-in-node-js
- [x] from web-servers workout:
  - basic-web-server-with-express
  - http-server-in-node

---

### npm

There is one insight missing standards:
  - [x] passing-through-command-line-arguments-in-npm-scripts

Also, there were two insights with added standards which weren't in a workout. This can't work with the content consumer, so I've added them to the `publishing` workout:
 - registry-user-accounts-for-npm
 - package-distribution-tags

### CODE REVIEW

**Comment by enki-hq** [comment]
### Insight previews:
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/node/error-handling/first-error-callbacks-in-node.md?ref=4f1cd8daf1599998ed7df55e850d95e1036dcd02
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/node/error-handling/handle-json-parse-error-in-node-js.md?ref=4f1cd8daf1599998ed7df55e850d95e1036dcd02
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/node/error-handling/try-catch-only-for-sync-code.md?ref=4f1cd8daf1599998ed7df55e850d95e1036dcd02
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/node/error-handling/uncaughtexception-listener-in-node-js.md?ref=4f1cd8daf1599998ed7df55e850d95e1036dcd02
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/node/error-handling/wrapping-errors-in-node-js-using-node-verror.md?ref=4f1cd8daf1599998ed7df55e850d95e1036dcd02
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/node/events/consuming-events.md?ref=4f1cd8daf1599998ed7df55e850d95e1036dcd02
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/node/events/handling-event-errors.md?ref=4f1cd8daf1599998ed7df55e850d95e1036dcd02
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/node/events/listening-to-events-just-once.md?ref=4f1cd8daf1599998ed7df55e850d95e1036dcd02
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/node/events/passing-arguments-to-listeners.md?ref=4f1cd8daf1599998ed7df55e850d95e1036dcd02
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/node/events/synchronous-event-delivery.md?ref=4f1cd8daf1599998ed7df55e850d95e1036dcd02
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/node/file-io/asynchronous-file-write-read-in-node-js.md?ref=4f1cd8daf1599998ed7df55e850d95e1036dcd02
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/node/intro-node/executing-programs-with-node.md?ref=4f1cd8daf1599998ed7df55e850d95e1036dcd02
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/node/intro-node/installing-node-js.md?ref=4f1cd8daf1599998ed7df55e850d95e1036dcd02
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/node/intro-node/npm-nodes-package-manager.md?ref=4f1cd8daf1599998ed7df55e850d95e1036dcd02
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/node/intro-node/the-repl-terminal.md?ref=4f1cd8daf1599998ed7df55e850d95e1036dcd02
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/node/intro-node/what-is-nodejs.md?ref=4f1cd8daf1599998ed7df55e850d95e1036dcd02
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/node/modules/exports-vs-module-exports-in-node.md?ref=4f1cd8daf1599998ed7df55e850d95e1036dcd02
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/node/modules/local-modules.md?ref=4f1cd8daf1599998ed7df55e850d95e1036dcd02
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/node/modules/module-patterns.md?ref=4f1cd8daf1599998ed7df55e850d95e1036dcd02
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/node/modules/requiring-and-exporting.md?ref=4f1cd8daf1599998ed7df55e850d95e1036dcd02
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/node/modules/what-are-node-modules.md?ref=4f1cd8daf1599998ed7df55e850d95e1036dcd02
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/node/patterns/factories-design-pattern.md?ref=4f1cd8daf1599998ed7df55e850d95e1036dcd02
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/node/patterns/global-objects-and-environment-variables-in-node.md?ref=4f1cd8daf1599998ed7df55e850d95e1036dcd02
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/node/patterns/middleware-pipeline-design-pattern.md?ref=4f1cd8daf1599998ed7df55e850d95e1036dcd02
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/node/patterns/process-nexttick-callback-pattern.md?ref=4f1cd8daf1599998ed7df55e850d95e1036dcd02
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/node/patterns/use-conventional-property-names-for-error-handling-in-node-js.md?ref=4f1cd8daf1599998ed7df55e850d95e1036dcd02
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/node/processes-clustering/clustering.md?ref=4f1cd8daf1599998ed7df55e850d95e1036dcd02
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/node/processes-clustering/manage-child-processes-in-node.md?ref=4f1cd8daf1599998ed7df55e850d95e1036dcd02
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/node/processes-clustering/master-and-worker-process-communication.md?ref=4f1cd8daf1599998ed7df55e850d95e1036dcd02
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/node/processes-clustering/master-processes-and-worker-processes.md?ref=4f1cd8daf1599998ed7df55e850d95e1036dcd02
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/node/processes-clustering/the-worker-class.md?ref=4f1cd8daf1599998ed7df55e850d95e1036dcd02
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/node/quirks/avoid-command-injection.md?ref=4f1cd8daf1599998ed7df55e850d95e1036dcd02
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/node/quirks/node-and-sudo.md?ref=4f1cd8daf1599998ed7df55e850d95e1036dcd02
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/node/quirks/node-os-module.md?ref=4f1cd8daf1599998ed7df55e850d95e1036dcd02
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/node/streams/chaining-readable-streams.md?ref=4f1cd8daf1599998ed7df55e850d95e1036dcd02
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/node/streams/piping-readable-streams.md?ref=4f1cd8daf1599998ed7df55e850d95e1036dcd02
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/node/streams/readable-streams.md?ref=4f1cd8daf1599998ed7df55e850d95e1036dcd02
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/node/streams/what-are-streams.md?ref=4f1cd8daf1599998ed7df55e850d95e1036dcd02
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/node/streams/writable-streams.md?ref=4f1cd8daf1599998ed7df55e850d95e1036dcd02
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/node/tools/automatic-compilation-for-node-with-nodemon.md?ref=4f1cd8daf1599998ed7df55e850d95e1036dcd02
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/node/tools/bulk-write-in-node-with-cork.md?ref=4f1cd8daf1599998ed7df55e850d95e1036dcd02
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/node/tools/how-to-debug-node-js.md?ref=4f1cd8daf1599998ed7df55e850d95e1036dcd02
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/node/tools/the-built-in-node-debugger.md?ref=4f1cd8daf1599998ed7df55e850d95e1036dcd02
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/node/web-servers/custom-node-repl-server.md?ref=4f1cd8daf1599998ed7df55e850d95e1036dcd02
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/node/web-servers/the-http-module-for-servers.md?ref=4f1cd8daf1599998ed7df55e850d95e1036dcd02

**Comment by enki-hq** [comment]
Rule course:sections failed for files: 
  - javascript/node/README.md

**Comment by lizTheDeveloper** [comment]
@Loopiezlol not sure why this is failing?

**Comment by enki-hq** [comment]
Rule course:sections failed for files: 
  - javascript/node/README.md

**Comment by Loopiezlol** [comment]
there was a bug I fixed https://github.com/sagelabs/monoenki/pull/3955
but idk why it's still failing. looking into it today

**Comment by enki-hq** [comment]
duplicated mapping key at line 22, column -49:
    standards:
    ^

**Comment by enki-hq** [comment]
duplicated mapping key at line 22, column -49:
    standards:
    ^

**Comment by enki-hq** [comment]
duplicated mapping key at line 22, column -49:
    standards:
    ^

**Comment by enki-hq** [comment]
Rule insight:levels failed for files: 
  - javascript/node/best-practices/process-env-performance.md

**Comment by enki-hq** [comment]
Rule insight:quiz failed for files: 
  - javascript/node/code-style-recommendations/styling-brackets.md

**Comment by enki-hq** [comment]
Rule course:sections failed for files: 
  - javascript/node/README.md

**Comment by lizTheDeveloper** [comment]
@Loopiezlol I am not sure why the sections field is failing on this file, but nowhere else

**Comment by enki-hq** [comment]
duplicated mapping key at line 25, column -49:
    links:
    ^

**Comment by enki-hq** [comment]
Must have exactly 1 headline but found 0 instead.

**Comment by enki-hq** [comment]
Rule insight:standards failed for files: 
  - javascript/node/intro-node/what-is-nodejs.md
  - javascript/node/modules/exports-vs-module-exports-in-node.md
  - javascript/node/modules/local-modules.md
  - javascript/node/modules/module-patterns.md
  - javascript/node/modules/requiring-and-exporting.md
  - javascript/node/modules/what-are-node-modules.md
  - javascript/node/patterns/factories-design-pattern.md
  - javascript/node/patterns/global-objects-and-environment-variables-in-node.md
  - javascript/node/patterns/middleware-pipeline-design-pattern.md
  - javascript/node/patterns/process-nexttick-callback-pattern.md
  - javascript/node/patterns/use-conventional-property-names-for-error-handling-in-node-js.md
  - javascript/node/processes-clustering/clustering.md
  - javascript/node/processes-clustering/manage-child-processes-in-node.md
  - javascript/node/processes-clustering/master-and-worker-process-communication.md
  - javascript/node/processes-clustering/master-processes-and-worker-processes.md
  - javascript/node/processes-clustering/the-worker-class.md
  - javascript/node/quirks/avoid-command-injection.md
  - javascript/node/quirks/node-and-sudo.md
  - javascript/node/quirks/node-os-module.md
  - javascript/node/streams/chaining-readable-streams.md
  - javascript/node/streams/piping-readable-streams.md
  - javascript/node/streams/readable-streams.md
  - javascript/node/streams/what-are-streams.md
  - javascript/node/streams/writable-streams.md
  - javascript/node/tools/automatic-compilation-for-node-with-nodemon.md
  - javascript/node/tools/bulk-write-in-node-with-cork.md
  - javascript/node/tools/how-to-debug-node-js.md
  - javascript/node/tools/the-built-in-node-debugger.md
  - javascript/node/web-servers/custom-node-repl-server.md
  - javascript/node/web-servers/the-http-module-for-servers.md
  - javascript/npm/features-i/available-binaries-for-scripting.md
  - javascript/npm/features-i/npm-scripting.md
  - javascript/npm/features-i/npm-variables.md
  - javascript/npm/features-i/remote-scripts.md
  - javascript/npm/features-i/scripts-lifecycle.md
  - javascript/npm/features-ii/abbreviate-commands-in-npm.md
  - javascript/npm/features-ii/environmental-variables-and-flags-for-npm.md
  - javascript/npm/features-ii/npm-verifies-sha1-hashes-of-packages.md
  - javascript/npm/features-ii/optionaldependencies-in-npm.md
  - javascript/npm/intro-npm/package-json.md
  - javascript/npm/intro-npm/semantic-versioning.md
  - javascript/npm/intro-npm/setting-up-npm.md
  - javascript/npm/intro-npm/what-is-npm.md
  - javascript/npm/intro-npm/why-use-npm.md
  - javascript/npm/packages-modules/dependencies.md
  - javascript/npm/packages-modules/deprecated-peer-dependencies.md
  - javascript/npm/packages-modules/how-npm3-handles-dependencies.md
  - javascript/npm/packages-modules/packages-vs-modules.md
  - javascript/npm/packages-modules/private-packages.md
  - javascript/npm/publishing/check-data-about-a-package.md
  - javascript/npm/publishing/creating-a-node-module.md
  - javascript/npm/publishing/how-to-publish-your-own-packages.md
  - javascript/npm/publishing/package-distribution-tags.md
  - javascript/npm/publishing/prepare-your-module-for-publishing.md
  - javascript/npm/publishing/registry-user-accounts-for-npm.md
  - javascript/npm/publishing/tests.md
  - javascript/npm/tools-i/bump-package-version-in-npm.md
  - javascript/npm/tools-i/deprecate-npm-packages.md
  - javascript/npm/tools-i/lock-down-dependency-versions-by-shrinkwrapping.md
  - javascript/npm/tools-i/manage-local-node-modules-with-npm-link.md
  - javascript/npm/tools-i/manipulate-npm-packages-cache.md

**Comment by enki-hq** [comment]
Rule course:sections failed for files: 
  - javascript/node/README.md

**Comment by enki-hq** [comment]
Rule insight:standards failed for files: 
  - javascript/node/modules/exports-vs-module-exports-in-node.md
  - javascript/node/modules/local-modules.md
  - javascript/node/modules/module-patterns.md
  - javascript/node/modules/requiring-and-exporting.md
  - javascript/node/modules/what-are-node-modules.md
  - javascript/node/patterns/factories-design-pattern.md
  - javascript/node/patterns/global-objects-and-environment-variables-in-node.md
  - javascript/node/patterns/middleware-pipeline-design-pattern.md
  - javascript/node/patterns/process-nexttick-callback-pattern.md
  - javascript/node/patterns/use-conventional-property-names-for-error-handling-in-node-js.md
  - javascript/node/processes-clustering/clustering.md
  - javascript/node/processes-clustering/manage-child-processes-in-node.md
  - javascript/node/processes-clustering/master-and-worker-process-communication.md
  - javascript/node/processes-clustering/master-processes-and-worker-processes.md
  - javascript/node/processes-clustering/the-worker-class.md
  - javascript/node/quirks/avoid-command-injection.md
  - javascript/node/quirks/node-and-sudo.md
  - javascript/node/quirks/node-os-module.md
  - javascript/node/streams/chaining-readable-streams.md
  - javascript/node/streams/piping-readable-streams.md
  - javascript/node/streams/readable-streams.md
  - javascript/node/streams/what-are-streams.md
  - javascript/node/streams/writable-streams.md
  - javascript/node/tools/automatic-compilation-for-node-with-nodemon.md
  - javascript/node/tools/bulk-write-in-node-with-cork.md
  - javascript/node/tools/how-to-debug-node-js.md
  - javascript/node/tools/the-built-in-node-debugger.md
  - javascript/node/web-servers/custom-node-repl-server.md
  - javascript/node/web-servers/the-http-module-for-servers.md
  - javascript/npm/features-i/available-binaries-for-scripting.md
  - javascript/npm/features-i/npm-scripting.md
  - javascript/npm/features-i/npm-variables.md
  - javascript/npm/features-i/remote-scripts.md
  - javascript/npm/features-i/scripts-lifecycle.md
  - javascript/npm/features-ii/abbreviate-commands-in-npm.md
  - javascript/npm/features-ii/environmental-variables-and-flags-for-npm.md
  - javascript/npm/features-ii/npm-verifies-sha1-hashes-of-packages.md
  - javascript/npm/features-ii/optionaldependencies-in-npm.md
  - javascript/npm/intro-npm/package-json.md
  - javascript/npm/intro-npm/semantic-versioning.md
  - javascript/npm/intro-npm/setting-up-npm.md
  - javascript/npm/intro-npm/what-is-npm.md
  - javascript/npm/intro-npm/why-use-npm.md
  - javascript/npm/packages-modules/dependencies.md
  - javascript/npm/packages-modules/deprecated-peer-dependencies.md
  - javascript/npm/packages-modules/how-npm3-handles-dependencies.md
  - javascript/npm/packages-modules/packages-vs-modules.md
  - javascript/npm/packages-modules/private-packages.md
  - javascript/npm/publishing/check-data-about-a-package.md
  - javascript/npm/publishing/creating-a-node-module.md
  - javascript/npm/publishing/how-to-publish-your-own-packages.md
  - javascript/npm/publishing/package-distribution-tags.md
  - javascript/npm/publishing/prepare-your-module-for-publishing.md
  - javascript/npm/publishing/registry-user-accounts-for-npm.md
  - javascript/npm/publishing/tests.md
  - javascript/npm/tools-i/bump-package-version-in-npm.md
  - javascript/npm/tools-i/deprecate-npm-packages.md
  - javascript/npm/tools-i/lock-down-dependency-versions-by-shrinkwrapping.md
  - javascript/npm/tools-i/manage-local-node-modules-with-npm-link.md
  - javascript/npm/tools-i/manipulate-npm-packages-cache.md

**Comment by enki-hq** [comment]
Rule course:sections failed for files: 
  - javascript/node/README.md

**Comment by enki-hq** [comment]
Rule insight:standards failed for files: 
  - javascript/node/modules/exports-vs-module-exports-in-node.md
  - javascript/node/modules/local-modules.md
  - javascript/node/modules/module-patterns.md
  - javascript/node/modules/requiring-and-exporting.md
  - javascript/node/modules/what-are-node-modules.md
  - javascript/node/patterns/factories-design-pattern.md
  - javascript/node/patterns/global-objects-and-environment-variables-in-node.md
  - javascript/node/patterns/middleware-pipeline-design-pattern.md
  - javascript/node/patterns/process-nexttick-callback-pattern.md
  - javascript/node/patterns/use-conventional-property-names-for-error-handling-in-node-js.md
  - javascript/node/processes-clustering/clustering.md
  - javascript/node/processes-clustering/manage-child-processes-in-node.md
  - javascript/node/processes-clustering/master-and-worker-process-communication.md
  - javascript/node/processes-clustering/master-processes-and-worker-processes.md
  - javascript/node/processes-clustering/the-worker-class.md
  - javascript/node/quirks/avoid-command-injection.md
  - javascript/node/quirks/node-and-sudo.md
  - javascript/node/quirks/node-os-module.md
  - javascript/node/streams/chaining-readable-streams.md
  - javascript/node/streams/piping-readable-streams.md
  - javascript/node/streams/readable-streams.md
  - javascript/node/streams/what-are-streams.md
  - javascript/node/streams/writable-streams.md
  - javascript/node/tools/automatic-compilation-for-node-with-nodemon.md
  - javascript/node/tools/bulk-write-in-node-with-cork.md
  - javascript/node/tools/how-to-debug-node-js.md
  - javascript/node/tools/the-built-in-node-debugger.md
  - javascript/node/web-servers/custom-node-repl-server.md
  - javascript/node/web-servers/the-http-module-for-servers.md
  - javascript/npm/features-i/available-binaries-for-scripting.md
  - javascript/npm/features-i/npm-scripting.md
  - javascript/npm/features-i/npm-variables.md
  - javascript/npm/features-i/remote-scripts.md
  - javascript/npm/features-i/scripts-lifecycle.md
  - javascript/npm/features-ii/abbreviate-commands-in-npm.md
  - javascript/npm/features-ii/environmental-variables-and-flags-for-npm.md
  - javascript/npm/features-ii/npm-verifies-sha1-hashes-of-packages.md
  - javascript/npm/features-ii/optionaldependencies-in-npm.md
  - javascript/npm/intro-npm/package-json.md
  - javascript/npm/intro-npm/semantic-versioning.md
  - javascript/npm/intro-npm/setting-up-npm.md
  - javascript/npm/intro-npm/what-is-npm.md
  - javascript/npm/intro-npm/why-use-npm.md
  - javascript/npm/packages-modules/dependencies.md
  - javascript/npm/packages-modules/deprecated-peer-dependencies.md
  - javascript/npm/packages-modules/how-npm3-handles-dependencies.md
  - javascript/npm/packages-modules/packages-vs-modules.md
  - javascript/npm/packages-modules/private-packages.md
  - javascript/npm/publishing/check-data-about-a-package.md
  - javascript/npm/publishing/creating-a-node-module.md
  - javascript/npm/publishing/how-to-publish-your-own-packages.md
  - javascript/npm/publishing/package-distribution-tags.md
  - javascript/npm/publishing/prepare-your-module-for-publishing.md
  - javascript/npm/publishing/registry-user-accounts-for-npm.md
  - javascript/npm/publishing/tests.md
  - javascript/npm/tools-i/bump-package-version-in-npm.md
  - javascript/npm/tools-i/deprecate-npm-packages.md
  - javascript/npm/tools-i/lock-down-dependency-versions-by-shrinkwrapping.md
  - javascript/npm/tools-i/manage-local-node-modules-with-npm-link.md
  - javascript/npm/tools-i/manipulate-npm-packages-cache.md

**Comment by Loopiezlol** [comment]
merged with develop and fixed the sections thing

the problem now is that a lot of standards don't have objectives

**Comment by enki-hq** [comment]
Rule insight:standards failed for files: 
  - javascript/node/modules/exports-vs-module-exports-in-node.md
  - javascript/node/modules/local-modules.md
  - javascript/node/modules/module-patterns.md
  - javascript/node/modules/requiring-and-exporting.md
  - javascript/node/modules/what-are-node-modules.md
  - javascript/node/patterns/factories-design-pattern.md
  - javascript/node/patterns/global-objects-and-environment-variables-in-node.md
  - javascript/node/patterns/middleware-pipeline-design-pattern.md
  - javascript/node/patterns/process-nexttick-callback-pattern.md
  - javascript/node/patterns/use-conventional-property-names-for-error-handling-in-node-js.md
  - javascript/node/processes-clustering/clustering.md
  - javascript/node/processes-clustering/manage-child-processes-in-node.md
  - javascript/node/processes-clustering/master-and-worker-process-communication.md
  - javascript/node/processes-clustering/master-processes-and-worker-processes.md
  - javascript/node/processes-clustering/the-worker-class.md
  - javascript/node/quirks/avoid-command-injection.md
  - javascript/node/quirks/node-and-sudo.md
  - javascript/node/quirks/node-os-module.md
  - javascript/node/streams/chaining-readable-streams.md
  - javascript/node/streams/piping-readable-streams.md
  - javascript/node/streams/readable-streams.md
  - javascript/node/streams/what-are-streams.md
  - javascript/node/streams/writable-streams.md
  - javascript/node/tools/automatic-compilation-for-node-with-nodemon.md
  - javascript/node/tools/bulk-write-in-node-with-cork.md
  - javascript/node/tools/how-to-debug-node-js.md
  - javascript/node/tools/the-built-in-node-debugger.md
  - javascript/node/web-servers/custom-node-repl-server.md
  - javascript/node/web-servers/the-http-module-for-servers.md
  - javascript/npm/features-i/available-binaries-for-scripting.md
  - javascript/npm/features-i/npm-scripting.md
  - javascript/npm/features-i/npm-variables.md
  - javascript/npm/features-i/remote-scripts.md
  - javascript/npm/features-i/scripts-lifecycle.md
  - javascript/npm/features-ii/abbreviate-commands-in-npm.md
  - javascript/npm/features-ii/environmental-variables-and-flags-for-npm.md
  - javascript/npm/features-ii/npm-verifies-sha1-hashes-of-packages.md
  - javascript/npm/features-ii/optionaldependencies-in-npm.md
  - javascript/npm/intro-npm/package-json.md
  - javascript/npm/intro-npm/semantic-versioning.md
  - javascript/npm/intro-npm/setting-up-npm.md
  - javascript/npm/intro-npm/what-is-npm.md
  - javascript/npm/intro-npm/why-use-npm.md
  - javascript/npm/packages-modules/dependencies.md
  - javascript/npm/packages-modules/deprecated-peer-dependencies.md
  - javascript/npm/packages-modules/how-npm3-handles-dependencies.md
  - javascript/npm/packages-modules/packages-vs-modules.md
  - javascript/npm/packages-modules/private-packages.md
  - javascript/npm/publishing/check-data-about-a-package.md
  - javascript/npm/publishing/creating-a-node-module.md
  - javascript/npm/publishing/how-to-publish-your-own-packages.md
  - javascript/npm/publishing/package-distribution-tags.md
  - javascript/npm/publishing/prepare-your-module-for-publishing.md
  - javascript/npm/publishing/registry-user-accounts-for-npm.md
  - javascript/npm/publishing/tests.md
  - javascript/npm/tools-i/bump-package-version-in-npm.md
  - javascript/npm/tools-i/deprecate-npm-packages.md
  - javascript/npm/tools-i/lock-down-dependency-versions-by-shrinkwrapping.md
  - javascript/npm/tools-i/manage-local-node-modules-with-npm-link.md
  - javascript/npm/tools-i/manipulate-npm-packages-cache.md

**Comment by enki-hq** [comment]
Failed parsing files: 
  - javascript/node/modules/what-are-node-modules.md: 
 > Must have exactly 1 headline but found 2 instead.
  - javascript/npm/tools-i/manipulate-npm-packages-cache.md: 
 > Must have exactly 1 headline but found 2 instead.

**Comment by enki-hq** [comment]
Rule insight:standards failed for files: 
  - javascript/node/patterns/global-objects-and-environment-variables-in-node.md
  - javascript/node/patterns/process-nexttick-callback-pattern.md
  - javascript/node/patterns/use-conventional-property-names-for-error-handling-in-node-js.md
  - javascript/node/processes-clustering/clustering.md
  - javascript/node/processes-clustering/manage-child-processes-in-node.md
  - javascript/node/processes-clustering/master-and-worker-process-communication.md
  - javascript/node/processes-clustering/master-processes-and-worker-processes.md
  - javascript/npm/packages-modules/private-packages.md
  - javascript/npm/publishing/registry-user-accounts-for-npm.md

**Comment by enki-hq** [comment]
Rule insight:standards failed for files: 
  - javascript/npm/publishing/registry-user-accounts-for-npm.md

**Pull request merged**
