### PR TITLE
SQL-DQL-exercises

### PR DESCRIPTION
**Pull request by sebaraba**
## Done:
- [x] Aggregate Queries on single table;
- [x] Aggregate Queries on multiple tables;
- [x] Basic Queries;
- [x] Joins;
- [x] Read from multiple tables;
- [x] Write, Insert, Delete;

### CODE REVIEW

**Comment by enki-hq** [comment]
can not read a block mapping entry; a multiline key may not be an implicit key at line 24, column 1:
    ---
    ^

**Comment by enki-hq** [comment]
can not read a block mapping entry; a multiline key may not be an implicit key at line 24, column 1:
    ---
    ^

**Comment by lizTheDeveloper** [comment]
hey @sebaraba can you fix the yaml on these

**Comment by enki-hq** [comment]
can not read a block mapping entry; a multiline key may not be an implicit key at line 26, column 1:
    ---
    ^

**Comment by enki-hq** [comment]
can not read a block mapping entry; a multiline key may not be an implicit key at line 26, column 1:
    ---
    ^

**Comment by enki-hq** [comment]
can not read a block mapping entry; a multiline key may not be an implicit key at line 26, column 1:
    ---
    ^

**Comment by enki-hq** [comment]
can not read a block mapping entry; a multiline key may not be an implicit key at line 26, column 1:
    ---
    ^

**Comment by enki-hq** [comment]
can not read a block mapping entry; a multiline key may not be an implicit key at line 26, column 1:
    ---
    ^

**Comment by enki-hq** [comment]
can not read a block mapping entry; a multiline key may not be an implicit key at line 26, column 1:
    ---
    ^

**Comment by lizTheDeveloper** [comment]
@sebaraba can you update these to the latest format

**Comment by lizTheDeveloper** [comment]
Merged into exercises

**Pull request closed without merging**
