### PR TITLE
Fix python schedule-events-with-sched practice

### PR DESCRIPTION
**Pull request by aschult5**
sched.scheduler should take time.time and time.sleep as arguments, as is done in the insight.

Add missing scheduler.run call.

Clarify that the scheduler will enter print, not "second" which is actually the argument passed to print.

### CODE REVIEW

**Comment by enki-hq** [comment]
### Insight previews:
- [ ] https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/python/core/utilities-i/schedule-events-with-sched.md?ref=3f42205c9f5c47e7c0d91d73f6386db66ba55043

**Comment by aschult5** [comment]
I could not find documentation on how to make the corresponding change for answer checking. I'm happy to make that change if someone guides me.

**Comment by ryanwarsaw** [comment]
Hey @aschult5 yeah that's kind of confusing, here's an example of how it works for multi-choice questions:

Each option in the question is represented by a `???`, we list the options as a bulleted list. The first `???` is associated with the first bullet of the list and so forth. Any excess bullets are incorrect answers. Our app parses the bullet list and randomizes the options, but remembers the order so we know which one is correct. 

For example; let's say it's a multi-choice question about a JavaScript function that logs something to the console:

```js
??? myFunction() {
  console.???("Hello, World!");
}
```

The bullet list would be: 

```
 - function
 - log
 ... wrong answers we will mix in before displaying to the user
```

Hope that helps, let me know if you have any questions :)

**Comment by ryanwarsaw** [comment]
:100: Works like a charm! Great work, thank you for the PR :)

**Pull request merged**
