### PR TITLE
Update multi-line-string-variables.md

### PR DESCRIPTION
**Pull request by Stefan-Stojanovic**
fix back tick not displaying as a character in the pq

### CODE REVIEW

**Comment by enki-hq** [comment]
### Insight previews:
- [ ] [enkidevs/curriculum/javascript/core/strings-ii/multi-line-string-variables.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/javascript/core/strings-ii/multi-line-string-variables.md?ref=a3ba02bdac5383bc16cde8a7b8c9947fbba3aef6)

**Comment by kapnobatai137** [comment]
can you test this in spider to see how ti looks? @Stefan-Stojanovic

**Comment by Stefan-Stojanovic** [comment]
It still doesn't work.

I've tried all of these within the app and none display the backtick:

* ``Backticks (`)``
*  `Backticks (\`)`
*  `Backticks (`)`
* ``Backticks (\`)``
* ``Backticks (`)``
*  `Backticks (/`)`
*  `Backticks (`)`
* ``Backticks (/`)``
* Backticks (/`)
* Backticks(`)

**Comment by kapnobatai137** [comment]
There doesn't seem to be any easy way out of this so we'll have to just modify the content. We can just have it say `Backticks`  and I think that would be enough.

**Comment by kapnobatai137** [comment]
image

image

for the pq, syntax highlighting kinda gives it away. what do you think @nem035 ?

**Comment by nem035** [comment]
Yeah, syntax highlighting kind of shows the answer @kapnobatai137.

Maybe we can say:

````md
Which characters are used to enclose a multi-line string?

```js
"" // A
```

```js
`` // B
```
````

**Comment by kapnobatai137** [comment]
image

**Pull request merged**
