### PR TITLE
SQL - Building Queries

### PR DESCRIPTION
**Pull request by kapnobatai137**
- discussion insight for the Building Queries Workout

### CODE REVIEW

**Comment by enki-hq** [comment]
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| building-queries-discussion-insight | <ul><li>`Playground` pointing to `https://student.enkicamp.com/public/playground?jsonUrl=https%3A%2F%2Fgist.githubusercontent.com%2Fkapnobatai137%2F2b85df43ad3d134112160d24aa78ad5a%2Fraw%2F9b4aab60d58fbe17e783458192629d83c6eb53aa%2Fsql-building-queries-discussion-insight.json` is broken because `HTTP_404`</li></ul> |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| building-queries-discussion-insight | <ul><li>`Playground` pointing to `https://student.enkicamp.com/public/playground?jsonUrl=https%3A%2F%2Fgist.githubusercontent.com%2Fkapnobatai137%2F2b85df43ad3d134112160d24aa78ad5a%2Fraw%2F9b4aab60d58fbe17e783458192629d83c6eb53aa%2Fsql-building-queries-discussion-insight.json` is broken because `HTTP_404`</li></ul> |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| building-queries-discussion-insight | <ul><li>`Playground` pointing to `https://student.enkicamp.com/public/playground?jsonUrl=https%3A%2F%2Fgist.githubusercontent.com%2Fkapnobatai137%2F2b85df43ad3d134112160d24aa78ad5a%2Fraw%2F9b4aab60d58fbe17e783458192629d83c6eb53aa%2Fsql-building-queries-discussion-insight.json` is broken because `HTTP_404`</li></ul> |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Review by Stefan-Stojanovic — DISMISSED** [review]
Looking good imo

**Comment by enki-hq** [comment]
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| building-queries-discussion-insight | <ul><li>`Playground` pointing to `https://learner.enkicamp.com/public/playground?jsonUrl=https%3A%2F%2Fgist.githubusercontent.com%2Fkapnobatai137%2F2b85df43ad3d134112160d24aa78ad5a%2Fraw%2F9b4aab60d58fbe17e783458192629d83c6eb53aa%2Fsql-building-queries-discussion-insight.json` is broken because `HTTP_404`</li></ul> |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Pull request merged**
