### PR TITLE
Update lists workout

### PR DESCRIPTION
**Pull request by Stefan-Stojanovic**

### CODE REVIEW

**Comment by enki-hq** [comment]
### Insight previews:
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/Web/HTML/lists/unordered-lists.md?ref=c093700fef3e661d146625782fd8a440ae825a37

**Comment by enki-hq** [comment]
Rule insight:quiz failed for files: 
  - Web/HTML/lists/nested-lists.md

**Comment by enki-hq** [comment]
Rule insight:quiz failed for files: 
  - Web/HTML/lists/nested-lists.md

**Comment by enki-hq** [comment]
Rule insight:quiz failed for files: 
  - Web/HTML/lists/nested-lists.md

**Comment by enki-hq** [comment]
Rule insight:quiz failed for files: 
  - Web/HTML/lists/nested-lists.md

**Comment by enki-hq** [comment]
Rule insight:quiz failed for files: 
  - Web/HTML/lists/list-orders.md
  - Web/HTML/lists/nested-lists.md

**Comment by enki-hq** [comment]
Rule insight:quiz failed for files: 
  - Web/HTML/lists/nested-lists.md

**Comment by enki-hq** [comment]
Rule insight:code-width failed for files: 
  - Web/HTML/tables/colgroup-and-col.md

**Comment by lizTheDeveloper** [comment]
https://github.com/enkidevs/curriculum/pull/840

**Pull request closed without merging**
