### PR TITLE
Update the-not-operator.md

### PR DESCRIPTION
**Pull request by Stefan-Stojanovic**
Remove the mention of the `is` operators as the `is` operator insight is further down the topic

Add removed information about `is` to the `is operator insight`

### CODE REVIEW

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Insight previews:
- [ ] [enkidevs/curriculum/python/python-core/control-flow-ii/the-not-operator.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/python/python-core/control-flow-ii/the-not-operator.md?ref=c2d9b79f357052d2c1fc23d336cb80d087408ea0)
- [ ] [enkidevs/curriculum/python/python-core/memory-allocation/the-is-operator.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/python/python-core/memory-allocation/the-is-operator.md?ref=c2d9b79f357052d2c1fc23d336cb80d087408ea0)

**Review by kapnobatai137 — DISMISSED** [review]

**Pull request merged**
