### PR TITLE
Security OSI Course / Topic Creation

### PR DESCRIPTION
**Pull request by lizTheDeveloper**
For those of you anxiously awaiting our first security course- we're working on merging this, there are some backend changes that need to be made first. Should launch before next week!

### CODE REVIEW

**Comment by enki-hq** [comment]
bad indentation of a sequence entry at line 3, column 21:
      - [SANS Institute](https://www.sans.org/reading-ro ... 
                        ^

**Comment by enki-hq** [comment]
Invalid section title on line 29: Hi, great site. Too bad I hacked it!<script>window.location="http://www.mysite.com/"</script>

**Comment by enki-hq** [comment]
bad indentation of a sequence entry at line 3, column 21:
      - [SANS Institute](https://www.sans.org/reading-ro ... 
                        ^

**Comment by enki-hq** [comment]
bad indentation of a sequence entry at line 3, column 7:
      - ''[SANS Institute](https://www.san ... 
          ^

**Comment by enki-hq** [comment]
Invalid section title on line 24: # Content

**Comment by enki-hq** [comment]
bad indentation of a sequence entry at line 5, column 30:
      - [Common Ports Cheatsheet](http://packetlife.net/media/lib ... 
                                 ^

**Comment by Loopiezlol** [comment]
removed the standards for now, they won't be parsed by the content consumer atm

to restore them  check out at `f71f12edee10bd4cbc749fd5f8c385ebaa7cd666` and copy them from there

**Pull request merged**
