### PR TITLE
Replace old note format with emoji one Comp Sci

### PR DESCRIPTION
**Pull request by Stefan-Stojanovic**

### CODE REVIEW

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Insight previews:
- [ ] [enkidevs/curriculum/comp-sci/data-structures-and-algorithms/binary-search-tree/verifying-a-binary-search-tree.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/comp-sci/data-structures-and-algorithms/binary-search-tree/verifying-a-binary-search-tree.md?ref=cf1cf83aa4bc28f4ee14395fffc3957d72d93511)
- [ ] [enkidevs/curriculum/comp-sci/data-structures-and-algorithms/intro-data-structures/the-linked-list-data-structure.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/comp-sci/data-structures-and-algorithms/intro-data-structures/the-linked-list-data-structure.md?ref=cf1cf83aa4bc28f4ee14395fffc3957d72d93511)
- [ ] [enkidevs/curriculum/comp-sci/data-structures-and-algorithms/intro-graphs/the-components-of-a-graph-ii.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/comp-sci/data-structures-and-algorithms/intro-graphs/the-components-of-a-graph-ii.md?ref=cf1cf83aa4bc28f4ee14395fffc3957d72d93511)
- [ ] [enkidevs/curriculum/comp-sci/data-structures-and-algorithms/intro-graphs/the-components-of-a-graph.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/comp-sci/data-structures-and-algorithms/intro-graphs/the-components-of-a-graph.md?ref=cf1cf83aa4bc28f4ee14395fffc3957d72d93511)

**Review by nem035 — DISMISSED** [review]

**Review by kapnobatai137 — APPROVED** [review]

**Pull request merged**
