### PR TITLE
Update JS syntax

### PR DESCRIPTION
**Pull request by Stefan-Stojanovic**
change `var` - > `let` to all applicable insights

Add missing back ticks for code blocks as well as the correct name

### CODE REVIEW

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Review by nem035 — DISMISSED** [review]

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Insight previews:
- [ ] [enkidevs/curriculum/javascript/browser-apis/dummy-workout/window-sessionstorage.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/browser-apis/dummy-workout/window-sessionstorage.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/browser-apis/intro-browser-js/modify-elements.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/browser-apis/intro-browser-js/modify-elements.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/browser-apis/intro-browser-js/modifying-the-body.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/browser-apis/intro-browser-js/modifying-the-body.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/browser-apis/measuring-performance/high-resolution-time-api.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/browser-apis/measuring-performance/high-resolution-time-api.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/browser-apis/measuring-performance/progress-event.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/browser-apis/measuring-performance/progress-event.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/browser-apis/navigation/form-a-url-from-its-parts.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/browser-apis/navigation/form-a-url-from-its-parts.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/browser-apis/reading-writing/filereader-readasarraybuffer.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/browser-apis/reading-writing/filereader-readasarraybuffer.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/browser-apis/reading-writing/window-localstorage.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/browser-apis/reading-writing/window-localstorage.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/browser-apis/toolbox-i/battery-api.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/browser-apis/toolbox-i/battery-api.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/browser-apis/toolbox-i/geolocation.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/browser-apis/toolbox-i/geolocation.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/browser-apis/toolbox-ii/fetch-api.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/browser-apis/toolbox-ii/fetch-api.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/ecmascript-2015/array-updates/array-copywithin.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/ecmascript-2015/array-updates/array-copywithin.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/ecmascript-2015/classes-modules/classes-and-constructor.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/ecmascript-2015/classes-modules/classes-and-constructor.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/ecmascript-2015/classes-modules/extends-super-and-static.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/ecmascript-2015/classes-modules/extends-super-and-static.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/ecmascript-2015/destructuring/destructuring-part-3.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/ecmascript-2015/destructuring/destructuring-part-3.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/ecmascript-2015/dummy-workout/array-extensions-part-1.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/ecmascript-2015/dummy-workout/array-extensions-part-1.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/ecmascript-2015/dummy-workout/computed-properties.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/ecmascript-2015/dummy-workout/computed-properties.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/ecmascript-2015/dummy-workout/computed-property-names-in-object-literals.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/ecmascript-2015/dummy-workout/computed-property-names-in-object-literals.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/ecmascript-2015/dummy-workout/es6-arrow-functions.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/ecmascript-2015/dummy-workout/es6-arrow-functions.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/ecmascript-2015/dummy-workout/handling-modules.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/ecmascript-2015/dummy-workout/handling-modules.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/ecmascript-2015/dummy-workout/hoisting-with-var-and-let.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/ecmascript-2015/dummy-workout/hoisting-with-var-and-let.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/ecmascript-2015/dummy-workout/proxies-in-es6.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/ecmascript-2015/dummy-workout/proxies-in-es6.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/ecmascript-2015/dummy-workout/proxies.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/ecmascript-2015/dummy-workout/proxies.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/ecmascript-2015/dummy-workout/revokable-proxies-and-usages.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/ecmascript-2015/dummy-workout/revokable-proxies-and-usages.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/ecmascript-2015/dummy-workout/tagged-template-literals-3.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/ecmascript-2015/dummy-workout/tagged-template-literals-3.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/ecmascript-2015/dummy-workout/using-maps.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/ecmascript-2015/dummy-workout/using-maps.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/ecmascript-2015/generators-proxy/passing-values-to-generators.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/ecmascript-2015/generators-proxy/passing-values-to-generators.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/ecmascript-2015/generators-proxy/yield.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/ecmascript-2015/generators-proxy/yield.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/ecmascript-2015/intro-ecmascript/const-part-1.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/ecmascript-2015/intro-ecmascript/const-part-1.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/ecmascript-2015/intro-ecmascript/const-part-2.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/ecmascript-2015/intro-ecmascript/const-part-2.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/ecmascript-2015/iterators-generators/introducing-generators.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/ecmascript-2015/iterators-generators/introducing-generators.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/ecmascript-2015/promises/chaining-promises.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/ecmascript-2015/promises/chaining-promises.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/ecmascript-2015/promises/introducing-promises.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/ecmascript-2015/promises/introducing-promises.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/ecmascript-2015/promises/promise-api-methods.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/ecmascript-2015/promises/promise-api-methods.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/ecmascript-2015/promises/promises-reject.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/ecmascript-2015/promises/promises-reject.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/ecmascript-2015/spread-map-set-math/map-data-structure.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/ecmascript-2015/spread-map-set-math/map-data-structure.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/ecmascript-2015/spread-map-set-math/set-data-structure.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/ecmascript-2015/spread-map-set-math/set-data-structure.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/ecmascript-2015/spread-map-set-math/spread-part-1.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/ecmascript-2015/spread-map-set-math/spread-part-1.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/ecmascript-2015/spread-map-set-math/weakmap.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/ecmascript-2015/spread-map-set-math/weakmap.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/ecmascript-2015/symbol/symbol-registry.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/ecmascript-2015/symbol/symbol-registry.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/ecmascript-2015/symbol/symbol.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/ecmascript-2015/symbol/symbol.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/ecmascript-2015/symbol/why-use-symbols.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/ecmascript-2015/symbol/why-use-symbols.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/javascript-core/array-methods/apply-map-function-to-array-items.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-core/array-methods/apply-map-function-to-array-items.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/javascript-core/dummy-workout/check-if-an-argument-is-a-number.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-core/dummy-workout/check-if-an-argument-is-a-number.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/javascript-core/dummy-workout/if-else-shortcut-conditional-operator.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-core/dummy-workout/if-else-shortcut-conditional-operator.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/javascript-core/dummy-workout/labeling-your-loops.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-core/dummy-workout/labeling-your-loops.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/javascript-core/dummy-workout/nan.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-core/dummy-workout/nan.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/javascript-core/dummy-workout/precision.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-core/dummy-workout/precision.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/javascript-core/dummy-workout/undefined-empty-null-checks.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-core/dummy-workout/undefined-empty-null-checks.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/javascript-core/dummy-workout/use-splice-to-remove-an-item-from-an-array.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-core/dummy-workout/use-splice-to-remove-an-item-from-an-array.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/javascript-core/dummy-workout/using-assignment-operators.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-core/dummy-workout/using-assignment-operators.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/javascript-core/functions-i/function-arguments.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-core/functions-i/function-arguments.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/javascript-core/functions-i/functions-can-be-declared-after-use.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-core/functions-i/functions-can-be-declared-after-use.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/javascript-core/functions-ii/anonymous-functions.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-core/functions-ii/anonymous-functions.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/javascript-core/functions-iii/bind.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-core/functions-iii/bind.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/javascript-core/functions-iii/changing-a-functions-context-with-fn-call-object.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-core/functions-iii/changing-a-functions-context-with-fn-call-object.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/javascript-core/functions-iii/function-call-method.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-core/functions-iii/function-call-method.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/javascript-core/in-depth-ii/javascript-compilation.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-core/in-depth-ii/javascript-compilation.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/javascript-core/in-depth-ii/prototype-methods.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-core/in-depth-ii/prototype-methods.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/javascript-core/javascript-strings/types-string.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-core/javascript-strings/types-string.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/javascript-core/numbers/nan-is-a-number.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-core/numbers/nan-is-a-number.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/node/error-handling/handle-json-parse-error-in-node-js.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/node/error-handling/handle-json-parse-error-in-node-js.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/node/error-handling/try-catch-only-for-sync-code.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/node/error-handling/try-catch-only-for-sync-code.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/node/events/consuming-events.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/node/events/consuming-events.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/node/events/passing-arguments-to-listeners.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/node/events/passing-arguments-to-listeners.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/node/express-ii/cookie-session-in-express.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/node/express-ii/cookie-session-in-express.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/node/express-ii/gzip-compression-for-express.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/node/express-ii/gzip-compression-for-express.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/node/express-ii/log-with-morgan-in-express.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/node/express-ii/log-with-morgan-in-express.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/node/express-ii/vhost-in-express.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/node/express-ii/vhost-in-express.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/node/express/body-parser-in-express.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/node/express/body-parser-in-express.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/node/express/error-handler-in-express.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/node/express/error-handler-in-express.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/node/express/response-object-additional-properties-in-express.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/node/express/response-object-additional-properties-in-express.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)
- [ ] [enkidevs/curriculum/javascript/node/express/using-express-4-0-router.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/node/express/using-express-4-0-router.md?ref=f5c17acc1f09b0e978066bd6d008f9ab99ceb181)

**Review by kapnobatai137 — DISMISSED** [review]
:rocket:

**Review by kapnobatai137 — DISMISSED** [review]

**Review by kapnobatai137 — APPROVED** [review]

**Pull request merged**
