### PR TITLE
Create box-model-discussion-insight.md

### PR DESCRIPTION
**Pull request by Stefan-Stojanovic**
Some information:

For this insight, I used a codepen pen.

I created 2 HTML elements where one has some CSS while the other has NONE.

I made a template link out of this with the CSS hidden. Users can use this template to complete the task without seeing the answer while working on it.

This particular insight has 2 different submission options.

1. Finish the codepen, copy the code, and paste in the comments.

2. Finish the codepen, save it, send the link in the comments.

Right now, only users that use codepen often will know how to find the hidden CSS. If they do know, then I think they don't even need this exercise 💯 as it is a simple one. (third workout of the topic)

### CODE REVIEW

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Insight previews:
- [ ] [enkidevs/curriculum/web/styling/box-model/box-model-discussion-insight.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/web/styling/box-model/box-model-discussion-insight.md?ref=bffd23d0909887effe47dfcad305f380266805c0)

**Review by nem035 — APPROVED** [review]

**Pull request merged**
