### PR TITLE
Replace old note format with emoji in Zapier

### PR DESCRIPTION
**Pull request by Stefan-Stojanovic**

### CODE REVIEW

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Insight previews:
- [ ] [enkidevs/curriculum/zapier/zapier-introduction/first-zap/zap-editor-1.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/zapier/zapier-introduction/first-zap/zap-editor-1.md?ref=008a02e4833f552eb55f154fd6491cf84a94a77d)
- [ ] [enkidevs/curriculum/zapier/zapier-introduction/first-zap/zap-editor-2.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/zapier/zapier-introduction/first-zap/zap-editor-2.md?ref=008a02e4833f552eb55f154fd6491cf84a94a77d)
- [ ] [enkidevs/curriculum/zapier/zapier-introduction/zaps-i/multi-step-zaps.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/zapier/zapier-introduction/zaps-i/multi-step-zaps.md?ref=008a02e4833f552eb55f154fd6491cf84a94a77d)

**Review by nem035 — DISMISSED** [review]

**Review by kapnobatai137 — APPROVED** [review]

**Pull request merged**
