### PR TITLE
Add a link to the iptables manpage

### PR DESCRIPTION
**Pull request by mickeypash**
I recently reviewed this lesson which is good but concise. It would benefit from having a link to the manpage.

### CODE REVIEW

**Comment by enki-hq** [comment]
Rule insight:author failed for files: 
  - linux/networking-and-security/firewall-configuration-maintenance/intro-to-iptables.md

**Comment by mickeypash** [comment]
Am I meant to change the author of the article or is this a linting issue?

**Comment by enki-hq** [comment]
### Insight previews:
- [ ] [enkidevs/curriculum/linux/networking-and-security/firewall-configuration-maintenance/intro-to-iptables.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/linux/networking-and-security/firewall-configuration-maintenance/intro-to-iptables.md?ref=724e6c57075d3e3289ce9e79f26c326ca9a7da51)

**Comment by kapnobatai137** [comment]
Hello again @mickeypash and thank you for the contribution. It is greatly appreciated :tada: 

To answer your question, it was a bit of both :sweat_smile:. We changed the `author` field to take usernames (it was previously using the first part of the email). When you created this PR, our content consumer was looking for `tuwi.dc` in the database but the username was `tuwidc`, hence the error.

I've updated the field to contain the username, and resource link is also very good. Thank you again :muscle:

**Pull request merged**
