### PR TITLE
[New Topic] [Blockchain] - Blockchain Fundamentals

### PR DESCRIPTION
**Pull request by mihaiberq**
First set of stubs for the Fundamentals course.

Before launch, some legacy concerns have to be addressed:
- [x] Fix errors
- [x] Move standards to course files from standards repo
- [x] Make sure all insights have standards
  - [x] Make sure all insights respect standards syntax:
```
standards:
  standard.objective: points
```

- [x] Add descriptions
  - [x] Add topic description
  - [x] Add course description
  - [x] Add workout descriptions

### CODE REVIEW

**Comment by enki-hq** [comment]
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/blockchain/fundamentals/altcoins/altcoins.md?ref=666a1daebf87201aef2e641b8e12474b945a3602
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/blockchain/fundamentals/altcoins/why-do-we-need-multiple-coins.md?ref=666a1daebf87201aef2e641b8e12474b945a3602
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/blockchain/fundamentals/building-the-ledger/consensus.md?ref=666a1daebf87201aef2e641b8e12474b945a3602
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/blockchain/fundamentals/building-the-ledger/malicious-nodes.md?ref=666a1daebf87201aef2e641b8e12474b945a3602
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/blockchain/fundamentals/building-the-ledger/the-ledger.md?ref=666a1daebf87201aef2e641b8e12474b945a3602
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/blockchain/fundamentals/building-the-ledger/verifying-the-ledger.md?ref=666a1daebf87201aef2e641b8e12474b945a3602
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/blockchain/fundamentals/mining/energy-consumption-and-ecology.md?ref=666a1daebf87201aef2e641b8e12474b945a3602
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/blockchain/fundamentals/mining/how-can-one-mine.md?ref=666a1daebf87201aef2e641b8e12474b945a3602
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/blockchain/fundamentals/mining/mining-pools.md?ref=666a1daebf87201aef2e641b8e12474b945a3602
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/blockchain/fundamentals/mining/mining.md?ref=666a1daebf87201aef2e641b8e12474b945a3602
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/blockchain/fundamentals/reward-algorithms/proof-of-stake.md?ref=666a1daebf87201aef2e641b8e12474b945a3602
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/blockchain/fundamentals/reward-algorithms/proof-of-useful-work.md?ref=666a1daebf87201aef2e641b8e12474b945a3602
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/blockchain/fundamentals/reward-algorithms/proof-of-work.md?ref=666a1daebf87201aef2e641b8e12474b945a3602
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/blockchain/fundamentals/reward-algorithms/reward-algorithms.md?ref=666a1daebf87201aef2e641b8e12474b945a3602
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/blockchain/fundamentals/the-blockchain/blockchain-applications.md?ref=666a1daebf87201aef2e641b8e12474b945a3602
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/blockchain/fundamentals/the-blockchain/blocks.md?ref=666a1daebf87201aef2e641b8e12474b945a3602
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/blockchain/fundamentals/the-blockchain/what-is-a-blockchain.md?ref=666a1daebf87201aef2e641b8e12474b945a3602
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/blockchain/fundamentals/wallets/wallets.md?ref=666a1daebf87201aef2e641b8e12474b945a3602

**Comment by enki-hq** [comment]
bad indentation of a mapping entry at line 5, column 3:
      type: normal
      ^

**Comment by milesflo** [comment]
:clap:

**Comment by enki-hq** [comment]
Must have exactly 1 yaml configuration but found 0 instead.

**Comment by enki-hq** [comment]
Must have exactly 1 yaml configuration but found 0 instead.

**Comment by enki-hq** [comment]
Must have exactly 1 yaml configuration but found 0 instead.

**Comment by enki-hq** [comment]
Must have exactly 1 yaml configuration but found 0 instead.

**Comment by enki-hq** [comment]
Must have exactly 1 yaml configuration but found 0 instead.

**Comment by enki-hq** [comment]
Failed parsing files: 
  - blockchain/fundamentals/anonimity/anonymity.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - blockchain/fundamentals/anonimity/how-to-de-anonymize-bitcoin.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - blockchain/fundamentals/anonimity/mixing.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - blockchain/fundamentals/consensus-algorithms/byzantine-fault-tolerance.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - blockchain/fundamentals/consensus-algorithms/consensus-algorithms.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - blockchain/fundamentals/consensus-algorithms/proof-of-authority.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - blockchain/fundamentals/consensus-algorithms/proof-of-stake.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - blockchain/fundamentals/consensus-algorithms/proof-of-work.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - blockchain/fundamentals/cryptoeconomics/why-is-the-price-fluctuating-so-much.md: 
 > Missing compiler for node of type `questionGap`: `[object Object]`
  - blockchain/fundamentals/forking/forking-to-create-altcoins.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - blockchain/fundamentals/forking/forking-to-revert-transactions.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - blockchain/fundamentals/forking/what-are-forks.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - blockchain/fundamentals/mining/energy-consumption-and-ecology.md: 
 > Missing compiler for node of type `questionGap`: `[object Object]`
  - blockchain/fundamentals/solidity/ether-heists-caused-by-bugs.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - blockchain/fundamentals/solidity/intro-to-solidity.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - blockchain/fundamentals/solidity/security-concerns.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - blockchain/fundamentals/solidity/smart-contract-example.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - blockchain/fundamentals/the-blockchain/what-is-a-blockchain.md: 
 > bad indentation of a sequence entry at line 28, column 17:
      - '[Ethereum\'s inventor, Vitalik Buterin, abo ... 
                    ^
  - blockchain/fundamentals/wallets/bc-practice-identity.md: 
 > unexpected end of the stream within a single quoted scalar at line 24, column 1:
    
    ^
  - blockchain/fundamentals/wallets/bc-practice-signing.md: 
 > unexpected end of the stream within a single quoted scalar at line 23, column 1:
    
    ^

**Comment by enki-hq** [comment]
Failed parsing files: 
  - blockchain/fundamentals/consensus-algorithms/byzantine-fault-tolerance.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - blockchain/fundamentals/consensus-algorithms/consensus-algorithms.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - blockchain/fundamentals/consensus-algorithms/proof-of-authority.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - blockchain/fundamentals/consensus-algorithms/proof-of-stake.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - blockchain/fundamentals/consensus-algorithms/proof-of-work.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - blockchain/fundamentals/cryptoeconomics/why-is-the-price-fluctuating-so-much.md: 
 > Missing compiler for node of type `questionGap`: `[object Object]`
  - blockchain/fundamentals/forking/forking-to-create-altcoins.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - blockchain/fundamentals/forking/forking-to-revert-transactions.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - blockchain/fundamentals/forking/what-are-forks.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - blockchain/fundamentals/mining/energy-consumption-and-ecology.md: 
 > Missing compiler for node of type `questionGap`: `[object Object]`
  - blockchain/fundamentals/solidity/ether-heists-caused-by-bugs.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - blockchain/fundamentals/solidity/intro-to-solidity.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - blockchain/fundamentals/solidity/security-concerns.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - blockchain/fundamentals/solidity/smart-contract-example.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - blockchain/fundamentals/the-blockchain/what-is-a-blockchain.md: 
 > bad indentation of a sequence entry at line 28, column 17:
      - '[Ethereum\'s inventor, Vitalik Buterin, abo ... 
                    ^
  - blockchain/fundamentals/wallets/bc-practice-identity.md: 
 > unexpected end of the stream within a single quoted scalar at line 24, column 1:
    
    ^
  - blockchain/fundamentals/wallets/bc-practice-signing.md: 
 > unexpected end of the stream within a single quoted scalar at line 23, column 1:
    
    ^

**Comment by enki-hq** [comment]
Failed parsing files: 
  - blockchain/fundamentals/consensus-algorithms/byzantine-fault-tolerance.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - blockchain/fundamentals/consensus-algorithms/consensus-algorithms.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - blockchain/fundamentals/consensus-algorithms/proof-of-authority.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - blockchain/fundamentals/consensus-algorithms/proof-of-stake.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - blockchain/fundamentals/consensus-algorithms/proof-of-work.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - blockchain/fundamentals/cryptoeconomics/why-is-the-price-fluctuating-so-much.md: 
 > Missing compiler for node of type `questionGap`: `[object Object]`
  - blockchain/fundamentals/mining/energy-consumption-and-ecology.md: 
 > Missing compiler for node of type `questionGap`: `[object Object]`
  - blockchain/fundamentals/solidity/ether-heists-caused-by-bugs.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - blockchain/fundamentals/solidity/intro-to-solidity.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - blockchain/fundamentals/solidity/security-concerns.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - blockchain/fundamentals/solidity/smart-contract-example.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - blockchain/fundamentals/the-blockchain/what-is-a-blockchain.md: 
 > bad indentation of a sequence entry at line 28, column 17:
      - '[Ethereum\'s inventor, Vitalik Buterin, abo ... 
                    ^
  - blockchain/fundamentals/wallets/bc-practice-identity.md: 
 > unexpected end of the stream within a single quoted scalar at line 24, column 1:
    
    ^
  - blockchain/fundamentals/wallets/bc-practice-signing.md: 
 > unexpected end of the stream within a single quoted scalar at line 23, column 1:
    
    ^

**Comment by enki-hq** [comment]
Failed parsing files: 
  - blockchain/fundamentals/consensus-algorithms/consensus-algorithms.md: 
 > bad indentation of a sequence entry at line 30, column 19:
      - '[A Hitchiker's Guide to Consensus Algorithms] ... 
                      ^
  - blockchain/fundamentals/cryptoeconomics/why-is-the-price-fluctuating-so-much.md: 
 > Missing compiler for node of type `questionGap`: `[object Object]`
  - blockchain/fundamentals/mining/energy-consumption-and-ecology.md: 
 > Missing compiler for node of type `questionGap`: `[object Object]`
  - blockchain/fundamentals/solidity/ether-heists-caused-by-bugs.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - blockchain/fundamentals/solidity/intro-to-solidity.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - blockchain/fundamentals/solidity/security-concerns.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - blockchain/fundamentals/solidity/smart-contract-example.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - blockchain/fundamentals/the-blockchain/what-is-a-blockchain.md: 
 > bad indentation of a sequence entry at line 28, column 17:
      - '[Ethereum\'s inventor, Vitalik Buterin, abo ... 
                    ^
  - blockchain/fundamentals/wallets/bc-practice-identity.md: 
 > unexpected end of the stream within a single quoted scalar at line 24, column 1:
    
    ^
  - blockchain/fundamentals/wallets/bc-practice-signing.md: 
 > unexpected end of the stream within a single quoted scalar at line 23, column 1:
    
    ^

**Comment by enki-hq** [comment]
Failed parsing files: 
  - blockchain/fundamentals/consensus-algorithms/consensus-algorithms.md: 
 > bad indentation of a sequence entry at line 30, column 19:
      - '[A Hitchiker's Guide to Consensus Algorithms] ... 
                      ^
  - blockchain/fundamentals/cryptoeconomics/why-is-the-price-fluctuating-so-much.md: 
 > Missing compiler for node of type `questionGap`: `[object Object]`
  - blockchain/fundamentals/mining/energy-consumption-and-ecology.md: 
 > Missing compiler for node of type `questionGap`: `[object Object]`
  - blockchain/fundamentals/solidity/ether-heists-caused-by-bugs.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - blockchain/fundamentals/solidity/intro-to-solidity.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - blockchain/fundamentals/solidity/security-concerns.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - blockchain/fundamentals/solidity/smart-contract-example.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - blockchain/fundamentals/the-blockchain/what-is-a-blockchain.md: 
 > bad indentation of a sequence entry at line 28, column 17:
      - '[Ethereum\'s inventor, Vitalik Buterin, abo ... 
                    ^
  - blockchain/fundamentals/wallets/bc-practice-identity.md: 
 > unexpected end of the stream within a single quoted scalar at line 24, column 1:
    
    ^
  - blockchain/fundamentals/wallets/bc-practice-signing.md: 
 > unexpected end of the stream within a single quoted scalar at line 23, column 1:
    
    ^

**Comment by enki-hq** [comment]
Failed parsing files: 
  - blockchain/fundamentals/consensus-algorithms/consensus-algorithms.md: 
 > bad indentation of a sequence entry at line 30, column 19:
      - '[A Hitchiker's Guide to Consensus Algorithms] ... 
                      ^
  - blockchain/fundamentals/cryptoeconomics/why-is-the-price-fluctuating-so-much.md: 
 > Missing compiler for node of type `questionGap`: `[object Object]`
  - blockchain/fundamentals/mining/energy-consumption-and-ecology.md: 
 > Missing compiler for node of type `questionGap`: `[object Object]`
  - blockchain/fundamentals/solidity/ether-heists-caused-by-bugs.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - blockchain/fundamentals/solidity/intro-to-solidity.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - blockchain/fundamentals/solidity/security-concerns.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - blockchain/fundamentals/solidity/smart-contract-example.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - blockchain/fundamentals/the-blockchain/what-is-a-blockchain.md: 
 > bad indentation of a sequence entry at line 28, column 17:
      - '[Ethereum\'s inventor, Vitalik Buterin, abo ... 
                    ^
  - blockchain/fundamentals/wallets/bc-practice-identity.md: 
 > unexpected end of the stream within a single quoted scalar at line 24, column 1:
    
    ^
  - blockchain/fundamentals/wallets/bc-practice-signing.md: 
 > unexpected end of the stream within a single quoted scalar at line 23, column 1:
    
    ^

**Comment by enki-hq** [comment]
Failed parsing files: 
  - blockchain/fundamentals/cryptoeconomics/why-is-the-price-fluctuating-so-much.md: 
 > Missing compiler for node of type `questionGap`: `[object Object]`
  - blockchain/fundamentals/solidity/smart-contract-example.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.

**Comment by enki-hq** [comment]
Failed parsing files: 
  - blockchain/fundamentals/cryptoeconomics/why-is-the-price-fluctuating-so-much.md: 
 > Missing compiler for node of type `questionGap`: `[object Object]`
  - blockchain/fundamentals/solidity/smart-contract-example.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.

**Comment by enki-hq** [comment]
Failed parsing files: 
  - blockchain/fundamentals/cryptoeconomics/why-is-the-price-fluctuating-so-much.md: 
 > Missing compiler for node of type `questionGap`: `[object Object]`
  - blockchain/fundamentals/solidity/smart-contract-example.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.

**Comment by enki-hq** [comment]
Failed parsing files: 
  - blockchain/fundamentals/building-the-ledger/the-ledger.md: 
 > duplicated mapping key at line 16, column 3:
      blockchain.identify-blockchain-a ... 
      ^
  - blockchain/fundamentals/cryptoeconomics/why-is-the-price-fluctuating-so-much.md: 
 > Missing compiler for node of type `questionGap`: `[object Object]`
  - blockchain/fundamentals/solidity/smart-contract-example.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.

**Comment by enki-hq** [comment]
Failed parsing files: 
  - blockchain/fundamentals/cryptoeconomics/why-is-the-price-fluctuating-so-much.md: 
 > Missing compiler for node of type `questionGap`: `[object Object]`

**Comment by enki-hq** [comment]
Rule insight:quiz failed for files: 
  - blockchain/fundamentals/consensus-algorithms/consensus-algorithms.md
  - blockchain/fundamentals/the-blockchain/what-is-a-blockchain.md

**Comment by enki-hq** [comment]
Rule insight:footnotes failed for files: 
  - blockchain/fundamentals/the-blockchain/what-is-a-blockchain.md

**Comment by enki-hq** [comment]
Rule insight:standards failed for files: 
  - blockchain/fundamentals/altcoins/altcoins.md
  - blockchain/fundamentals/altcoins/why-is-it-worth-having-multiple-coins.md
  - blockchain/fundamentals/building-the-ledger/bc-practice-distributed.md
  - blockchain/fundamentals/building-the-ledger/bc-practice-transaction.md
  - blockchain/fundamentals/forking/forking-to-create-altcoins.md
  - blockchain/fundamentals/wallets/bc-practice-signing.md
  - blockchain/fundamentals/consensus-algorithms/byzantine-fault-tolerance.md
  - blockchain/fundamentals/consensus-algorithms/consensus-algorithms.md
  - blockchain/fundamentals/consensus-algorithms/delegated-proof-of-stake.md
  - blockchain/fundamentals/consensus-algorithms/proof-of-stake.md
  - blockchain/fundamentals/consensus-algorithms/proof-of-work.md
  - blockchain/fundamentals/forking/forking-to-reverse-transactions.md
  - blockchain/fundamentals/forking/what-are-forks.md
  - blockchain/fundamentals/the-blockchain/bc-practice-blockchain.md
  - blockchain/fundamentals/the-blockchain/bc-practice-blocks.md
  - blockchain/fundamentals/wallets/bc-practice-identity.md

**Comment by enki-hq** [comment]
Rule workout:insights failed for files: 
  - blockchain/fundamentals/consensus-algorithms/README.md

**Comment by enki-hq** [comment]
Rule topic:data failed for files: 
  - blockchain/README.md

**Comment by enki-hq** [comment]
### Insight previews:
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/blockchain/fundamentals/altcoins/altcoins.md?ref=362757580bbc914704e17b789f168e62d964bb4d
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/blockchain/fundamentals/altcoins/why-is-it-worth-having-multiple-coins.md?ref=362757580bbc914704e17b789f168e62d964bb4d
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/blockchain/fundamentals/anonimity/anonymity.md?ref=362757580bbc914704e17b789f168e62d964bb4d
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/blockchain/fundamentals/anonimity/how-to-de-anonymize-bitcoin.md?ref=362757580bbc914704e17b789f168e62d964bb4d
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/blockchain/fundamentals/anonimity/mixing.md?ref=362757580bbc914704e17b789f168e62d964bb4d
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/blockchain/fundamentals/blockchain-on-the-web/web3js.md?ref=362757580bbc914704e17b789f168e62d964bb4d
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/blockchain/fundamentals/building-the-ledger/bc-practice-distributed.md?ref=362757580bbc914704e17b789f168e62d964bb4d
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/blockchain/fundamentals/building-the-ledger/bc-practice-transaction.md?ref=362757580bbc914704e17b789f168e62d964bb4d
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/blockchain/fundamentals/building-the-ledger/consensus.md?ref=362757580bbc914704e17b789f168e62d964bb4d
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/blockchain/fundamentals/building-the-ledger/malicious-nodes.md?ref=362757580bbc914704e17b789f168e62d964bb4d
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/blockchain/fundamentals/building-the-ledger/the-ledger.md?ref=362757580bbc914704e17b789f168e62d964bb4d
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/blockchain/fundamentals/building-the-ledger/the-utxo-model.md?ref=362757580bbc914704e17b789f168e62d964bb4d
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/blockchain/fundamentals/building-the-ledger/verifying-the-ledger.md?ref=362757580bbc914704e17b789f168e62d964bb4d
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/blockchain/fundamentals/consensus-algorithms/byzantine-fault-tolerance.md?ref=362757580bbc914704e17b789f168e62d964bb4d
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/blockchain/fundamentals/consensus-algorithms/consensus-algorithms.md?ref=362757580bbc914704e17b789f168e62d964bb4d
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/blockchain/fundamentals/consensus-algorithms/delegated-proof-of-stake.md?ref=362757580bbc914704e17b789f168e62d964bb4d
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/blockchain/fundamentals/consensus-algorithms/proof-of-stake.md?ref=362757580bbc914704e17b789f168e62d964bb4d
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/blockchain/fundamentals/consensus-algorithms/proof-of-work.md?ref=362757580bbc914704e17b789f168e62d964bb4d
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/blockchain/fundamentals/cryptoeconomics/how-do-cryptocurrencies-acquire-value.md?ref=362757580bbc914704e17b789f168e62d964bb4d
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/blockchain/fundamentals/cryptoeconomics/why-is-the-price-fluctuating-so-much.md?ref=362757580bbc914704e17b789f168e62d964bb4d
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/blockchain/fundamentals/ethereum-i/ethereum-and-ether.md?ref=362757580bbc914704e17b789f168e62d964bb4d
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/blockchain/fundamentals/ethereum-i/what-are-smart-contracts.md?ref=362757580bbc914704e17b789f168e62d964bb4d
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/blockchain/fundamentals/ethereum-i/what-does-ethereum-do-differently.md?ref=362757580bbc914704e17b789f168e62d964bb4d
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/blockchain/fundamentals/ethereum-ii/erc20-tokens.md?ref=362757580bbc914704e17b789f168e62d964bb4d
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/blockchain/fundamentals/ethereum-ii/initial-coin-offerings.md?ref=362757580bbc914704e17b789f168e62d964bb4d
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/blockchain/fundamentals/forking/forking-to-create-altcoins.md?ref=362757580bbc914704e17b789f168e62d964bb4d
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/blockchain/fundamentals/forking/forking-to-reverse-transactions.md?ref=362757580bbc914704e17b789f168e62d964bb4d
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/blockchain/fundamentals/forking/what-are-forks.md?ref=362757580bbc914704e17b789f168e62d964bb4d
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/blockchain/fundamentals/mining/energy-consumption-and-ecology.md?ref=362757580bbc914704e17b789f168e62d964bb4d
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/blockchain/fundamentals/mining/how-can-one-mine.md?ref=362757580bbc914704e17b789f168e62d964bb4d
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/blockchain/fundamentals/mining/mining-pools.md?ref=362757580bbc914704e17b789f168e62d964bb4d
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/blockchain/fundamentals/mining/mining.md?ref=362757580bbc914704e17b789f168e62d964bb4d
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/blockchain/fundamentals/solidity/ether-heists-caused-by-bugs.md?ref=362757580bbc914704e17b789f168e62d964bb4d
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/blockchain/fundamentals/solidity/intro-to-solidity.md?ref=362757580bbc914704e17b789f168e62d964bb4d
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/blockchain/fundamentals/solidity/security-concerns.md?ref=362757580bbc914704e17b789f168e62d964bb4d
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/blockchain/fundamentals/the-bitcoin-blockchain/bitcoin.md?ref=362757580bbc914704e17b789f168e62d964bb4d
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/blockchain/fundamentals/the-bitcoin-blockchain/the-bitcoin-block.md?ref=362757580bbc914704e17b789f168e62d964bb4d
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/blockchain/fundamentals/the-bitcoin-blockchain/the-bitcoin-blockchain.md?ref=362757580bbc914704e17b789f168e62d964bb4d
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/blockchain/fundamentals/the-blockchain/bc-practice-blockchain.md?ref=362757580bbc914704e17b789f168e62d964bb4d
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/blockchain/fundamentals/the-blockchain/bc-practice-blocks.md?ref=362757580bbc914704e17b789f168e62d964bb4d
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/blockchain/fundamentals/the-blockchain/blockchain-components.md?ref=362757580bbc914704e17b789f168e62d964bb4d
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/blockchain/fundamentals/the-blockchain/blocks.md?ref=362757580bbc914704e17b789f168e62d964bb4d
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/blockchain/fundamentals/the-blockchain/what-is-a-blockchain.md?ref=362757580bbc914704e17b789f168e62d964bb4d
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/blockchain/fundamentals/wallets/bc-practice-identity.md?ref=362757580bbc914704e17b789f168e62d964bb4d
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/blockchain/fundamentals/wallets/bc-practice-signing.md?ref=362757580bbc914704e17b789f168e62d964bb4d
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/blockchain/fundamentals/wallets/identity.md?ref=362757580bbc914704e17b789f168e62d964bb4d
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/blockchain/fundamentals/wallets/wallets.md?ref=362757580bbc914704e17b789f168e62d964bb4d

**Comment by enki-hq** [comment]
Rule insight:type-content failed for files: 
  - blockchain/fundamentals/wallets/keeping-your-wallet-secure.md

**Pull request merged**
