### PR TITLE
Update dictionary-methods-ii.md

### PR DESCRIPTION
**Pull request by Stefan-Stojanovic**

### CODE REVIEW

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Insight previews:
- [ ] [enkidevs/curriculum/python/python-core/unordered-data-types/dictionary-methods-ii.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python/python-core/unordered-data-types/dictionary-methods-ii.md?ref=130a3dad91e7e71ee8555718a72d0976485e8f7c)

**Comment by kapnobatai137** [comment]
@Stefan-Stojanovic is this PR still relevant?

**Comment by Stefan-Stojanovic** [comment]
> @Stefan-Stojanovic is this PR still relevant?

Since we decided to remove the `zip()` entirely from the following exercise, no, closing it now

**Pull request closed without merging**
