### PR TITLE
Update header.md

### PR DESCRIPTION
**Pull request by Stefan-Stojanovic**
add <> to the question and remove it from all answers as it has no benefit having to explicitly write <> when asked about the elements name

### CODE REVIEW

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Insight previews:
- [ ] [enkidevs/curriculum/web/html/sectioning-elements/footer.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/web/html/sectioning-elements/footer.md?ref=0228f0e6692a6f02c44c8819a3e3a22839cc91c9)
- [ ] [enkidevs/curriculum/web/html/sectioning-elements/header.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/web/html/sectioning-elements/header.md?ref=0228f0e6692a6f02c44c8819a3e3a22839cc91c9)
- [ ] [enkidevs/curriculum/web/html/sectioning-elements/main.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/web/html/sectioning-elements/main.md?ref=0228f0e6692a6f02c44c8819a3e3a22839cc91c9)

**Review by nem035 — APPROVED** [review]

**Review by nem035 — APPROVED** [review]

**Pull request merged**
