### PR TITLE
Replace old note format with emoji one JavaScript

### PR DESCRIPTION
**Pull request by Stefan-Stojanovic**
Replace `note` word with lightbulb emoji across all notes in the js topic

`> note: ` 
-> 
`> 💡` for regular notes
`> ❗ ` dangerous/warning notes

### CODE REVIEW

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Insight previews:
- [ ] [enkidevs/curriculum/javascript/browser-apis/reading-writing/blobs.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/browser-apis/reading-writing/blobs.md?ref=597b6b2626d69faa797ad35954790bf64c7d6429)
- [ ] [enkidevs/curriculum/javascript/ecmascript-2015/function-improvements/property-value-shorthand.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/ecmascript-2015/function-improvements/property-value-shorthand.md?ref=597b6b2626d69faa797ad35954790bf64c7d6429)
- [ ] [enkidevs/curriculum/javascript/ecmascript-2015/promises/how-to-create-promises.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/ecmascript-2015/promises/how-to-create-promises.md?ref=597b6b2626d69faa797ad35954790bf64c7d6429)
- [ ] [enkidevs/curriculum/javascript/javascript-core/flow-control/loops-part-1.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-core/flow-control/loops-part-1.md?ref=597b6b2626d69faa797ad35954790bf64c7d6429)
- [ ] [enkidevs/curriculum/javascript/javascript-core/in-depth-ii/javascript-compilation.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-core/in-depth-ii/javascript-compilation.md?ref=597b6b2626d69faa797ad35954790bf64c7d6429)
- [ ] [enkidevs/curriculum/javascript/javascript-core/scope/scope-and-strict-mode.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-core/scope/scope-and-strict-mode.md?ref=597b6b2626d69faa797ad35954790bf64c7d6429)
- [ ] [enkidevs/curriculum/javascript/javascript-core/types-ii/truthy-falsy.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-core/types-ii/truthy-falsy.md?ref=597b6b2626d69faa797ad35954790bf64c7d6429)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/js-adding-and-sorting-arrays/js-adding-and-sorting-arrays.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/js-adding-and-sorting-arrays/js-adding-and-sorting-arrays.md?ref=597b6b2626d69faa797ad35954790bf64c7d6429)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/js-print-primes/js-print-primes.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/js-print-primes/js-print-primes.md?ref=597b6b2626d69faa797ad35954790bf64c7d6429)
- [ ] [enkidevs/curriculum/javascript/node/file-io/async-file-write-in-node-js.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/node/file-io/async-file-write-in-node-js.md?ref=597b6b2626d69faa797ad35954790bf64c7d6429)
- [ ] [enkidevs/curriculum/javascript/node/modules/requiring-and-exporting.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/node/modules/requiring-and-exporting.md?ref=597b6b2626d69faa797ad35954790bf64c7d6429)
- [ ] [enkidevs/curriculum/javascript/node/operational-vs-programmer-errors/operational-vs-programmer-errors.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/node/operational-vs-programmer-errors/operational-vs-programmer-errors.md?ref=597b6b2626d69faa797ad35954790bf64c7d6429)

**Review by nem035 — DISMISSED** [review]
:+1:

**Review by kapnobatai137 — APPROVED** [review]

**Pull request merged**
