### PR TITLE
Add Python Playground Questions

### PR DESCRIPTION
**Pull request by Stefan-Stojanovic**

### CODE REVIEW

**Comment by enki-hq** [comment]
Failed parsing files: 
  - python-playground-questions/python-playground-core/harmonic-series/harmonic-series.md: 
 > 	Cannot compile node with invalid type thematicBreak

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Workout

| Workout Name | Error Message |
|:-:|:-:|
| sum-lists-in-a-dict | One of the mentioned insights couldn't be found in this pull request or the database. |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Workout

| Workout Name | Error Message |
|:-:|:-:|
| sum-lists-in-a-dict | One of the mentioned insights couldn't be found in this pull request or the database. |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Workout

| Workout Name | Error Message |
|:-:|:-:|
| sum-lists-in-a-dict | One of the mentioned insights couldn't be found in this pull request or the database. |
### Course

| Course Name | Error Message |
|:-:|:-:|
| python-playground-core | We couldn't find these workouts: `sort-lists-in-a-dict`. |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Workout

| Workout Name | Error Message |
|:-:|:-:|
| sort-lists-in-a-dict | One of the mentioned insights couldn't be found in this pull request or the database. |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Insight previews:
- [ ] [enkidevs/curriculum/python-playground-questions/python-playground-core/adding-and-sorting-lists/adding-and-sorting-lists.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python-playground-questions/python-playground-core/adding-and-sorting-lists/adding-and-sorting-lists.md?ref=aec5aa53b07591bb0c4127b81c5b1f79b8200f5a)
- [ ] [enkidevs/curriculum/python-playground-questions/python-playground-core/arithmetic-operation/arithmetic-operation.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python-playground-questions/python-playground-core/arithmetic-operation/arithmetic-operation.md?ref=aec5aa53b07591bb0c4127b81c5b1f79b8200f5a)
- [ ] [enkidevs/curriculum/python-playground-questions/python-playground-core/beginning-and-end-pairs/beginning-and-end-pairs.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python-playground-questions/python-playground-core/beginning-and-end-pairs/beginning-and-end-pairs.md?ref=aec5aa53b07591bb0c4127b81c5b1f79b8200f5a)
- [ ] [enkidevs/curriculum/python-playground-questions/python-playground-core/calculator-class/calculator-class.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python-playground-questions/python-playground-core/calculator-class/calculator-class.md?ref=aec5aa53b07591bb0c4127b81c5b1f79b8200f5a)
- [ ] [enkidevs/curriculum/python-playground-questions/python-playground-core/combine-dictionaries/combine-dictionaries.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python-playground-questions/python-playground-core/combine-dictionaries/combine-dictionaries.md?ref=aec5aa53b07591bb0c4127b81c5b1f79b8200f5a)
- [ ] [enkidevs/curriculum/python-playground-questions/python-playground-core/dice-roll/dice-roll.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python-playground-questions/python-playground-core/dice-roll/dice-roll.md?ref=aec5aa53b07591bb0c4127b81c5b1f79b8200f5a)
- [ ] [enkidevs/curriculum/python-playground-questions/python-playground-core/even-or-odd/even-or-odd.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python-playground-questions/python-playground-core/even-or-odd/even-or-odd.md?ref=aec5aa53b07591bb0c4127b81c5b1f79b8200f5a)
- [ ] [enkidevs/curriculum/python-playground-questions/python-playground-core/factorial-calculator/factorial-calculator.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python-playground-questions/python-playground-core/factorial-calculator/factorial-calculator.md?ref=aec5aa53b07591bb0c4127b81c5b1f79b8200f5a)
- [ ] [enkidevs/curriculum/python-playground-questions/python-playground-core/fibonacci-sequence/fibonacci-sequence.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python-playground-questions/python-playground-core/fibonacci-sequence/fibonacci-sequence.md?ref=aec5aa53b07591bb0c4127b81c5b1f79b8200f5a)
- [ ] [enkidevs/curriculum/python-playground-questions/python-playground-core/happy-birthday/happy-birthday.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python-playground-questions/python-playground-core/happy-birthday/happy-birthday.md?ref=aec5aa53b07591bb0c4127b81c5b1f79b8200f5a)
- [ ] [enkidevs/curriculum/python-playground-questions/python-playground-core/harmonic-series/harmonic-series.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python-playground-questions/python-playground-core/harmonic-series/harmonic-series.md?ref=aec5aa53b07591bb0c4127b81c5b1f79b8200f5a)
- [ ] [enkidevs/curriculum/python-playground-questions/python-playground-core/iterate-over-dict-values/iterate-over-dict-values.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python-playground-questions/python-playground-core/iterate-over-dict-values/iterate-over-dict-values.md?ref=aec5aa53b07591bb0c4127b81c5b1f79b8200f5a)
- [ ] [enkidevs/curriculum/python-playground-questions/python-playground-core/iterate-over-two-lists/iterate-over-two-lists.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python-playground-questions/python-playground-core/iterate-over-two-lists/iterate-over-two-lists.md?ref=aec5aa53b07591bb0c4127b81c5b1f79b8200f5a)
- [ ] [enkidevs/curriculum/python-playground-questions/python-playground-core/least-frequent-character/least-frequent-character.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python-playground-questions/python-playground-core/least-frequent-character/least-frequent-character.md?ref=aec5aa53b07591bb0c4127b81c5b1f79b8200f5a)
- [ ] [enkidevs/curriculum/python-playground-questions/python-playground-core/list-of-characters-to-string/list-of-characters-to-string.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python-playground-questions/python-playground-core/list-of-characters-to-string/list-of-characters-to-string.md?ref=aec5aa53b07591bb0c4127b81c5b1f79b8200f5a)
- [ ] [enkidevs/curriculum/python-playground-questions/python-playground-core/miles-to-kilometeres/miles-to-kilometeres.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python-playground-questions/python-playground-core/miles-to-kilometeres/miles-to-kilometeres.md?ref=aec5aa53b07591bb0c4127b81c5b1f79b8200f5a)
- [ ] [enkidevs/curriculum/python-playground-questions/python-playground-core/multiplication-table/multiplication-table.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python-playground-questions/python-playground-core/multiplication-table/multiplication-table.md?ref=aec5aa53b07591bb0c4127b81c5b1f79b8200f5a)
- [ ] [enkidevs/curriculum/python-playground-questions/python-playground-core/pascals-triangle/pascals-triangle.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python-playground-questions/python-playground-core/pascals-triangle/pascals-triangle.md?ref=aec5aa53b07591bb0c4127b81c5b1f79b8200f5a)
- [ ] [enkidevs/curriculum/python-playground-questions/python-playground-core/print-primes/print-primes.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python-playground-questions/python-playground-core/print-primes/print-primes.md?ref=aec5aa53b07591bb0c4127b81c5b1f79b8200f5a)
- [ ] [enkidevs/curriculum/python-playground-questions/python-playground-core/remove-duplicate-from-tuple/remove-duplicate-from-tuple.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python-playground-questions/python-playground-core/remove-duplicate-from-tuple/remove-duplicate-from-tuple.md?ref=aec5aa53b07591bb0c4127b81c5b1f79b8200f5a)
- [ ] [enkidevs/curriculum/python-playground-questions/python-playground-core/remove-odd-numbers-from-list/remove-odd-numbers-from-list.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python-playground-questions/python-playground-core/remove-odd-numbers-from-list/remove-odd-numbers-from-list.md?ref=aec5aa53b07591bb0c4127b81c5b1f79b8200f5a)
- [ ] [enkidevs/curriculum/python-playground-questions/python-playground-core/reverse-a-string/reverse-a-string.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python-playground-questions/python-playground-core/reverse-a-string/reverse-a-string.md?ref=aec5aa53b07591bb0c4127b81c5b1f79b8200f5a)
- [ ] [enkidevs/curriculum/python-playground-questions/python-playground-core/smallest-list-element/smallest-list-element.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python-playground-questions/python-playground-core/smallest-list-element/smallest-list-element.md?ref=aec5aa53b07591bb0c4127b81c5b1f79b8200f5a)
- [ ] [enkidevs/curriculum/python-playground-questions/python-playground-core/sort-lists-in-a-dict/sort-lists-in-a-dict.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python-playground-questions/python-playground-core/sort-lists-in-a-dict/sort-lists-in-a-dict.md?ref=aec5aa53b07591bb0c4127b81c5b1f79b8200f5a)
- [ ] [enkidevs/curriculum/python-playground-questions/python-playground-core/squared-dictionary-keys/squared-dictionary-keys.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python-playground-questions/python-playground-core/squared-dictionary-keys/squared-dictionary-keys.md?ref=aec5aa53b07591bb0c4127b81c5b1f79b8200f5a)
- [ ] [enkidevs/curriculum/python-playground-questions/python-playground-core/string-length/string-length.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python-playground-questions/python-playground-core/string-length/string-length.md?ref=aec5aa53b07591bb0c4127b81c5b1f79b8200f5a)
- [ ] [enkidevs/curriculum/python-playground-questions/python-playground-core/sum-and-product-of-two-tuples/sum-and-product-of-two-tuples.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python-playground-questions/python-playground-core/sum-and-product-of-two-tuples/sum-and-product-of-two-tuples.md?ref=aec5aa53b07591bb0c4127b81c5b1f79b8200f5a)
- [ ] [enkidevs/curriculum/python-playground-questions/python-playground-core/sum-items-in-dict/sum-items-in-dict.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python-playground-questions/python-playground-core/sum-items-in-dict/sum-items-in-dict.md?ref=aec5aa53b07591bb0c4127b81c5b1f79b8200f5a)
- [ ] [enkidevs/curriculum/python-playground-questions/python-playground-core/word-length/word-length.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/python-playground-questions/python-playground-core/word-length/word-length.md?ref=aec5aa53b07591bb0c4127b81c5b1f79b8200f5a)

**Comment by Stefan-Stojanovic** [comment]
Closing this one and adding a new one as it is easier than updating all 30 insights 1 by 1

**Pull request closed without merging**
