### PR TITLE
Python - Improvements Wave II

### PR DESCRIPTION
**Pull request by kapnobatai137**

### CODE REVIEW

**Comment by enki-hq** [comment]
Failed parsing files: 
  - python/core/sequential-data-types-i/intro-to-sequential-data-types.md: 
 > can not read an implicit mapping pair; a colon is missed at line 14, column 92:
     ... at-does-pythonic-mean){website}'
                                         ^

**Comment by enki-hq** [comment]
Rule insight:slug failed for files: 
  - python/core/sequential-data-types-i/the-fundamental-tuples.md
  - python/core/control-structures-ii/chain-comparison-operators.md
  - python/core/sequential-data-types-i/tuple-assignment.md
  - python/core/sequential-data-types-ii/del-statement-for-lists.md
  - python/core/sequential-data-types-ii/lists.md

**Comment by enki-hq** [comment]
Rule insight:questions failed for files: 
  - python/core/sequential-data-types-ii/built-in-list-methods-i.md

**Comment by enki-hq** [comment]
Rule insight:footnotes failed for files: 
  - python/core/sequential-data-types-i/intro-to-sequential-data-types.md

**Comment by enki-hq** [comment]
Rule insight:slug failed for files: 
  - python/core/control-structures-ii/chain-comparison-operators.md
  - python/core/syntax-and-numerical-operators/python-data-types.md

**Comment by enki-hq** [comment]
Rule insight:footnotes failed for files: 
  - python/core/sequential-data-types-i/intro-to-sequential-data-types.md

**Comment by enki-hq** [comment]
Rule workout:slug failed for files: 
  - .archived/python/core/control-structures/README.md

**Comment by enki-hq** [comment]
Rule insight:footnotes failed for files: 
  - python/core/sequential-data-types-i/intro-to-sequential-data-types.md

**Comment by enki-hq** [comment]
Rule workout:slug failed for files: 
  - .archived/python/core/control-structures/README.md

**Comment by enki-hq** [comment]
Rule insight:footnotes failed for files: 
  - python/core/sequential-data-types-i/intro-to-sequential-data-types.md

**Comment by enki-hq** [comment]
Rule workout:slug failed for files: 
  - .archived/python/core/control-structures/README.md

**Comment by enki-hq** [comment]
Rule insight:footnotes failed for files: 
  - python/core/sequential-data-types-i/intro-to-sequential-data-types.md

**Comment by enki-hq** [comment]
Rule insight:footnotes failed for files: 
  - python/core/sequential-data-types-i/intro-to-sequential-data-types.md

**Comment by kapnobatai137** [comment]
will close this, a better pr is up that will keep history of all/most insights

**Pull request closed without merging**
