### PR TITLE
Update wording

### PR DESCRIPTION
**Pull request by Stefan-Stojanovic**

### CODE REVIEW

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Insight previews:
- [ ] [enkidevs/curriculum/regular-expressions/regular-expressions-introduction/email-and-password-example/regex-email-address-checker-ii.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/regular-expressions/regular-expressions-introduction/email-and-password-example/regex-email-address-checker-ii.md?ref=eaa0d82500bb00dce98299356444c3c2e276137e)

**Review by kapnobatai137 — APPROVED** [review]
:rocket:

**Pull request merged**
