### PR TITLE
Update tagged-template-literals-2.md

### PR DESCRIPTION
**Pull request by Stefan-Stojanovic**
enclose all answers in double back ticks to display the answers with a back tick in it and not combine it with the next answer with a back tick and create multiple wrong answers.

the possible answers in the app would combine the first ` with the 2nd  `)  and the third `)) and give  ``, ) and )) as possible answers, (``) being the correct one

### CODE REVIEW

**Comment by enki-hq** [comment]
### Insight previews:
- [ ] [enkidevs/curriculum/javascript/ecmascript-2015/string-flexibility/tagged-template-literals-2.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/javascript/ecmascript-2015/string-flexibility/tagged-template-literals-2.md?ref=cb6a449d511552cc10cc1bff82fca6dcef028417)

**Comment by kapnobatai137** [comment]
can you test this in spider so we can see how it is displayed? @Stefan-Stojanovic

**Comment by Stefan-Stojanovic** [comment]
It still doesn't work.

I've tried all of these within the app and none display the backtick:

* ``Backticks (`)``
*  `Backticks (\`)`
*  `Backticks (`)`
* ``Backticks (\`)``
* ``Backticks (`)``
*  `Backticks (/`)`
*  `Backticks (`)`
* ``Backticks (/`)``
* Backticks (/`)
* Backticks(`)

**Comment by kapnobatai137** [comment]
I think the best approach here is to change the question. I'll tackle this tomorrow.

**Comment by kapnobatai137** [comment]
image

**Pull request merged**
