### PR TITLE
Add type in the gap Git

### PR DESCRIPTION
**Pull request by Stefan-Stojanovic**
Marked if applied to all insights:

- [x] Remove all backticks from every headline

- [x] Add type in the gap and change context to standalone to all applicable questions

- [x] Change some questions to support type in the gap

### CODE REVIEW

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Insight previews:
- [ ] [enkidevs/curriculum/git/essentials/branching/fetching-a-remote-branch.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/essentials/branching/fetching-a-remote-branch.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/essentials/branching/managing-branches.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/essentials/branching/managing-branches.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/essentials/branching/pulling-a-remote-branch.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/essentials/branching/pulling-a-remote-branch.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/essentials/branching/pushing-to-a-remote-branch.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/essentials/branching/pushing-to-a-remote-branch.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/essentials/branching/setting-the-upstream-branch.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/essentials/branching/setting-the-upstream-branch.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/essentials/branching/what-is-rebasing.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/essentials/branching/what-is-rebasing.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/essentials/commits/cherry-pick-a-commit.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/essentials/commits/cherry-pick-a-commit.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/essentials/commits/custom-commit-template.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/essentials/commits/custom-commit-template.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/essentials/commits/how-to-write-a-git-commit-message.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/essentials/commits/how-to-write-a-git-commit-message.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/essentials/commits/what-is-a-checksum.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/essentials/commits/what-is-a-checksum.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/essentials/commits/what-is-stored-in-a-commit.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/essentials/commits/what-is-stored-in-a-commit.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/essentials/getting-started/basic-git-configuration.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/essentials/getting-started/basic-git-configuration.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/essentials/getting-started/cloning-a-git-repository.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/essentials/getting-started/cloning-a-git-repository.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/essentials/getting-started/initializing-a-git-repository.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/essentials/getting-started/initializing-a-git-repository.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/essentials/getting-started/some-common-terminology.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/essentials/getting-started/some-common-terminology.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/essentials/git-features-i/check-the-reflog.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/essentials/git-features-i/check-the-reflog.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/essentials/git-features-i/get-the-most-out-of-git.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/essentials/git-features-i/get-the-most-out-of-git.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/essentials/git-features-i/git-ignore.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/essentials/git-features-i/git-ignore.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/essentials/git-features-i/subdirectory-checkout.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/essentials/git-features-i/subdirectory-checkout.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/essentials/git-features-ii/dates-in-git.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/essentials/git-features-ii/dates-in-git.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/essentials/git-features-ii/debug-using-binary-search.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/essentials/git-features-ii/debug-using-binary-search.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/essentials/git-features-ii/let-s-play-the-blame-game.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/essentials/git-features-ii/let-s-play-the-blame-game.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/essentials/git-features-ii/reset-vs-revert.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/essentials/git-features-ii/reset-vs-revert.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/essentials/git-features-iii/create-a-global-git-commit-hook.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/essentials/git-features-iii/create-a-global-git-commit-hook.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/essentials/git-features-iii/diff-images-using-exiftool.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/essentials/git-features-iii/diff-images-using-exiftool.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/essentials/git-features-iii/useful-commit-hooks.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/essentials/git-features-iii/useful-commit-hooks.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/essentials/git-features-iii/what-is-a-hook.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/essentials/git-features-iii/what-is-a-hook.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/essentials/git-features-iv/pushing-tags-to-a-server.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/essentials/git-features-iv/pushing-tags-to-a-server.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/essentials/git-features-iv/revision-tools.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/essentials/git-features-iv/revision-tools.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/essentials/git-features-iv/sharing-data-by-bundling.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/essentials/git-features-iv/sharing-data-by-bundling.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/essentials/git-features-iv/using-tags-for-version-control.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/essentials/git-features-iv/using-tags-for-version-control.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/essentials/git-fundamentals/branches-in-git.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/essentials/git-fundamentals/branches-in-git.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/essentials/git-fundamentals/how-does-git-work.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/essentials/git-fundamentals/how-does-git-work.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/essentials/git-fundamentals/the-git-working-tree.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/essentials/git-fundamentals/the-git-working-tree.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/essentials/git-fundamentals/what-is-git.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/essentials/git-fundamentals/what-is-git.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/essentials/git-fundamentals/what-is-version-control.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/essentials/git-fundamentals/what-is-version-control.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/essentials/intro-git/benefits-of-git.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/essentials/intro-git/benefits-of-git.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/essentials/intro-git/installing-git.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/essentials/intro-git/installing-git.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/essentials/intro-git/why-git.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/essentials/intro-git/why-git.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/essentials/local-repository/committing.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/essentials/local-repository/committing.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/essentials/local-repository/stashing.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/essentials/local-repository/stashing.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/essentials/local-repository/the-local-repository.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/essentials/local-repository/the-local-repository.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/essentials/local-repository/tracking-and-staging-files.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/essentials/local-repository/tracking-and-staging-files.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/essentials/local-repository/working-in-the-local-repository.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/essentials/local-repository/working-in-the-local-repository.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/essentials/remote-repository/introduction-to-remote-repositories.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/essentials/remote-repository/introduction-to-remote-repositories.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/essentials/remote-repository/merging.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/essentials/remote-repository/merging.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/essentials/remote-repository/pushing.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/essentials/remote-repository/pushing.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/essentials/remote-repository/tracking-and-staging-files.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/essentials/remote-repository/tracking-and-staging-files.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/essentials/remote-repository/working-with-remotes.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/essentials/remote-repository/working-with-remotes.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/workflow/branches/checkout-the-previous-branch.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/workflow/branches/checkout-the-previous-branch.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/workflow/branches/master-and-origin-aren-t-special.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/workflow/branches/master-and-origin-aren-t-special.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/workflow/branches/move-the-last-commit-to-a-new-branch.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/workflow/branches/move-the-last-commit-to-a-new-branch.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/workflow/branches/prune-remote-tracking-references.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/workflow/branches/prune-remote-tracking-references.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/workflow/branches/viewing-your-tracking-branches.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/workflow/branches/viewing-your-tracking-branches.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/workflow/finding-commits/locate-a-commit-by-its-hash.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/workflow/finding-commits/locate-a-commit-by-its-hash.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/workflow/finding-commits/search-by-commit-message-keyword.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/workflow/finding-commits/search-by-commit-message-keyword.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/workflow/finding-commits/search-for-commits-by-author.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/workflow/finding-commits/search-for-commits-by-author.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/workflow/finding-commits/specify-a-commit-by-its-ancestry.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/workflow/finding-commits/specify-a-commit-by-its-ancestry.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/workflow/finding-commits/specify-a-range-of-commits-using-double-dot-syntax.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/workflow/finding-commits/specify-a-range-of-commits-using-double-dot-syntax.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/workflow/git-workflow-tips/avoiding-whitespace-issues.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/workflow/git-workflow-tips/avoiding-whitespace-issues.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/workflow/git-workflow-tips/cache-your-authentication-details-to-save-time.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/workflow/git-workflow-tips/cache-your-authentication-details-to-save-time.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/workflow/git-workflow-tips/custom-colour-options.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/workflow/git-workflow-tips/custom-colour-options.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/workflow/git-workflow-tips/overcome-line-ending-issues.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/workflow/git-workflow-tips/overcome-line-ending-issues.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/workflow/git-workflow-tips/sign-your-work-using-gpg.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/workflow/git-workflow-tips/sign-your-work-using-gpg.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/workflow/help/getting-help.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/workflow/help/getting-help.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/workflow/help/how-to-unstage-a-staged-file.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/workflow/help/how-to-unstage-a-staged-file.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/workflow/help/modifying-a-previous-commit.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/workflow/help/modifying-a-previous-commit.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/workflow/help/recover-lost-code.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/workflow/help/recover-lost-code.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/workflow/help/undo-a-committed-snapshot.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/workflow/help/undo-a-committed-snapshot.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/workflow/logging/limiting-log-output-by-time.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/workflow/logging/limiting-log-output-by-time.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/workflow/logging/logging.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/workflow/logging/logging.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/workflow/logging/make-your-log-output-pretty.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/workflow/logging/make-your-log-output-pretty.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/workflow/logging/show-history-of-a-function.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/workflow/logging/show-history-of-a-function.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/workflow/logging/view-your-commit-history-in-a-graph.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/workflow/logging/view-your-commit-history-in-a-graph.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/workflow/merges/merging-under-the-hood.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/workflow/merges/merging-under-the-hood.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/workflow/merges/rebasing.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/workflow/merges/rebasing.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/workflow/merges/remember-the-results-of-previous-hunk-conflicts.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/workflow/merges/remember-the-results-of-previous-hunk-conflicts.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/workflow/merges/solving-basic-merge-conflicts.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/workflow/merges/solving-basic-merge-conflicts.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/workflow/merges/the-golden-rule-of-rebasing.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/workflow/merges/the-golden-rule-of-rebasing.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/workflow/staging-i/intent-to-add.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/workflow/staging-i/intent-to-add.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/workflow/staging-i/interactive-staging.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/workflow/staging-i/interactive-staging.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/workflow/staging-i/interactively-stage-patches.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/workflow/staging-i/interactively-stage-patches.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/workflow/staging-i/interactively-unstage-changes.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/workflow/staging-i/interactively-unstage-changes.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/workflow/staging-i/use-short-status-to-make-output-more-compact.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/workflow/staging-i/use-short-status-to-make-output-more-compact.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/workflow/staging-ii/create-a-new-branch-from-a-stash.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/workflow/staging-ii/create-a-new-branch-from-a-stash.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/workflow/staging-ii/delete-all-untracked-files.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/workflow/staging-ii/delete-all-untracked-files.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/workflow/staging-ii/stashing-changes.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/workflow/staging-ii/stashing-changes.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/workflow/staging-ii/untrack-a-directory-file-without-deleting-it.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/workflow/staging-ii/untrack-a-directory-file-without-deleting-it.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/workflow/staging-ii/useful-stashing-options.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/workflow/staging-ii/useful-stashing-options.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/workflow/work-smart/add-autocorrect-to-git.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/workflow/work-smart/add-autocorrect-to-git.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/workflow/work-smart/tracking-shorthands.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/workflow/work-smart/tracking-shorthands.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/workflow/work-smart/upstream-tracking-shorthand.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/workflow/work-smart/upstream-tracking-shorthand.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/workflow/work-smart/using-aliases-for-git-commands.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/workflow/work-smart/using-aliases-for-git-commands.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/workflow/work-smart/you-can-use-git-offline.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/workflow/work-smart/you-can-use-git-offline.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/workflow/workflow/general-github-workflow.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/workflow/workflow/general-github-workflow.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/workflow/workflow/git-hub.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/workflow/workflow/git-hub.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/workflow/workflow/squashing-commits.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/workflow/workflow/squashing-commits.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/workflow/workflow/workflow-long-running-branches.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/workflow/workflow/workflow-long-running-branches.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)
- [ ] [enkidevs/curriculum/git/workflow/workflow/workflow-topic-branches.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/git/workflow/workflow/workflow-topic-branches.md?ref=e48111ee57e2f7074bc685a91508f02036d4b28b)

**Comment by enki-hq** [comment]
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| what-is-a-checksum | Link checking took too long. Verify it manually. |
| let-s-play-the-blame-game | Link checking took too long. Verify it manually. |
| revision-tools | Link checking took too long. Verify it manually. |
| how-does-git-work | Link checking took too long. Verify it manually. |
| the-git-working-tree | Link checking took too long. Verify it manually. |
| cache-your-authentication-details-to-save-time | Link checking took too long. Verify it manually. |
| remember-the-results-of-previous-hunk-conflicts | Link checking took too long. Verify it manually. |
| the-golden-rule-of-rebasing | Link checking took too long. Verify it manually. |
| interactive-staging | Link checking took too long. Verify it manually. |
| interactively-stage-patches | Link checking took too long. Verify it manually. |
| create-a-new-branch-from-a-stash | Link checking took too long. Verify it manually. |
| stashing-changes | Link checking took too long. Verify it manually. |
| useful-stashing-options | Link checking took too long. Verify it manually. |
| tracking-shorthands | Link checking took too long. Verify it manually. |
| upstream-tracking-shorthand | Link checking took too long. Verify it manually. |
| using-aliases-for-git-commands | Link checking took too long. Verify it manually. |
| workflow-long-running-branches | Link checking took too long. Verify it manually. |
| workflow-topic-branches | Link checking took too long. Verify it manually. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Review by kapnobatai137 — APPROVED** [review]

**Pull request merged**
