### PR TITLE
Add csharp

### PR DESCRIPTION
**Pull request by LiorB-D**

### CODE REVIEW

**Comment by enki-hq** [comment]
### Workout

| Workout Name | Error Message |
|:-:|:-:|
| intro-to-csharp | Workout description must be a non-empty string. |
| logical-operators-csharp | Workout description must be a non-empty string. |
| more-data-types-csharp | Workout description must be a non-empty string. |
### Course

| Course Name | Error Message |
|:-:|:-:|
| csharp-core | Course is missing its description. |
### Topic

| Topic Name | Error Message |
|:-:|:-:|
| csharp | Topic color `null` is not valid hex |
| csharp | Topic description must be a non-empty string. |

> If you notice anything wrong with these rules contact content-team@enki.com.

**Comment by enki-hq** [comment]
### Topic

| Topic Name | Error Message |
|:-:|:-:|
| csharp | Topic color `#A278DB` does not conform to our HSV rules. Replace it with `#cca6ff`. |

> If you notice anything wrong with these rules contact content-team@enki.com.

**Comment by enki-hq** [comment]
### Insight previews:
- [ ] [enkidevs/curriculum/csharp/csharp-core/control-flow-i-csharp/comparison-operators-csharp.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/csharp/csharp-core/control-flow-i-csharp/comparison-operators-csharp.md?ref=7e634dff278f8323ca8b627ca14b248967c32728)
- [ ] [enkidevs/curriculum/csharp/csharp-core/control-flow-i-csharp/if-else-statements-csharp.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/csharp/csharp-core/control-flow-i-csharp/if-else-statements-csharp.md?ref=7e634dff278f8323ca8b627ca14b248967c32728)
- [ ] [enkidevs/curriculum/csharp/csharp-core/control-flow-i-csharp/if-statements-csharp.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/csharp/csharp-core/control-flow-i-csharp/if-statements-csharp.md?ref=7e634dff278f8323ca8b627ca14b248967c32728)
- [ ] [enkidevs/curriculum/csharp/csharp-core/control-flow-i-csharp/nested-if-else-csharp.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/csharp/csharp-core/control-flow-i-csharp/nested-if-else-csharp.md?ref=7e634dff278f8323ca8b627ca14b248967c32728)
- [ ] [enkidevs/curriculum/csharp/csharp-core/intro-to-csharp/first-program-csharp.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/csharp/csharp-core/intro-to-csharp/first-program-csharp.md?ref=7e634dff278f8323ca8b627ca14b248967c32728)
- [ ] [enkidevs/curriculum/csharp/csharp-core/intro-to-csharp/installing-csharp-locally.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/csharp/csharp-core/intro-to-csharp/installing-csharp-locally.md?ref=7e634dff278f8323ca8b627ca14b248967c32728)
- [ ] [enkidevs/curriculum/csharp/csharp-core/intro-to-csharp/what-is-csharp.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/csharp/csharp-core/intro-to-csharp/what-is-csharp.md?ref=7e634dff278f8323ca8b627ca14b248967c32728)
- [ ] [enkidevs/curriculum/csharp/csharp-core/intro-to-csharp/why-learn-csharp.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/csharp/csharp-core/intro-to-csharp/why-learn-csharp.md?ref=7e634dff278f8323ca8b627ca14b248967c32728)
- [ ] [enkidevs/curriculum/csharp/csharp-core/logical-operators-csharp/and-csharp.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/csharp/csharp-core/logical-operators-csharp/and-csharp.md?ref=7e634dff278f8323ca8b627ca14b248967c32728)
- [ ] [enkidevs/curriculum/csharp/csharp-core/logical-operators-csharp/not-csharp.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/csharp/csharp-core/logical-operators-csharp/not-csharp.md?ref=7e634dff278f8323ca8b627ca14b248967c32728)
- [ ] [enkidevs/curriculum/csharp/csharp-core/logical-operators-csharp/or-csharp.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/csharp/csharp-core/logical-operators-csharp/or-csharp.md?ref=7e634dff278f8323ca8b627ca14b248967c32728)
- [ ] [enkidevs/curriculum/csharp/csharp-core/logical-operators-csharp/what-are-logical-operators-csharp.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/csharp/csharp-core/logical-operators-csharp/what-are-logical-operators-csharp.md?ref=7e634dff278f8323ca8b627ca14b248967c32728)
- [ ] [enkidevs/curriculum/csharp/csharp-core/logical-operators-csharp/xor-csharp.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/csharp/csharp-core/logical-operators-csharp/xor-csharp.md?ref=7e634dff278f8323ca8b627ca14b248967c32728)
- [ ] [enkidevs/curriculum/csharp/csharp-core/looping-csharp/do-while-loops-csharp.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/csharp/csharp-core/looping-csharp/do-while-loops-csharp.md?ref=7e634dff278f8323ca8b627ca14b248967c32728)
- [ ] [enkidevs/curriculum/csharp/csharp-core/looping-csharp/for-loops-csharp.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/csharp/csharp-core/looping-csharp/for-loops-csharp.md?ref=7e634dff278f8323ca8b627ca14b248967c32728)
- [ ] [enkidevs/curriculum/csharp/csharp-core/looping-csharp/what-are-loops-csharp.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/csharp/csharp-core/looping-csharp/what-are-loops-csharp.md?ref=7e634dff278f8323ca8b627ca14b248967c32728)
- [ ] [enkidevs/curriculum/csharp/csharp-core/looping-csharp/while-loops-csharp.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/csharp/csharp-core/looping-csharp/while-loops-csharp.md?ref=7e634dff278f8323ca8b627ca14b248967c32728)
- [ ] [enkidevs/curriculum/csharp/csharp-core/more-data-types-csharp/array-methods-csharp.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/csharp/csharp-core/more-data-types-csharp/array-methods-csharp.md?ref=7e634dff278f8323ca8b627ca14b248967c32728)
- [ ] [enkidevs/curriculum/csharp/csharp-core/more-data-types-csharp/arrays-csharp.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/csharp/csharp-core/more-data-types-csharp/arrays-csharp.md?ref=7e634dff278f8323ca8b627ca14b248967c32728)
- [ ] [enkidevs/curriculum/csharp/csharp-core/more-data-types-csharp/for-each-csharp.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/csharp/csharp-core/more-data-types-csharp/for-each-csharp.md?ref=7e634dff278f8323ca8b627ca14b248967c32728)
- [ ] [enkidevs/curriculum/csharp/csharp-core/more-data-types-csharp/list-methods-csharp.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/csharp/csharp-core/more-data-types-csharp/list-methods-csharp.md?ref=7e634dff278f8323ca8b627ca14b248967c32728)
- [ ] [enkidevs/curriculum/csharp/csharp-core/more-data-types-csharp/lists-csharp.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/csharp/csharp-core/more-data-types-csharp/lists-csharp.md?ref=7e634dff278f8323ca8b627ca14b248967c32728)
- [ ] [enkidevs/curriculum/csharp/csharp-core/variables-and-data-types-csharp/assignment-operators-csharp.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/csharp/csharp-core/variables-and-data-types-csharp/assignment-operators-csharp.md?ref=7e634dff278f8323ca8b627ca14b248967c32728)
- [ ] [enkidevs/curriculum/csharp/csharp-core/variables-and-data-types-csharp/basic-data-types-csharp-ii.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/csharp/csharp-core/variables-and-data-types-csharp/basic-data-types-csharp-ii.md?ref=7e634dff278f8323ca8b627ca14b248967c32728)
- [ ] [enkidevs/curriculum/csharp/csharp-core/variables-and-data-types-csharp/basic-data-types-csharp-iii.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/csharp/csharp-core/variables-and-data-types-csharp/basic-data-types-csharp-iii.md?ref=7e634dff278f8323ca8b627ca14b248967c32728)
- [ ] [enkidevs/curriculum/csharp/csharp-core/variables-and-data-types-csharp/basic-data-types-csharp-iv.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/csharp/csharp-core/variables-and-data-types-csharp/basic-data-types-csharp-iv.md?ref=7e634dff278f8323ca8b627ca14b248967c32728)
- [ ] [enkidevs/curriculum/csharp/csharp-core/variables-and-data-types-csharp/basic-data-types-csharp.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/csharp/csharp-core/variables-and-data-types-csharp/basic-data-types-csharp.md?ref=7e634dff278f8323ca8b627ca14b248967c32728)
- [ ] [enkidevs/curriculum/csharp/csharp-core/variables-and-data-types-csharp/creating-and-storing-variables-in-csharp.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/csharp/csharp-core/variables-and-data-types-csharp/creating-and-storing-variables-in-csharp.md?ref=7e634dff278f8323ca8b627ca14b248967c32728)
- [ ] [enkidevs/curriculum/csharp/csharp-core/variables-and-data-types-csharp/printing-variables-in-csharp.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/csharp/csharp-core/variables-and-data-types-csharp/printing-variables-in-csharp.md?ref=7e634dff278f8323ca8b627ca14b248967c32728)

**Comment by enki-hq** [comment]
### Workout

| Workout Name | Error Message |
|:-:|:-:|
| first-csharp-program | One of the mentioned insights couldn't be found in this pull request or the database. |
| intro-to-csharp | One of the mentioned insights couldn't be found in this pull request or the database. |
| variables-csharp | One of the mentioned insights couldn't be found in this pull request or the database. |
### Course

| Course Name | Error Message |
|:-:|:-:|
| csharp-core | We couldn't find these workouts: `variables-and-data-types-csharp`, `more-data-types-csharp`. |

> If you notice anything wrong with these rules contact content-team@enki.com.

**Comment by enki-hq** [comment]
### Workout

| Workout Name | Error Message |
|:-:|:-:|
| first-csharp-program | One of the mentioned insights couldn't be found in this pull request or the database. |
### Topic

| Topic Name | Error Message |
|:-:|:-:|
| csharp | Topic should have at least one workout with the "workout" aspect. |

> If you notice anything wrong with these rules contact content-team@enki.com.

**Comment by enki-hq** [comment]
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| assumed-knowledge-pref | Insight slug `assumed-knowledge-preface` is not unique in the database. |
| what-is-xamarin | Insight has a practice question but it's missing the `practiceQuestion` metadata field. |

> If you notice anything wrong with these rules contact content-team@enki.com.

**Comment by enki-hq** [comment]
Failed parsing files: 
  - csharp/csharp-core/intro-to-csharp/what-is-xamarin.md: 
 > duplicated mapping key at line 6, column 1:
    category: must-know
    ^

**Comment by enki-hq** [comment]
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| csharp-projects | Insight doesn't have a practice question but it has formats and context for it. |
| first-program-csharp | Insight has a practice question but it's missing the `practiceQuestion` metadata field. |

> If you notice anything wrong with these rules contact content-team@enki.com.

**Comment by enki-hq** [comment]
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| nullable-vars-csharp | Insight doesn't have a practice question but it has formats and context for it. |

> If you notice anything wrong with these rules contact content-team@enki.com.

**Comment by enki-hq** [comment]
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| printing-variables-in-csharp | No footnote matches found in content. |

> If you notice anything wrong with these rules contact content-team@enki.com.

**Comment by enki-hq** [comment]
Failed parsing files: 
  - csharp/csharp-core/intro-to-csharp/first-program-csharp.md: 
 > Missing compiler for node of type `questionCode`: `[object Object]`

**Comment by enki-hq** [comment]
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| intro-csharp-frameworks | No Enki username has been found for this author. |

> If you notice anything wrong with these rules contact content-team@enki.com.

**Comment by enki-hq** [comment]
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| intro-csharp-frameworks | No Enki username has been found for this author. |

> If you notice anything wrong with these rules contact content-team@enki.com.

**Comment by enki-hq** [comment]
Failed parsing files: 
  - csharp/csharp-core/csharp-frameworks/what-is-unity.md: 
 > a line break is expected at line 8, column 8:
      - >- [Unity](https://unity.com/){website}
           ^
  - csharp/csharp-core/csharp-frameworks/what-is-xamarin.md: 
 > bad indentation of a mapping entry at line 8, column 3:
      [Xamarin](https://dotnet.microso ... 
      ^

**Comment by enki-hq** [comment]
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| what-is-xamarin | <ul><li>`Xamarin` pointing to `https://dotnet.microsoft.com/en-us/apps/xamarin` is broken because `HTTP_403`</li></ul> |
| what-is-blazor | <ul><li>`Blazor` pointing to `https://dotnet.microsoft.com/en-us/apps/aspnet/web-apps/blazor` is broken because `HTTP_403`</li></ul> |
| what-is-unity | <ul><li>`Unity` pointing to `https://unity.com/` is broken because `HTTP_403`</li></ul> |

> If you notice anything wrong with these rules contact content-team@enki.com.

**Comment by enki-hq** [comment]
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| what-is-xamarin | <ul><li>`Xamarin` pointing to `https://dotnet.microsoft.com/en-us/apps/xamarin` is broken because `HTTP_403`</li></ul> |
| what-is-blazor | <ul><li>`Blazor` pointing to `https://dotnet.microsoft.com/en-us/apps/aspnet/web-apps/blazor` is broken because `HTTP_403`</li></ul> |
| what-is-unity | <ul><li>`Unity` pointing to `https://unity.com/` is broken because `HTTP_403`</li></ul> |

> If you notice anything wrong with these rules contact content-team@enki.com.

**Comment by enki-hq** [comment]
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| what-is-xamarin | <ul><li>`Xamarin` pointing to `https://dotnet.microsoft.com/en-us/apps/xamarin` is broken because `HTTP_403`</li></ul> |
| what-is-blazor | <ul><li>`Blazor` pointing to `https://dotnet.microsoft.com/en-us/apps/aspnet/web-apps/blazor` is broken because `HTTP_403`</li></ul> |
| what-is-unity | <ul><li>`Unity` pointing to `https://unity.com/` is broken because `HTTP_403`</li></ul> |

> If you notice anything wrong with these rules contact content-team@enki.com.

**Comment by enki-hq** [comment]
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| what-is-blazor | <ul><li>`Blazor` pointing to `https://dotnet.microsoft.com/en-us/apps/aspnet/web-apps/blazor` is broken because `HTTP_403`</li></ul> |
| what-is-xamarin | <ul><li>`Xamarin` pointing to `https://dotnet.microsoft.com/en-us/apps/xamarin` is broken because `HTTP_403`</li></ul> |
| what-is-unity | <ul><li>`Unity` pointing to `https://unity.com/` is broken because `HTTP_403`</li></ul> |

> If you notice anything wrong with these rules contact content-team@enki.com.

**Comment by enki-hq** [comment]
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| what-is-xamarin | <ul><li>`Xamarin` pointing to `https://dotnet.microsoft.com/en-us/apps/xamarin` is broken because `HTTP_403`</li></ul> |
| what-is-blazor | <ul><li>`Blazor` pointing to `https://dotnet.microsoft.com/en-us/apps/aspnet/web-apps/blazor` is broken because `HTTP_403`</li></ul> |
| what-is-unity | <ul><li>`Unity` pointing to `https://unity.com/` is broken because `HTTP_403`</li></ul> |

> If you notice anything wrong with these rules contact content-team@enki.com.

**Comment by enki-hq** [comment]
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| what-is-blazor | <ul><li>`Blazor` pointing to `https://dotnet.microsoft.com/en-us/apps/aspnet/web-apps/blazor` is broken because `HTTP_403`</li></ul> |
| what-is-xamarin | <ul><li>`Xamarin` pointing to `https://dotnet.microsoft.com/en-us/apps/xamarin` is broken because `HTTP_403`</li></ul> |
| what-is-unity | <ul><li>`Unity` pointing to `https://unity.com/` is broken because `HTTP_403`</li></ul> |

> If you notice anything wrong with these rules contact content-team@enki.com.

**Review by nem035 — APPROVED** [review]

**Pull request merged**
