### PR TITLE
Update inversion-of-control.md

### PR DESCRIPTION
**Pull request by nem035**

### CODE REVIEW

**Comment by enki-hq** [comment]
Failed parsing files: 
  - javascript/ecmascript-2015/async-tips/inversion-of-control.md: 
 > 	duplicated mapping key at line 19, column -7:
    links:
    ^

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Insight previews:
- [ ] [enkidevs/curriculum/javascript/ecmascript-2015/async-tips/inversion-of-control.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/ecmascript-2015/async-tips/inversion-of-control.md?ref=8aa7843a99f928522db146e6b16e5210a45b3148)

**Review by kapnobatai137 — APPROVED** [review]
:rocket:

**Pull request merged**
