### PR TITLE
Fixed inconsistencies in code blocks

### PR DESCRIPTION
**Pull request by milesflo**

### CODE REVIEW

**Comment by enki-hq** [comment]
Rule insight:levels failed for files: 
  - javascript/node/best-practices/process-env-performance.md

**Comment by enki-hq** [comment]
Rule insight:quiz failed for files: 
  - javascript/node/code-style-recommendations/styling-brackets.md

**Comment by Loopiezlol** [comment]
awesome work @milesflo

**Comment by Loopiezlol** [comment]
will fix the validators myself and push this. hope you don't mind

**Comment by enki-hq** [comment]
bad indentation of a sequence entry at line 16, column 9:
      - '{\'pi\': 3.14}'
            ^

**Comment by enki-hq** [comment]
### Insight previews:
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/java/data-management/data-structures-implementation/difference-between-hashmap-and-hashtable.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/java/data-management/file-system-iii/jjs-oracle-nashorn-newest-javascript-engine.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/java/fundamentals/annotations-ii/use-javadoc-comments-to-describe-the-purpose-of-a-class-or-method.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/java/fundamentals/java-basics/java-strings.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/java/fundamentals/modifiers/the-final-modifier.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/java/fundamentals/operators-ii/equals-operation-on-different-data-types.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/java/threading/multithreading/thread-sleep-and-thread-yield-do-not-have-synchronization-mechanisms.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/browser-apis/measuring-performance/progress-event.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/browser-apis/reading-writing/blobs.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/browser-apis/reading-writing/filereader-readasarraybuffer.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/browser-apis/reading-writing/filereader-readasdataurl.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/browser-apis/reading-writing/filereader-readastext.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/browser-apis/reading-writing/window-localstorage.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/browser-apis/toolbox-i/geolocation.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/browser-apis/toolbox-i/page-visibility-api.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/browser-apis/toolbox-ii/fetch-api.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/browser-apis/toolbox-ii/network-information-api.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/browser-apis/user-interaction/drag-and-drop-api.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/browser-apis/user-interaction/mediadevices-getusermedia.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/browser-apis/user-interaction/social-sharing-without-widgets.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/core/array-methods/how-to-merge-two-arrays.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/core/arrays/arrays.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/core/async-tips/using-timers-with-extra-arguments.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/core/errors/debugging.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/core/flow-control/data-type-comparison-in-switch-statements.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/core/functions-iii/changing-a-functions-context-with-fn-call-object.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/core/functions-iii/difference-between-call-and-apply-methods.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/core/functions-iii/function-call-method.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/core/recipes-i/using-the-double-tilde.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/node/best-practices/process-env-performance.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/node/code-style-recommendations/styling-brackets.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/node/express-ii/vhost-in-express.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/node/intro-node/npm-nodes-package-manager.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/node/modules/exports-vs-module-exports-in-node.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/node/operational-vs-programmer-errors/handling-operational-errors.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/node/operational-vs-programmer-errors/operational-vs-programmer-errors.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/node/quirks/node-os-module.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/npm/packages-modules/private-packages.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/react/basics-ii/conditional-rendering-part-1.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/react/good-to-know/load-initial-data-via-ajax.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/react/props-ii/dealing-with-this-props-children.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/react/props-ii/props-in-getinitialstate-is-an-anti-pattern.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/react/props-ii/type-of-the-children-props.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/javascript/react/props-iii/componentwillreceiveprops-not-triggered-after-mounting.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/linux/jobs-and-processes-data-manipulation/basics-process-management/listing-processes-using-ps.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/linux/jobs-and-processes-data-manipulation/basics-process-management/stopping-processes-with-kill-and-killall.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/linux/jobs-and-processes-data-manipulation/basics-process-management/the-process-tree.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/linux/jobs-and-processes-data-manipulation/crontab/crontab-newline-issue.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/linux/jobs-and-processes-data-manipulation/crontab/fixing-the-shell-in-cron.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/linux/jobs-and-processes-data-manipulation/data-manipulation-recipes/clean-configuration-files.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/linux/jobs-and-processes-data-manipulation/file-streams/paging-through-long-output-using-less.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/linux/jobs-and-processes-data-manipulation/file-streams/selecting-portions-of-a-line-using-cut.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/linux/jobs-and-processes-data-manipulation/file-streams/the-awk-programming-language-and-awk-command.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/linux/jobs-and-processes-data-manipulation/file-streams/the-head-and-tail-commands.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/linux/jobs-and-processes-data-manipulation/file-streams/transforming-text-with-sed.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/linux/networking-and-security/basics-networking/diagnosing-network-problems-with-traceroute.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/linux/networking-and-security/basics-networking/the-loopback-network-interface-lo.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/linux/networking-and-security/basics-networking/using-curl-to-make-http-requests.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/linux/networking-and-security/basics-networking/using-ping-to-measure-network-latency.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/linux/networking-and-security/basics-networking/what-is-a-network-interface.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/linux/networking-and-security/ssh-connections/breaking-out-of-a-terminal-when-ssh-locks.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/linux/networking-and-security/ssh-connections/staying-connected-remotely-via-ssh-without-an-interactive-shell.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/linux/system-and-package-management/disk-time-management/using-dd-to-create-disk-images.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/linux/system-and-package-management/system-monitoring-ii/finding-open-files-with-lsof.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/linux/user-and-file-management/bash-environment/manipulating-environment-variables.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/linux/user-and-file-management/bash-environment/understanding-the-path-environment-variable.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/linux/user-and-file-management/bash-environment/what-are-environment-variables.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/linux/user-and-file-management/file-management/matching-multiple-files-with-wildcards.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/linux/user-and-file-management/file-management/using-find-to-search-by-file-size.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/linux/user-and-file-management/file-management/using-find-to-search-by-filename.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/linux/user-and-file-management/file-management/using-which-to-find-executables.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/linux/user-and-file-management/pipelines/appending-output-with.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/linux/user-and-file-management/pipelines/input-and-output-redirection-with-and.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/linux/user-and-file-management/pipelines/the-basics-of-command-substitution.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/linux/user-and-file-management/pipelines/the-basics-of-the-pipe-operator.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/linux/user-and-file-management/shell/the-basics-of-environment-variables.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/linux/user-and-file-management/shell/what-is-a-shell.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/linux/user-and-file-management/terminal-history/keep-useful-commands-in-your-shell-history-with-tags.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/linux/user-and-file-management/user-management-utilities/best-password-generation-utilities.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/linux/user-and-file-management/user-management-utilities/random-password-generator.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/linux/user-and-file-management/user-management/adding-new-users-with-useradd.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/linux/user-and-file-management/user-management/changing-user-passwords-with-passwd.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/linux/user-and-file-management/user-permissions/changing-file-ownership-with-chown.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/linux/user-and-file-management/user-permissions/changing-file-permissions-with-chmod.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/linux/user-and-file-management/user-permissions/changing-group-membership-with-usermod.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/linux/user-and-file-management/user-permissions/file-ownership.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/linux/user-and-file-management/user-permissions/users-and-groups-on-linux.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/python/core/advanced-queues/special-queue-methods.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/python/core/basic-file-manipulation/how-to-open-a-file-object.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/python/core/basic-file-manipulation/i-o-functions.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/python/core/basic-file-manipulation/other-operations-on-files.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/python/core/basic-file-manipulation/reading-from-files.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/python/core/bits-bytes-hexadecimals/get-the-most-of-float-s.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/python/core/bits-bytes-hexadecimals/get-the-most-of-int-s.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/python/core/classes-i/method-overriding.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/python/core/fundamental-data-structures/variables-and-types.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/python/core/intro-to-modules/namespace-and-scoping.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/python/core/intro-to-modules/python-packages.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/python/core/intro-to-modules/the-from-import-statement.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/python/core/intro-to-modules/the-import-statement.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/python/core/intro-to-modules/what-are-modules.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/python/core/is-your-python-healthy/python-debugger.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/python/core/more-on-sets/mixing-sets-and-frozensets.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/python/core/playing-with-time/datetime-module.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/python/core/playing-with-time/datetime-object.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/python/core/playing-with-time/playing-with-time.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/python/core/playing-with-time/time-object.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/python/core/playing-with-time/timedelta-object.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/python/core/tips/exiting-the-interpreter.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/python/core/utilities-i/check-available-python-modules.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/python/core/working-with-strings/pythonic-substring-testing.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/python/functional-programming/decorators/decorators-syntax.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/python/functional-programming/decorators/what-are-decorators.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/python/functional-programming/immutability/distinguish-the-mutability-of-common-types.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/python/functional-programming/iterators/the-iteration-protocol.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/python/functional-programming/iterators/the-itertools-module.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/sql/ddl/data-types/add-support-for-other-character-sets.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/sql/ddl/data-types/sql-numeric-data-types.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/sql/ddl/data-types/sql-string-data-types.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/sql/ddl/storing-blobs/storing-blobs-in-mssql.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/sql/ddl/storing-blobs/storing-blobs-in-mysql.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/sql/ddl/storing-blobs/storing-blobs-in-psql.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/sql/ddl/storing-json/storing-json-in-an-rdbms.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/sql/ddl/storing-json/storing-json-in-mssql.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/sql/ddl/storing-json/storing-json-in-mysql.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/sql/ddl/storing-json/storing-json-in-postgresql.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/sql/dql/joins/full-join.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/sql/dql/joins/inner-join.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/sql/dql/joins/left-and-right-joins.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/sql/dql/joins/multiple-joins.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/sql/dql/joins/union.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/sql/dql/write/insert.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/web/html-and-css-basics/pseudo-elements/styling-elements-using-before-and-after.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/web/styling/sass-i/rules-and-directives.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/web/styling/sass-i/sass-supported-comments.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/web/styling/sass-ii/referencing-parent-selectors.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/web/styling/sass-ii/sass-extend-inheritance.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/web/styling/sass-ii/sass-mixins.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/web/styling/sass-ii/using-sassscripts-interactive-shell.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/web/styling/sass-iii/sassscript-color-operations.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/web/styling/sass-iii/sassscript-map-and-list-functions.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/web/styling/sass-iii/sassscript-number-functions.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/web/styling/sass-iii/sassscript-string-operations.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/web/styling/styling-i/use-list-style-type-to-change-the-marker-type-in-lists.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/web/styling/styling-ii/use-background-repeat-to-repeat-a-background-image-horizontally-or-vertically.md?ref=dad85fddd313610b59564fc09e63a5dabbbb85eb

**Comment by Loopiezlol** [comment]
for some reason, this failed on our backend getting a 403 on a specific insight, although some of them were updated. i'm going to retrigger changes on insights and push again

**Pull request merged**
