### PR TITLE
Remove broken links from Web/Html insights

### PR DESCRIPTION
**Pull request by Stefan-Stojanovic**

### CODE REVIEW

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Insight previews:
- [ ] [enkidevs/curriculum/web/html/html-images/html-image-2-codepen-exercise.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/web/html/html-images/html-image-2-codepen-exercise.md?ref=a3f0d196eecc17f25e9f36106952d027dce5f98d)
- [ ] [enkidevs/curriculum/web/html/html-images/html-image-3-codepen-exercise.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/web/html/html-images/html-image-3-codepen-exercise.md?ref=a3f0d196eecc17f25e9f36106952d027dce5f98d)
- [ ] [enkidevs/curriculum/web/html/html-images/html-image-map-codepen-exercise.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/web/html/html-images/html-image-map-codepen-exercise.md?ref=a3f0d196eecc17f25e9f36106952d027dce5f98d)
- [ ] [enkidevs/curriculum/web/html/html-images/image-alt.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/web/html/html-images/image-alt.md?ref=a3f0d196eecc17f25e9f36106952d027dce5f98d)

**Review by kapnobatai137 — APPROVED** [review]

**Pull request merged**
