### PR TITLE
Replace old note format with emoji one git

### PR DESCRIPTION
**Pull request by Stefan-Stojanovic**

### CODE REVIEW

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Insight previews:
- [ ] [enkidevs/curriculum/git/essentials/branching/fetching-a-remote-branch.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/git/essentials/branching/fetching-a-remote-branch.md?ref=de9f20f48983ea6309fa3a9fb545b969b82d6f9f)
- [ ] [enkidevs/curriculum/git/essentials/dummy-workout/remote-repositories-fetching-and-pushing.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/git/essentials/dummy-workout/remote-repositories-fetching-and-pushing.md?ref=de9f20f48983ea6309fa3a9fb545b969b82d6f9f)
- [ ] [enkidevs/curriculum/git/essentials/git-features-ii/dates-in-git.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/git/essentials/git-features-ii/dates-in-git.md?ref=de9f20f48983ea6309fa3a9fb545b969b82d6f9f)
- [ ] [enkidevs/curriculum/git/workflow/branches/viewing-your-tracking-branches.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/git/workflow/branches/viewing-your-tracking-branches.md?ref=de9f20f48983ea6309fa3a9fb545b969b82d6f9f)
- [ ] [enkidevs/curriculum/git/workflow/git-workflow-tips/sign-your-work-using-gpg.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/git/workflow/git-workflow-tips/sign-your-work-using-gpg.md?ref=de9f20f48983ea6309fa3a9fb545b969b82d6f9f)

**Review by kapnobatai137 — APPROVED** [review]
:rocket:

**Pull request merged**
