### PR TITLE
Added SVG image to Workout

### PR DESCRIPTION
**Pull request by matthewleach**

### CODE REVIEW

**Comment by enki-hq** [comment]
### Insight previews:
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/web/html/best-practices/alt-with-images.md?ref=c8525feb383471e123ea003933adb787283de005

**Comment by enki-hq** [comment]
Rule insight:code-width failed for files: 
  - web/html/best-practices/quote-attribute-values.md

**Comment by matthewleach** [comment]
Changed image width from pixels to 100%

**Comment by enki-hq** [comment]
Rule insight:questions failed for files: 
  - web/html/core-html-elements/update-hyperlinks.md

**Comment by enki-hq** [comment]
Rule insight:questions failed for files: 
  - web/html/core-html-elements/update-hyperlinks.md

**Comment by enki-hq** [comment]
Rule insight:questions failed for files: 
  - web/html/core-html-elements/update-hyperlinks.md

**Comment by enki-hq** [comment]
Rule insight:questions failed for files: 
  - web/html/core-html-elements/update-hyperlinks.md

**Comment by enki-hq** [comment]
Rule insight:questions failed for files: 
  - web/html/core-html-elements/update-hyperlinks.md

**Comment by enki-hq** [comment]
Rule insight:questions failed for files: 
  - web/html/core-html-elements/update-hyperlinks.md

**Comment by lizTheDeveloper** [comment]
💯 🎉

**Pull request merged**
