### PR TITLE
update webpage-structure

### PR DESCRIPTION
**Pull request by Stefan-Stojanovic**

### CODE REVIEW

**Comment by enki-hq** [comment]
### Insight previews:
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/Web/HTML/web-page-structure/head-element.md?ref=e80266b6fb707471d8e96d53745d6837768d0539

**Comment by enki-hq** [comment]
Rule insight:quiz failed for files: 
  - Web/HTML/web-page-structure/optional-elements.md

**Comment by enki-hq** [comment]
Rule insight:quiz failed for files: 
  - Web/HTML/web-page-structure/optional-elements.md

**Comment by enki-hq** [comment]
Rule insight:quiz failed for files: 
  - Web/HTML/web-page-structure/optional-elements.md

**Comment by enki-hq** [comment]
Failed parsing files: 
  - Web/HTML/web-page-structure/doctype.md: 
 > Must have exactly 1 headline but found 0 instead.

**Comment by enki-hq** [comment]
Failed parsing files: 
  - Web/HTML/web-page-structure/doctype.md: 
 > Must have exactly 1 headline but found 0 instead.

**Comment by enki-hq** [comment]
Failed parsing files: 
  - Web/HTML/web-page-structure/doctype.md: 
 > Must have exactly 1 headline but found 0 instead.

**Comment by enki-hq** [comment]
Failed parsing files: 
  - Web/HTML/web-page-structure/doctype.md: 
 > Must have exactly 1 headline but found 0 instead.

**Comment by lizTheDeveloper** [comment]
This has been migrated to #766

**Pull request closed without merging**
