### PR TITLE
add js playground questions

### PR DESCRIPTION
**Pull request by Stefan-Stojanovic**

### CODE REVIEW

**Comment by enki-hq** [comment]
### Workout

| Workout Name | Error Message |
|:-:|:-:|
| sum-arrays-in-a-object | One of the mentioned insights couldn't be found in this pull request or the database. |
### Course

| Course Name | Error Message |
|:-:|:-:|
| javascript-playground-questions | Topic has more than one core course. |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Workout

| Workout Name | Error Message |
|:-:|:-:|
| sum-arrays-in-a-object | One of the mentioned insights couldn't be found in this pull request or the database. |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Workout

| Workout Name | Error Message |
|:-:|:-:|
| sum-arrays-in-a-object | One of the mentioned insights couldn't be found in this pull request or the database. |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Workout

| Workout Name | Error Message |
|:-:|:-:|
| sum-arrays-in-a-object | One of the mentioned insights couldn't be found in this pull request or the database. |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| beginning-and-end-pairs | No Enki username has been found for this author. |
### Workout

| Workout Name | Error Message |
|:-:|:-:|
| sum-arrays-in-a-object | One of the mentioned insights couldn't be found in this pull request or the database. |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| beginning-and-end-pairs | No Enki username has been found for this author. |
### Workout

| Workout Name | Error Message |
|:-:|:-:|
| sum-arrays-in-a-object | One of the mentioned insights couldn't be found in this pull request or the database. |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Workout

| Workout Name | Error Message |
|:-:|:-:|
| sum-arrays-in-a-object | One of the mentioned insights couldn't be found in this pull request or the database. |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Workout

| Workout Name | Error Message |
|:-:|:-:|
| sum-arrays-in-a-object | One of the mentioned insights couldn't be found in this pull request or the database. |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Insight previews:
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/adding-and-sorting-arrays/adding-and-sorting-arrays.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/adding-and-sorting-arrays/adding-and-sorting-arrays.md?ref=87dd7eb166ae9ca2981251e68c8e735df1f1ff8e)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/arithmetic-operation/arithmetic-operation.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/arithmetic-operation/arithmetic-operation.md?ref=87dd7eb166ae9ca2981251e68c8e735df1f1ff8e)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/array-of-characters-to-string/array-of-characters-to-string.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/array-of-characters-to-string/array-of-characters-to-string.md?ref=87dd7eb166ae9ca2981251e68c8e735df1f1ff8e)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/beginning-and-end-pairs/beginning-and-end-pairs.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/beginning-and-end-pairs/beginning-and-end-pairs.md?ref=87dd7eb166ae9ca2981251e68c8e735df1f1ff8e)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/calculator-class/calculator-class.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/calculator-class/calculator-class.md?ref=87dd7eb166ae9ca2981251e68c8e735df1f1ff8e)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/combine-objects/combine-objects.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/combine-objects/combine-objects.md?ref=87dd7eb166ae9ca2981251e68c8e735df1f1ff8e)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/dice-roll/dice-roll.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/dice-roll/dice-roll.md?ref=87dd7eb166ae9ca2981251e68c8e735df1f1ff8e)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/even-or-odd/even-or-odd.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/even-or-odd/even-or-odd.md?ref=87dd7eb166ae9ca2981251e68c8e735df1f1ff8e)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/factorial-calculator/factorial-calculator.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/factorial-calculator/factorial-calculator.md?ref=87dd7eb166ae9ca2981251e68c8e735df1f1ff8e)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/fibonacci-sequence/fibonacci-sequence.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/fibonacci-sequence/fibonacci-sequence.md?ref=87dd7eb166ae9ca2981251e68c8e735df1f1ff8e)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/happy-birthday/happy-birthday.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/happy-birthday/happy-birthday.md?ref=87dd7eb166ae9ca2981251e68c8e735df1f1ff8e)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/harmonic-series/harmonic-series.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/harmonic-series/harmonic-series.md?ref=87dd7eb166ae9ca2981251e68c8e735df1f1ff8e)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/iterate-over-object-values/iterate-over-object-values.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/iterate-over-object-values/iterate-over-object-values.md?ref=87dd7eb166ae9ca2981251e68c8e735df1f1ff8e)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/iterate-over-two-arrays/iterate-over-two-arrays.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/iterate-over-two-arrays/iterate-over-two-arrays.md?ref=87dd7eb166ae9ca2981251e68c8e735df1f1ff8e)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/least-frequent-character/least-frequent-character.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/least-frequent-character/least-frequent-character.md?ref=87dd7eb166ae9ca2981251e68c8e735df1f1ff8e)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/miles-to-kilometres/miles-to-kilometres.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/miles-to-kilometres/miles-to-kilometres.md?ref=87dd7eb166ae9ca2981251e68c8e735df1f1ff8e)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/multiplication-table/multiplication-table.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/multiplication-table/multiplication-table.md?ref=87dd7eb166ae9ca2981251e68c8e735df1f1ff8e)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/pascals-triangle/pascals-triangle.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/pascals-triangle/pascals-triangle.md?ref=87dd7eb166ae9ca2981251e68c8e735df1f1ff8e)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/print-primes/print-primes.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/print-primes/print-primes.md?ref=87dd7eb166ae9ca2981251e68c8e735df1f1ff8e)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/remove-duplicate-from-array/remove-duplicate-from-array.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/remove-duplicate-from-array/remove-duplicate-from-array.md?ref=87dd7eb166ae9ca2981251e68c8e735df1f1ff8e)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/remove-odd-numbers-from-array/remove-odd-numbers-from-array.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/remove-odd-numbers-from-array/remove-odd-numbers-from-array.md?ref=87dd7eb166ae9ca2981251e68c8e735df1f1ff8e)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/reverse-a-string/reverse-a-string.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/reverse-a-string/reverse-a-string.md?ref=87dd7eb166ae9ca2981251e68c8e735df1f1ff8e)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/smallest-array-element/smallest-array-element.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/smallest-array-element/smallest-array-element.md?ref=87dd7eb166ae9ca2981251e68c8e735df1f1ff8e)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/sort-arrays-in-a-object/sort-arrays-in-a-object.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/sort-arrays-in-a-object/sort-arrays-in-a-object.md?ref=87dd7eb166ae9ca2981251e68c8e735df1f1ff8e)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/squared-object-keys/squared-object-keys.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/squared-object-keys/squared-object-keys.md?ref=87dd7eb166ae9ca2981251e68c8e735df1f1ff8e)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/stopping-a-loop/stopping-a-loop.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/stopping-a-loop/stopping-a-loop.md?ref=87dd7eb166ae9ca2981251e68c8e735df1f1ff8e)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/string-length/string-length.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/string-length/string-length.md?ref=87dd7eb166ae9ca2981251e68c8e735df1f1ff8e)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/sum-and-product-of-two-arrays/sum-and-product-of-two-arrays.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/sum-and-product-of-two-arrays/sum-and-product-of-two-arrays.md?ref=87dd7eb166ae9ca2981251e68c8e735df1f1ff8e)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/sum-items-in-object/sum-items-in-object.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/sum-items-in-object/sum-items-in-object.md?ref=87dd7eb166ae9ca2981251e68c8e735df1f1ff8e)
- [ ] [enkidevs/curriculum/javascript/javascript-playground-questions/word-length/word-length.md](https://app.enki.com/public/preview-insight/enkidevs/curriculum/javascript/javascript-playground-questions/word-length/word-length.md?ref=87dd7eb166ae9ca2981251e68c8e735df1f1ff8e)

**Comment by enki-hq** [comment]
Failed parsing files: 
  - javascript/javascript-core/update-object-values-exercise/update-object-values-exercise.md: 
 > 	end of the stream or a document separator is expected at line 21, column 1:
    }; 
    ^

**Comment by enki-hq** [comment]
Failed parsing files: 
  - javascript/javascript-core/update-object-values-exercise/update-object-values-exercise.md: 
 > 	end of the stream or a document separator is expected at line 21, column 1:
    }; 
    ^

**Comment by enki-hq** [comment]
Failed parsing files: 
  - javascript/javascript-core/update-object-values-exercise/update-object-values-exercise.md: 
 > 	end of the stream or a document separator is expected at line 21, column 1:
    }; 
    ^

**Comment by enki-hq** [comment]
Failed parsing files: 
  - javascript/javascript-core/update-object-values-exercise/update-object-values-exercise.md: 
 > 	end of the stream or a document separator is expected at line 21, column 1:
    }; 
    ^

**Comment by enki-hq** [comment]
Failed parsing files: 
  - javascript/javascript-core/update-object-values-exercise/update-object-values-exercise.md: 
 > 	end of the stream or a document separator is expected at line 21, column 1:
    }; 
    ^

**Comment by enki-hq** [comment]
### Workout

| Workout Name | Error Message |
|:-:|:-:|
| object-combination | One of the mentioned insights couldn't be found in this pull request or the database. |
### Course

| Course Name | Error Message |
|:-:|:-:|
| javascript-playground-questions | We couldn't find these workouts: `combine-objects`. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Course

| Course Name | Error Message |
|:-:|:-:|
| javascript-playground-questions | We couldn't find these workouts: `combine-objects`. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Review by kapnobatai137 — APPROVED** [review]

**Comment by enki-hq** [comment]
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| arithmetic-operation | Insight slug `arithmetic-operation` is not unique in the database. |
| beginning-and-end-pairs | Insight slug `beginning-and-end-pairs` is not unique in the database. |
| calculator-class | Insight slug `calculator-class` is not unique in the database. |
| dice-roll | Insight slug `dice-roll` is not unique in the database. |
| even-or-odd | Insight slug `even-or-odd` is not unique in the database. |
| factorial-calculator | Insight slug `factorial-calculator` is not unique in the database. |
| fibonacci-sequence | Insight slug `fibonacci-sequence` is not unique in the database. |
| happy-birthday | Insight slug `happy-birthday` is not unique in the database. |
| harmonic-series | Insight slug `harmonic-series` is not unique in the database. |
| miles-to-kilometres | Insight slug `miles-to-kilometres` is not unique in the database. |
| least-frequent-character | Insight slug `least-frequent-character` is not unique in the database. |
| multiplication-table | Insight slug `multiplication-table` is not unique in the database. |
| pascals-triangle | Insight slug `pascals-triangle` is not unique in the database. |
| print-primes | Insight slug `print-primes` is not unique in the database. |
| reverse-a-string | Insight slug `reverse-a-string` is not unique in the database. |
| stopping-a-loop | Insight slug `stopping-a-loop` is not unique in the database. |
| string-length | Insight slug `string-length` is not unique in the database. |
| word-length | Insight slug `word-length` is not unique in the database. |
### Workout

| Workout Name | Error Message |
|:-:|:-:|
| arithmetic-operation | Workout slug `arithmetic-operation` isn't unique in the database. |
| beginning-and-end-pairs | Workout slug `beginning-and-end-pairs` isn't unique in the database. |
| calculator-class | Workout slug `calculator-class` isn't unique in the database. |
| dice-roll | Workout slug `dice-roll` isn't unique in the database. |
| even-or-odd | Workout slug `even-or-odd` isn't unique in the database. |
| factorial-calculator | Workout slug `factorial-calculator` isn't unique in the database. |
| fibonacci-sequence | Workout slug `fibonacci-sequence` isn't unique in the database. |
| happy-birthday | Workout slug `happy-birthday` isn't unique in the database. |
| harmonic-series | Workout slug `harmonic-series` isn't unique in the database. |
| least-frequent-character | Workout slug `least-frequent-character` isn't unique in the database. |
| miles-to-kilometres | Workout slug `miles-to-kilometres` isn't unique in the database. |
| multiplication-table | Workout slug `multiplication-table` isn't unique in the database. |
| pascals-triangle | Workout slug `pascals-triangle` isn't unique in the database. |
| print-primes | Workout slug `print-primes` isn't unique in the database. |
| reverse-a-string | Workout slug `reverse-a-string` isn't unique in the database. |
| stopping-a-loop | Workout slug `stopping-a-loop` isn't unique in the database. |
| string-length | Workout slug `string-length` isn't unique in the database. |
| word-length | Workout slug `word-length` isn't unique in the database. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Review by kapnobatai137 — APPROVED** [review]
:rocket:

**Pull request merged**
