### PR TITLE
Add 5 new Python quizzes

### PR DESCRIPTION
**Pull request by stefkn**
Did some stuff! Still need to fix a thing!

### CODE REVIEW

**Comment by enki-hq** [comment]
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/Python/Core/classes-i/python-inheritance.md?ref=243b6cac6586bb9708304255be9fbe005cc9c1d8
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/Python/Core/classes-ii/private-variables.md?ref=243b6cac6586bb9708304255be9fbe005cc9c1d8
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/Python/Core/functions/nested-functions.md?ref=243b6cac6586bb9708304255be9fbe005cc9c1d8
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/Python/Core/is-your-python-healthy/exception-handling.md?ref=243b6cac6586bb9708304255be9fbe005cc9c1d8
- [ ] https://enkipro.com/preview-insight/enkidevs/curriculum/Python/Core/tips/chain-comparison-operators.md?ref=243b6cac6586bb9708304255be9fbe005cc9c1d8

**Comment by lizTheDeveloper** [comment]
@milesflo can you fix the yaml on these

**Comment by enki-hq** [comment]
Failed parsing files: 
  - Python/Core/classes-i/python-inheritance.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - Python/Core/classes-ii/private-variables.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - Python/Core/functions/nested-functions.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - Python/Core/is-your-python-healthy/exception-handling.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - Python/Core/tips/chain-comparison-operators.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.

**Comment by enki-hq** [comment]
Failed parsing files: 
  - Python/Core/classes-i/python-inheritance.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - Python/Core/classes-ii/private-variables.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - Python/Core/functions/nested-functions.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - Python/Core/is-your-python-healthy/exception-handling.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - Python/Core/tips/chain-comparison-operators.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.

**Comment by enki-hq** [comment]
Failed parsing files: 
  - Python/Core/classes-i/python-inheritance.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - Python/Core/classes-ii/private-variables.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - Python/Core/functions/nested-functions.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - Python/Core/is-your-python-healthy/exception-handling.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - Python/Core/tips/chain-comparison-operators.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.

**Comment by enki-hq** [comment]
Failed parsing files: 
  - Python/Core/classes-i/python-inheritance.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - Python/Core/classes-ii/private-variables.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - Python/Core/functions/nested-functions.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - Python/Core/is-your-python-healthy/exception-handling.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.
  - Python/Core/tips/chain-comparison-operators.md: 
 > Must have exactly 1 yaml configuration but found 0 instead.

**Comment by enki-hq** [comment]
### Insight previews:
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/python/core/classes-i/python-inheritance.md?ref=bfd273309c91751f2b85b33d62b47abe320d3701
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/python/core/classes-ii/private-variables.md?ref=bfd273309c91751f2b85b33d62b47abe320d3701
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/python/core/control-structures/chain-comparison-operators.md?ref=bfd273309c91751f2b85b33d62b47abe320d3701
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/python/core/functions/nested-functions.md?ref=bfd273309c91751f2b85b33d62b47abe320d3701
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/python/core/is-your-python-healthy/exception-handling.md?ref=bfd273309c91751f2b85b33d62b47abe320d3701

**Pull request merged**
