### PR TITLE
SQL - Improve consistency

### PR DESCRIPTION
**Pull request by kapnobatai137**
Improved the consistency in using quotation marks, backticks and bold/italic.

### CODE REVIEW

**Comment by enki-hq** [comment]
### Insight previews:
- [ ] [enkidevs/curriculum/sql/ddl/alter/alter-characteristics.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/sql/ddl/alter/alter-characteristics.md?ref=9b9b24c6f006e84bfd7cd3ed4105af51d712bb0a)
- [ ] [enkidevs/curriculum/sql/ddl/create/check-constraint.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/sql/ddl/create/check-constraint.md?ref=9b9b24c6f006e84bfd7cd3ed4105af51d712bb0a)
- [ ] [enkidevs/curriculum/sql/ddl/data-types/collation.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/sql/ddl/data-types/collation.md?ref=9b9b24c6f006e84bfd7cd3ed4105af51d712bb0a)
- [ ] [enkidevs/curriculum/sql/ddl/data-types/encoding.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/sql/ddl/data-types/encoding.md?ref=9b9b24c6f006e84bfd7cd3ed4105af51d712bb0a)
- [ ] [enkidevs/curriculum/sql/ddl/indices/when-to-add-indexes.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/sql/ddl/indices/when-to-add-indexes.md?ref=9b9b24c6f006e84bfd7cd3ed4105af51d712bb0a)
- [ ] [enkidevs/curriculum/sql/dql/aggregate-queries/avg-clause.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/sql/dql/aggregate-queries/avg-clause.md?ref=9b9b24c6f006e84bfd7cd3ed4105af51d712bb0a)
- [ ] [enkidevs/curriculum/sql/dql/aggregate-queries/count-clause.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/sql/dql/aggregate-queries/count-clause.md?ref=9b9b24c6f006e84bfd7cd3ed4105af51d712bb0a)
- [ ] [enkidevs/curriculum/sql/dql/basic-queries/select.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/sql/dql/basic-queries/select.md?ref=9b9b24c6f006e84bfd7cd3ed4105af51d712bb0a)
- [ ] [enkidevs/curriculum/sql/dql/basic-queries/where-2.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/sql/dql/basic-queries/where-2.md?ref=9b9b24c6f006e84bfd7cd3ed4105af51d712bb0a)
- [ ] [enkidevs/curriculum/sql/dql/basic-queries/where-3.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/sql/dql/basic-queries/where-3.md?ref=9b9b24c6f006e84bfd7cd3ed4105af51d712bb0a)
- [ ] [enkidevs/curriculum/sql/dql/basic-queries/where.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/sql/dql/basic-queries/where.md?ref=9b9b24c6f006e84bfd7cd3ed4105af51d712bb0a)
- [ ] [enkidevs/curriculum/sql/dql/joins/full-join.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/sql/dql/joins/full-join.md?ref=9b9b24c6f006e84bfd7cd3ed4105af51d712bb0a)
- [ ] [enkidevs/curriculum/sql/dql/write/delete-clause.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/sql/dql/write/delete-clause.md?ref=9b9b24c6f006e84bfd7cd3ed4105af51d712bb0a)
- [ ] [enkidevs/curriculum/sql/dql/write/update-clause.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/sql/dql/write/update-clause.md?ref=9b9b24c6f006e84bfd7cd3ed4105af51d712bb0a)

**Comment by kapnobatai137** [comment]
image

which one do you think we should use? I have currently formatted it as `C`. @nem035

**Comment by nem035** [comment]
@kapnobatai137 `C` works (but note that you missed an `é`)

**Comment by kapnobatai137** [comment]
> @kapnobatai137 `C` works (but note that you missed an `é`)

nice spot. saw that when I made the screenshot, changed the content but didn't make a new screenshot.

**Pull request merged**
