### PR TITLE
Add type in the gap to python functional programming 

### PR DESCRIPTION
**Pull request by Stefan-Stojanovic**
Marked if applied to all insights:

- [x] Shorten all Headlines (If possible)
- [x] Remove all backticks from every headline
- [x] Add type in the gap and change context to standalone to all applicable questions
- [x] Modify questions to support type in the gap (if possible)

### CODE REVIEW

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| is-python-functional-language | <ul><li>`Is Python a functional language?` pointing to `https://www.quora.com/Is-Python-a-functional-language` is broken because `HTTP_403`</li></ul> |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| is-python-functional-language | <ul><li>`Is Python a functional language?` pointing to `https://www.quora.com/Is-Python-a-functional-language` is broken because `HTTP_403`</li></ul> |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by Stefan-Stojanovic** [comment]
> ### Insight
> Insight Name	Error Message
> is-python-functional-language	
> * `Is Python a functional language?` pointing to `https://www.quora.com/Is-Python-a-functional-language` is broken because `HTTP_403`
> 
> > If you notice anything wrong with these rules contact [andrei@enki.com](mailto:andrei@enki.com).

@kapnobatai137 If I remember correctly we should ignore this type of error?

**Comment by nem035** [comment]
@Stefan-Stojanovic the problem with that specific link is that Quora is a closed system, not open to the public. If you take a closer look, the error received was a [`403`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403), which typically means "you don't have access to this resource".

We should probably change the link entirely to a reputable public site.

**Comment by enki-hq** [comment]
### Insight previews:
- [ ] [enkidevs/curriculum/python/functional-programming/arrays-i/the-all-built-in-function.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/python/functional-programming/arrays-i/the-all-built-in-function.md?ref=07440f7a50162a31ed46d7b3a50b4cc8502a6f64)
- [ ] [enkidevs/curriculum/python/functional-programming/arrays-i/the-reversed-built-in-function.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/python/functional-programming/arrays-i/the-reversed-built-in-function.md?ref=07440f7a50162a31ed46d7b3a50b4cc8502a6f64)
- [ ] [enkidevs/curriculum/python/functional-programming/arrays-i/the-slice-built-in-function.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/python/functional-programming/arrays-i/the-slice-built-in-function.md?ref=07440f7a50162a31ed46d7b3a50b4cc8502a6f64)
- [ ] [enkidevs/curriculum/python/functional-programming/arrays-i/the-sum-built-in-function.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/python/functional-programming/arrays-i/the-sum-built-in-function.md?ref=07440f7a50162a31ed46d7b3a50b4cc8502a6f64)
- [ ] [enkidevs/curriculum/python/functional-programming/arrays-i/the-zip-built-in-function.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/python/functional-programming/arrays-i/the-zip-built-in-function.md?ref=07440f7a50162a31ed46d7b3a50b4cc8502a6f64)
- [ ] [enkidevs/curriculum/python/functional-programming/arrays-ii/the-filter-built-in-function.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/python/functional-programming/arrays-ii/the-filter-built-in-function.md?ref=07440f7a50162a31ed46d7b3a50b4cc8502a6f64)
- [ ] [enkidevs/curriculum/python/functional-programming/arrays-ii/the-map-built-in-function.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/python/functional-programming/arrays-ii/the-map-built-in-function.md?ref=07440f7a50162a31ed46d7b3a50b4cc8502a6f64)
- [ ] [enkidevs/curriculum/python/functional-programming/arrays-ii/the-max-built-in-function.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/python/functional-programming/arrays-ii/the-max-built-in-function.md?ref=07440f7a50162a31ed46d7b3a50b4cc8502a6f64)
- [ ] [enkidevs/curriculum/python/functional-programming/arrays-ii/the-reduce-built-in-function.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/python/functional-programming/arrays-ii/the-reduce-built-in-function.md?ref=07440f7a50162a31ed46d7b3a50b4cc8502a6f64)
- [ ] [enkidevs/curriculum/python/functional-programming/arrays-ii/the-sorted-built-in-function-ii.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/python/functional-programming/arrays-ii/the-sorted-built-in-function-ii.md?ref=07440f7a50162a31ed46d7b3a50b4cc8502a6f64)
- [ ] [enkidevs/curriculum/python/functional-programming/arrays-ii/the-sorted-built-in-function.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/python/functional-programming/arrays-ii/the-sorted-built-in-function.md?ref=07440f7a50162a31ed46d7b3a50b4cc8502a6f64)
- [ ] [enkidevs/curriculum/python/functional-programming/comprehension/list-comprehension.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/python/functional-programming/comprehension/list-comprehension.md?ref=07440f7a50162a31ed46d7b3a50b4cc8502a6f64)
- [ ] [enkidevs/curriculum/python/functional-programming/comprehension/nested-lists-comprehension.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/python/functional-programming/comprehension/nested-lists-comprehension.md?ref=07440f7a50162a31ed46d7b3a50b4cc8502a6f64)
- [ ] [enkidevs/curriculum/python/functional-programming/comprehension/set-comprehension.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/python/functional-programming/comprehension/set-comprehension.md?ref=07440f7a50162a31ed46d7b3a50b4cc8502a6f64)
- [ ] [enkidevs/curriculum/python/functional-programming/comprehension/speed-up-your-for-loop-using-map-or-list-comprehensions.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/python/functional-programming/comprehension/speed-up-your-for-loop-using-map-or-list-comprehensions.md?ref=07440f7a50162a31ed46d7b3a50b4cc8502a6f64)
- [ ] [enkidevs/curriculum/python/functional-programming/decorators/decorators-methods.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/python/functional-programming/decorators/decorators-methods.md?ref=07440f7a50162a31ed46d7b3a50b4cc8502a6f64)
- [ ] [enkidevs/curriculum/python/functional-programming/decorators/decorators-syntax.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/python/functional-programming/decorators/decorators-syntax.md?ref=07440f7a50162a31ed46d7b3a50b4cc8502a6f64)
- [ ] [enkidevs/curriculum/python/functional-programming/decorators/functools-wraps.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/python/functional-programming/decorators/functools-wraps.md?ref=07440f7a50162a31ed46d7b3a50b4cc8502a6f64)
- [ ] [enkidevs/curriculum/python/functional-programming/decorators/what-are-decorators.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/python/functional-programming/decorators/what-are-decorators.md?ref=07440f7a50162a31ed46d7b3a50b4cc8502a6f64)
- [ ] [enkidevs/curriculum/python/functional-programming/decorators/what-is-a-closure.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/python/functional-programming/decorators/what-is-a-closure.md?ref=07440f7a50162a31ed46d7b3a50b4cc8502a6f64)
- [ ] [enkidevs/curriculum/python/functional-programming/functional-programming-ii/functional-particularities-of-python.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/python/functional-programming/functional-programming-ii/functional-particularities-of-python.md?ref=07440f7a50162a31ed46d7b3a50b4cc8502a6f64)
- [ ] [enkidevs/curriculum/python/functional-programming/functional-programming-ii/functions-vs-procedures.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/python/functional-programming/functional-programming-ii/functions-vs-procedures.md?ref=07440f7a50162a31ed46d7b3a50b4cc8502a6f64)
- [ ] [enkidevs/curriculum/python/functional-programming/functional-programming-ii/is-python-functional-language.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/python/functional-programming/functional-programming-ii/is-python-functional-language.md?ref=07440f7a50162a31ed46d7b3a50b4cc8502a6f64)
- [ ] [enkidevs/curriculum/python/functional-programming/functional-programming-ii/lambda-functions.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/python/functional-programming/functional-programming-ii/lambda-functions.md?ref=07440f7a50162a31ed46d7b3a50b4cc8502a6f64)
- [ ] [enkidevs/curriculum/python/functional-programming/functional-programming/what-is-functional-programming.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/python/functional-programming/functional-programming/what-is-functional-programming.md?ref=07440f7a50162a31ed46d7b3a50b4cc8502a6f64)
- [ ] [enkidevs/curriculum/python/functional-programming/functional-programming/why-functional-programming-ii.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/python/functional-programming/functional-programming/why-functional-programming-ii.md?ref=07440f7a50162a31ed46d7b3a50b4cc8502a6f64)
- [ ] [enkidevs/curriculum/python/functional-programming/functional-programming/why-functional-programming-iii.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/python/functional-programming/functional-programming/why-functional-programming-iii.md?ref=07440f7a50162a31ed46d7b3a50b4cc8502a6f64)
- [ ] [enkidevs/curriculum/python/functional-programming/functional-programming/why-functional-programming.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/python/functional-programming/functional-programming/why-functional-programming.md?ref=07440f7a50162a31ed46d7b3a50b4cc8502a6f64)
- [ ] [enkidevs/curriculum/python/functional-programming/generators/benefits-of-using-generators.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/python/functional-programming/generators/benefits-of-using-generators.md?ref=07440f7a50162a31ed46d7b3a50b4cc8502a6f64)
- [ ] [enkidevs/curriculum/python/functional-programming/generators/generator-of-generators.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/python/functional-programming/generators/generator-of-generators.md?ref=07440f7a50162a31ed46d7b3a50b4cc8502a6f64)
- [ ] [enkidevs/curriculum/python/functional-programming/generators/recursive-generator.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/python/functional-programming/generators/recursive-generator.md?ref=07440f7a50162a31ed46d7b3a50b4cc8502a6f64)
- [ ] [enkidevs/curriculum/python/functional-programming/generators/what-are-generators.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/python/functional-programming/generators/what-are-generators.md?ref=07440f7a50162a31ed46d7b3a50b4cc8502a6f64)
- [ ] [enkidevs/curriculum/python/functional-programming/generators/yield-and-next.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/python/functional-programming/generators/yield-and-next.md?ref=07440f7a50162a31ed46d7b3a50b4cc8502a6f64)
- [ ] [enkidevs/curriculum/python/functional-programming/iterators/iterators-applications.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/python/functional-programming/iterators/iterators-applications.md?ref=07440f7a50162a31ed46d7b3a50b4cc8502a6f64)
- [ ] [enkidevs/curriculum/python/functional-programming/iterators/the-iteration-protocol.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/python/functional-programming/iterators/the-iteration-protocol.md?ref=07440f7a50162a31ed46d7b3a50b4cc8502a6f64)
- [ ] [enkidevs/curriculum/python/functional-programming/iterators/the-itertools-module-ii.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/python/functional-programming/iterators/the-itertools-module-ii.md?ref=07440f7a50162a31ed46d7b3a50b4cc8502a6f64)
- [ ] [enkidevs/curriculum/python/functional-programming/iterators/the-itertools-module.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/python/functional-programming/iterators/the-itertools-module.md?ref=07440f7a50162a31ed46d7b3a50b4cc8502a6f64)
- [ ] [enkidevs/curriculum/python/functional-programming/iterators/what-are-iterators.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/python/functional-programming/iterators/what-are-iterators.md?ref=07440f7a50162a31ed46d7b3a50b4cc8502a6f64)
- [ ] [enkidevs/curriculum/python/functional-programming/iterators/what-is-an-iterable.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/python/functional-programming/iterators/what-is-an-iterable.md?ref=07440f7a50162a31ed46d7b3a50b4cc8502a6f64)
- [ ] [enkidevs/curriculum/python/functional-programming/python-immutability/atomicity-of-failure.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/python/functional-programming/python-immutability/atomicity-of-failure.md?ref=07440f7a50162a31ed46d7b3a50b4cc8502a6f64)
- [ ] [enkidevs/curriculum/python/functional-programming/python-immutability/avoiding-identity-mutation.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/python/functional-programming/python-immutability/avoiding-identity-mutation.md?ref=07440f7a50162a31ed46d7b3a50b4cc8502a6f64)
- [ ] [enkidevs/curriculum/python/functional-programming/python-immutability/distinguish-the-mutability-of-common-types.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/python/functional-programming/python-immutability/distinguish-the-mutability-of-common-types.md?ref=07440f7a50162a31ed46d7b3a50b4cc8502a6f64)
- [ ] [enkidevs/curriculum/python/functional-programming/python-immutability/immutability-gotchas.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/python/functional-programming/python-immutability/immutability-gotchas.md?ref=07440f7a50162a31ed46d7b3a50b4cc8502a6f64)
- [ ] [enkidevs/curriculum/python/functional-programming/python-immutability/what-is-immutability.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/python/functional-programming/python-immutability/what-is-immutability.md?ref=07440f7a50162a31ed46d7b3a50b4cc8502a6f64)
- [ ] [enkidevs/curriculum/python/functional-programming/python-immutability/why-types-have-immutability-ii.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/python/functional-programming/python-immutability/why-types-have-immutability-ii.md?ref=07440f7a50162a31ed46d7b3a50b4cc8502a6f64)
- [ ] [enkidevs/curriculum/python/functional-programming/python-immutability/why-types-have-immutability.md](https://app.enkipro.com/public/preview-insight/enkidevs/curriculum/python/functional-programming/python-immutability/why-types-have-immutability.md?ref=07440f7a50162a31ed46d7b3a50b4cc8502a6f64)

**Review by kapnobatai137 — DISMISSED** [review]

**Comment by enki-hq** [comment]
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| functional-particularities-of-python | <ul><li>`Functional Programming in Python` pointing to `http://www.oreilly.com/programming/free/files/functional-programming-python.pdf` is broken because `HTTP_404`</li></ul> |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Review by kapnobatai137 — APPROVED** [review]

**Pull request merged**
