### PR TITLE
Update splice.md

### PR DESCRIPTION
**Pull request by Stefan-Stojanovic**
Add missing information regarding the *delete* argument for the Splice function

### CODE REVIEW

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Review by nem035 — DISMISSED** [review]
looks good, just don't forget the changelog entry :+1:

**Comment by Stefan-Stojanovic** [comment]
> looks good, just don't forget the changelog entry 👍

I know, just waiting until we can merge to add the commit. In case its fixed tomorrow I don't have to commit twice to update the changelog date entry

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Insight previews:
- [ ] [enkidevs/curriculum/javascript/javascript-core/arrays/splice.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/javascript/javascript-core/arrays/splice.md?ref=beef3041862fe9c5b36c26d56bf0bfb2221f8672)

**Comment by Stefan-Stojanovic** [comment]
Closing because of structural changes to the content

**Pull request closed without merging**
