### PR TITLE
Update forms

### PR DESCRIPTION
**Pull request by Stefan-Stojanovic**

### CODE REVIEW

**Comment by enki-hq** [comment]
Rule insight:code-width failed for files: 
  - Web/HTML/forms/check-boxes.md

**Comment by enki-hq** [comment]
Rule insight:questions failed for files: 
  - Web/HTML/forms/check-boxes.md

**Comment by enki-hq** [comment]
### Insight previews:
- [ ] https://enkipro.compreview-insight/enkidevs/curriculum/Web/HTML/forms/check-boxes.md?ref=648f43c157ccf469b8e5ecedadb0ec9f00d07561

**Comment by enki-hq** [comment]
Rule insight:questions failed for files: 
  - Web/HTML/forms/checkbox-groups

**Comment by enki-hq** [comment]
Rule insight:questions failed for files: 
  - Web/HTML/forms/checkbox-groups

**Comment by enki-hq** [comment]
Rule workout:insights failed for files: 
  - Web/HTML/forms/README.md

**Comment by enki-hq** [comment]
Rule insight:questions failed for files: 
  - Web/HTML/forms/checkbox-groups

**Comment by enki-hq** [comment]
Rule workout:insights failed for files: 
  - Web/HTML/forms/README.md

**Comment by enki-hq** [comment]
Rule insight:questions failed for files: 
  - Web/HTML/forms/checkbox-groups

**Comment by enki-hq** [comment]
Rule insight:quiz failed for files: 
  - Web/HTML/forms/dropdown-list.md

**Comment by enki-hq** [comment]
Rule workout:insights failed for files: 
  - Web/HTML/forms/README.md

**Comment by enki-hq** [comment]
Rule insight:questions failed for files: 
  - Web/HTML/forms/checkbox-groups

**Comment by enki-hq** [comment]
Rule insight:quiz failed for files: 
  - Web/HTML/forms/dropdown-list.md

**Comment by enki-hq** [comment]
Rule workout:insights failed for files: 
  - Web/HTML/forms/README.md

**Comment by enki-hq** [comment]
Rule insight:questions failed for files: 
  - Web/HTML/forms/checkbox-groups

**Comment by enki-hq** [comment]
Rule workout:insights failed for files: 
  - Web/HTML/forms/README.md

**Comment by enki-hq** [comment]
Rule insight:questions failed for files: 
  - Web/HTML/forms/checkbox-groups.md

**Comment by enki-hq** [comment]
Rule workout:insights failed for files: 
  - Web/HTML/forms/README.md

**Comment by Loopiezlol** [comment]
Hey @Stefan-Stojanovic 

The `workout:insights — Workout "insights" must exist in database or as new files.` rule works in the following way:
- takes the insight slugs in the `insights` field of the workout readme
- remove from this set all insights that were modified in the same PR  (file changed)
- if all insights were matched, the rule passes
- if there are insights unmatched, it checks the db for them and if they match the rule passes
- if there are insights that don't get matched then the rule fails

what happens here is that your changes will be applied to a branch `html-course-2`. the files referenced by the insights field (intro-form, text-field etc.) don't exist on `master` and hence nor in the db

what you can do is just trigger a change (add a whitespace if not something else) to the rest of the files referenced

**Comment by enki-hq** [comment]
Rule workout:insights failed for files: 
  - Web/HTML/forms/README.md

**Comment by enki-hq** [comment]
Failed parsing files: 
  - Web/HTML/forms/README.md: 
 > bad indentation of a mapping entry at line 16, column 2:
     - check-boxes 
     ^

**Comment by enki-hq** [comment]
Rule workout:insights failed for files: 
  - Web/HTML/forms/README.md

**Comment by enki-hq** [comment]
Rule workout:insights failed for files: 
  - Web/HTML/forms/README.md

**Comment by enki-hq** [comment]
Rule workout:insights failed for files: 
  - Web/HTML/forms/README.md

**Comment by enki-hq** [comment]
Rule workout:insights failed for files: 
  - Web/HTML/forms/README.md

**Comment by lizTheDeveloper** [comment]
This has been migrated into #766

**Pull request closed without merging**
