### PR TITLE
Comp. Sci. - Type in/Standalone

### PR DESCRIPTION
**Pull request by mihaiberq**
Testing first workout for errors for now

### CODE REVIEW

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| 0-1-knapsack-problem | <ul><li>`A More in-Depth Explanation of the Problem` pointing to `https://www.quora.com/Whats-an-intuitive-explanation-for-the-0-1-knapsack-problem-in-data-structures-and-algorithms` is broken because `HTTP_403`</li></ul> |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| 0-1-knapsack-problem | <ul><li>`A More in-Depth Explanation of the Problem` pointing to `https://www.quora.com/Whats-an-intuitive-explanation-for-the-0-1-knapsack-problem-in-data-structures-and-algorithms` is broken because `HTTP_403`</li></ul> |
| dns-purpose-1 | <ul><li>`What Is DNS?` pointing to `https://www.cloudflare.com/en-gb/learning/dns/what-is-dns/` is broken because `HTTP_403`</li></ul> |
| dns-purpose-2 | <ul><li>`What Is DNS?` pointing to `https://www.cloudflare.com/en-gb/learning/dns/what-is-dns/` is broken because `HTTP_403`</li></ul> |
| dns-purpose-3 | <ul><li>`What Is DNS?` pointing to `https://www.cloudflare.com/en-gb/learning/dns/what-is-dns/` is broken because `HTTP_403`</li></ul> |
| dns-hierarchy-3 | <ul><li>`What is a Domain Name Registrar?` pointing to `https://www.cloudflare.com/en-gb/learning/dns/glossary/what-is-a-domain-name-registrar/` is broken because `HTTP_403`</li></ul> |
| dns-duplicity | <ul><li>`What is Anycast?` pointing to `https://www.cloudflare.com/en-gb/learning/cdn/glossary/anycast-network/` is broken because `HTTP_403`</li></ul> |
| dns-hierarchy-4 | <ul><li>`What Is DNS?` pointing to `https://www.cloudflare.com/en-gb/learning/dns/what-is-dns/` is broken because `HTTP_403`</li></ul> |
| dns-hierarchy-1 | Link checking took too long. Verify it manually. |
| dns-hierarchy-2 | Link checking took too long. Verify it manually. |
### Changelog

| File Name | Error Message |
|:-:|:-:|
| Pull Request | Couldn't find a CHANGELOG entry for this pull request. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| 0-1-knapsack-problem | <ul><li>`A More in-Depth Explanation of the Problem` pointing to `https://www.quora.com/Whats-an-intuitive-explanation-for-the-0-1-knapsack-problem-in-data-structures-and-algorithms` is broken because `HTTP_403`</li></ul> |
| dns-purpose-2 | <ul><li>`What Is DNS?` pointing to `https://www.cloudflare.com/en-gb/learning/dns/what-is-dns/` is broken because `HTTP_403`</li></ul> |
| dns-purpose-3 | <ul><li>`What Is DNS?` pointing to `https://www.cloudflare.com/en-gb/learning/dns/what-is-dns/` is broken because `HTTP_403`</li></ul> |
| dns-purpose-1 | <ul><li>`What Is DNS?` pointing to `https://www.cloudflare.com/en-gb/learning/dns/what-is-dns/` is broken because `HTTP_403`</li></ul> |
| dns-hierarchy-3 | <ul><li>`What is a Domain Name Registrar?` pointing to `https://www.cloudflare.com/en-gb/learning/dns/glossary/what-is-a-domain-name-registrar/` is broken because `HTTP_403`</li></ul> |
| dns-hierarchy-4 | <ul><li>`What Is DNS?` pointing to `https://www.cloudflare.com/en-gb/learning/dns/what-is-dns/` is broken because `HTTP_403`</li></ul> |
| dns-duplicity | <ul><li>`What is Anycast?` pointing to `https://www.cloudflare.com/en-gb/learning/cdn/glossary/anycast-network/` is broken because `HTTP_403`</li></ul> |
| a-request-example | <ul><li>`What is an "HTTP request"?` pointing to `https://www.quora.com/What-is-an-HTTP-request` is broken because `HTTP_403`</li></ul> |
| dns-hierarchy-1 | Link checking took too long. Verify it manually. |
| dns-hierarchy-2 | Link checking took too long. Verify it manually. |
| network-models-tcp-ip | Insight doesn't have a revision question but it has formats and context for it. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by mihaiberq** [comment]
i tested the links manually and they all work when clicked from a regular machine. cloudflare probably has bot protection in place which breaks it. 

Imo we can disregard those errors

**Comment by enki-hq** [comment]
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| 0-1-knapsack-problem | <ul><li>`A More in-Depth Explanation of the Problem` pointing to `https://www.quora.com/Whats-an-intuitive-explanation-for-the-0-1-knapsack-problem-in-data-structures-and-algorithms` is broken because `HTTP_403`</li></ul> |
| dns-purpose-1 | <ul><li>`What Is DNS?` pointing to `https://www.cloudflare.com/en-gb/learning/dns/what-is-dns/` is broken because `HTTP_403`</li></ul> |
| dns-purpose-3 | <ul><li>`What Is DNS?` pointing to `https://www.cloudflare.com/en-gb/learning/dns/what-is-dns/` is broken because `HTTP_403`</li></ul> |
| dns-purpose-2 | <ul><li>`What Is DNS?` pointing to `https://www.cloudflare.com/en-gb/learning/dns/what-is-dns/` is broken because `HTTP_403`</li></ul> |
| dns-hierarchy-3 | <ul><li>`What is a Domain Name Registrar?` pointing to `https://www.cloudflare.com/en-gb/learning/dns/glossary/what-is-a-domain-name-registrar/` is broken because `HTTP_403`</li></ul> |
| dns-hierarchy-4 | <ul><li>`What Is DNS?` pointing to `https://www.cloudflare.com/en-gb/learning/dns/what-is-dns/` is broken because `HTTP_403`</li></ul> |
| dns-duplicity | <ul><li>`What is Anycast?` pointing to `https://www.cloudflare.com/en-gb/learning/cdn/glossary/anycast-network/` is broken because `HTTP_403`</li></ul> |
| a-request-example | <ul><li>`What is an "HTTP request"?` pointing to `https://www.quora.com/What-is-an-HTTP-request` is broken because `HTTP_403`</li></ul> |
| dns-hierarchy-1 | Link checking took too long. Verify it manually. |
| dns-hierarchy-2 | Link checking took too long. Verify it manually. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by kapnobatai137** [comment]
> i tested the links manually and they all work when clicked from a regular machine. cloudflare probably has bot protection in place which breaks it.
> 
> Imo we can disregard those errors

yeah, I think so as well. I've noticed it always fails for the cloudflare links although they're not dead

like you said, ignore the rule :+1:

**Comment by enki-hq** [comment]
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| 0-1-knapsack-problem | <ul><li>`A More in-Depth Explanation of the Problem` pointing to `https://www.quora.com/Whats-an-intuitive-explanation-for-the-0-1-knapsack-problem-in-data-structures-and-algorithms` is broken because `HTTP_403`</li></ul> |
| dns-purpose-1 | <ul><li>`What Is DNS?` pointing to `https://www.cloudflare.com/en-gb/learning/dns/what-is-dns/` is broken because `HTTP_403`</li></ul> |
| dns-purpose-3 | <ul><li>`What Is DNS?` pointing to `https://www.cloudflare.com/en-gb/learning/dns/what-is-dns/` is broken because `HTTP_403`</li></ul> |
| dns-purpose-2 | <ul><li>`What Is DNS?` pointing to `https://www.cloudflare.com/en-gb/learning/dns/what-is-dns/` is broken because `HTTP_403`</li></ul> |
| dns-hierarchy-4 | <ul><li>`What Is DNS?` pointing to `https://www.cloudflare.com/en-gb/learning/dns/what-is-dns/` is broken because `HTTP_403`</li></ul> |
| dns-hierarchy-3 | <ul><li>`What is a Domain Name Registrar?` pointing to `https://www.cloudflare.com/en-gb/learning/dns/glossary/what-is-a-domain-name-registrar/` is broken because `HTTP_403`</li></ul> |
| dns-duplicity | <ul><li>`What is Anycast?` pointing to `https://www.cloudflare.com/en-gb/learning/cdn/glossary/anycast-network/` is broken because `HTTP_403`</li></ul> |
| a-request-example | <ul><li>`What is an "HTTP request"?` pointing to `https://www.quora.com/What-is-an-HTTP-request` is broken because `HTTP_403`</li></ul> |
| client-error-status-codes | Link checking took too long. Verify it manually. |
| dns-hierarchy-1 | Link checking took too long. Verify it manually. |
| dns-hierarchy-2 | Link checking took too long. Verify it manually. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| 0-1-knapsack-problem | <ul><li>`A More in-Depth Explanation of the Problem` pointing to `https://www.quora.com/Whats-an-intuitive-explanation-for-the-0-1-knapsack-problem-in-data-structures-and-algorithms` is broken because `HTTP_403`</li></ul> |
| dns-purpose-1 | <ul><li>`What Is DNS?` pointing to `https://www.cloudflare.com/en-gb/learning/dns/what-is-dns/` is broken because `HTTP_403`</li></ul> |
| dns-purpose-2 | <ul><li>`What Is DNS?` pointing to `https://www.cloudflare.com/en-gb/learning/dns/what-is-dns/` is broken because `HTTP_403`</li></ul> |
| dns-purpose-3 | <ul><li>`What Is DNS?` pointing to `https://www.cloudflare.com/en-gb/learning/dns/what-is-dns/` is broken because `HTTP_403`</li></ul> |
| dns-hierarchy-3 | <ul><li>`What is a Domain Name Registrar?` pointing to `https://www.cloudflare.com/en-gb/learning/dns/glossary/what-is-a-domain-name-registrar/` is broken because `HTTP_403`</li></ul> |
| dns-hierarchy-4 | <ul><li>`What Is DNS?` pointing to `https://www.cloudflare.com/en-gb/learning/dns/what-is-dns/` is broken because `HTTP_403`</li></ul> |
| dns-duplicity | <ul><li>`What is Anycast?` pointing to `https://www.cloudflare.com/en-gb/learning/cdn/glossary/anycast-network/` is broken because `HTTP_403`</li></ul> |
| a-request-example | <ul><li>`What is an "HTTP request"?` pointing to `https://www.quora.com/What-is-an-HTTP-request` is broken because `HTTP_403`</li></ul> |
| dns-hierarchy-1 | Link checking took too long. Verify it manually. |
| dns-hierarchy-2 | Link checking took too long. Verify it manually. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| 0-1-knapsack-problem | <ul><li>`A More in-Depth Explanation of the Problem` pointing to `https://www.quora.com/Whats-an-intuitive-explanation-for-the-0-1-knapsack-problem-in-data-structures-and-algorithms` is broken because `HTTP_403`</li></ul> |
| dns-purpose-2 | <ul><li>`What Is DNS?` pointing to `https://www.cloudflare.com/en-gb/learning/dns/what-is-dns/` is broken because `HTTP_403`</li></ul> |
| dns-purpose-1 | <ul><li>`What Is DNS?` pointing to `https://www.cloudflare.com/en-gb/learning/dns/what-is-dns/` is broken because `HTTP_403`</li></ul> |
| dns-purpose-3 | <ul><li>`What Is DNS?` pointing to `https://www.cloudflare.com/en-gb/learning/dns/what-is-dns/` is broken because `HTTP_403`</li></ul> |
| dns-hierarchy-4 | <ul><li>`What Is DNS?` pointing to `https://www.cloudflare.com/en-gb/learning/dns/what-is-dns/` is broken because `HTTP_403`</li></ul> |
| dns-hierarchy-3 | <ul><li>`What is a Domain Name Registrar?` pointing to `https://www.cloudflare.com/en-gb/learning/dns/glossary/what-is-a-domain-name-registrar/` is broken because `HTTP_403`</li></ul> |
| dns-duplicity | <ul><li>`What is Anycast?` pointing to `https://www.cloudflare.com/en-gb/learning/cdn/glossary/anycast-network/` is broken because `HTTP_403`</li></ul> |
| a-request-example | <ul><li>`What is an "HTTP request"?` pointing to `https://www.quora.com/What-is-an-HTTP-request` is broken because `HTTP_403`</li></ul> |
| dns-hierarchy-1 | Link checking took too long. Verify it manually. |
| dns-hierarchy-2 | Link checking took too long. Verify it manually. |
| dns-record-format-1 | Link checking took too long. Verify it manually. |
| dns-record-format-3 | Link checking took too long. Verify it manually. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by enki-hq** [comment]
### Insight

| Insight Name | Error Message |
|:-:|:-:|
| 0-1-knapsack-problem | <ul><li>`A More in-Depth Explanation of the Problem` pointing to `https://www.quora.com/Whats-an-intuitive-explanation-for-the-0-1-knapsack-problem-in-data-structures-and-algorithms` is broken because `HTTP_403`</li></ul> |
| dns-purpose-3 | <ul><li>`What Is DNS?` pointing to `https://www.cloudflare.com/en-gb/learning/dns/what-is-dns/` is broken because `HTTP_403`</li></ul> |
| dns-hierarchy-4 | <ul><li>`What Is DNS?` pointing to `https://www.cloudflare.com/en-gb/learning/dns/what-is-dns/` is broken because `HTTP_403`</li></ul> |
| dns-hierarchy-3 | <ul><li>`What is a Domain Name Registrar?` pointing to `https://www.cloudflare.com/en-gb/learning/dns/glossary/what-is-a-domain-name-registrar/` is broken because `HTTP_403`</li></ul> |
| dns-duplicity | <ul><li>`What is Anycast?` pointing to `https://www.cloudflare.com/en-gb/learning/cdn/glossary/anycast-network/` is broken because `HTTP_403`</li></ul> |
| a-request-example | <ul><li>`What is an "HTTP request"?` pointing to `https://www.quora.com/What-is-an-HTTP-request` is broken because `HTTP_403`</li></ul> |
| dns-purpose-2 | <ul><li>`What Is DNS?` pointing to `https://www.cloudflare.com/en-gb/learning/dns/what-is-dns/` is broken because `HTTP_403`</li></ul> |
| dns-purpose-1 | <ul><li>`What Is DNS?` pointing to `https://www.cloudflare.com/en-gb/learning/dns/what-is-dns/` is broken because `HTTP_403`</li></ul> |
| dns-hierarchy-1 | Link checking took too long. Verify it manually. |
| dns-hierarchy-2 | Link checking took too long. Verify it manually. |
| dns-record-format-2 | Link checking took too long. Verify it manually. |
| dns-record-format-5 | Link checking took too long. Verify it manually. |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Review by kapnobatai137 — APPROVED** [review]

**Pull request merged**
