### PR TITLE
Fixed typo for Java example

### PR DESCRIPTION
**Pull request by DejanPerovic**
I found a small typo in default-constructors.md

### CODE REVIEW

**Comment by enki-hq** [comment]
### Title

| File Name | Error Message |
|:-:|:-:|
| default-constructors | Insight title should be `` Default Constructors `` |

> If you notice anything wrong with these rules contact andrei@enki.com.

**Comment by DejanPerovic** [comment]
Hi,
Could you please explain to me what exactly this means?

> title:capitalization — Every title or headline should be capitalized following the The Chicago Manual of Style....

What should I change?

**Comment by enki-hq** [comment]
### Insight previews:
- [ ] [enkidevs/curriculum/java/fundamentals/class-dependency-i/default-constructors.md](https://app.enkipro.com/#/public/preview-insight/enkidevs/curriculum/java/fundamentals/class-dependency-i/default-constructors.md?ref=ab872391f932422e34416fe17548d4b9e9822fac)

**Comment by kapnobatai137** [comment]
Hello @DejanPerovic and thank you for the contribution :tada: 

You have done nothing wrong. We recently introduced a rule that enforces all the titles in our app the be capitalized. Because some of our older content doesn't have capitalized titles, the rule will be triggered when the file is edited.

In this case, the insight title was `# Default constructors` but we want it to be `# Default Constructors`.

I updated the title now, so there are no extra changes to make :muscle:

**Comment by DejanPerovic** [comment]
@kapnobatai137 
Good to know. All the best!

**Pull request merged**
